### ISSUE TITLE
java.lang.AssertionError at com.impossibl.postgres.jdbc.ThreadedHousekeeper.acquire()

### ISSUE THREAD

**Issue by cowwoc** [impossibl/pgjdbc-ng#125]
I am getting the following assert failure in my unit tests using https://github.com/impossibl/pgjdbc-ng/commit/5978d763a8677b891f70e55f9140069dc94ce5be:

```
15:07:04.408 [qtp2026575312-31] WARN  org.eclipse.jetty.servlet.ServletHandler.doHandle() - 
javax.servlet.ServletException: org.glassfish.jersey.server.ContainerException: java.lang.AssertionError
    at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:393)
    at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:381)
    at org.glassfish.jersey.servlet.ServletContainer.doFilter(ServletContainer.java:534)
    at org.glassfish.jersey.servlet.ServletContainer.doFilter(ServletContainer.java:482)
    at org.glassfish.jersey.servlet.ServletContainer.doFilter(ServletContainer.java:419)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1650)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:583)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
    at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1125)
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1059)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
    at org.eclipse.jetty.server.Server.handle(Server.java:497)
    at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
    at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:248)
    at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
    at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:610)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:539)
    at java.lang.Thread.run(Thread.java:745)
Caused by: org.glassfish.jersey.server.ContainerException: java.lang.AssertionError
    at org.glassfish.jersey.servlet.internal.ResponseWriter.rethrow(ResponseWriter.java:256)
    at org.glassfish.jersey.servlet.internal.ResponseWriter.failure(ResponseWriter.java:238)
    at org.glassfish.jersey.server.ServerRuntime$Responder.process(ServerRuntime.java:439)
    at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:277)
    at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
    at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
    at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
    at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
    at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
    at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:297)
    at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:254)
    at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1030)
    at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:373)
    ... 22 common frames omitted
Caused by: java.lang.AssertionError: null
    at com.impossibl.postgres.jdbc.ThreadedHousekeeper.acquire(ThreadedHousekeeper.java:93)
    at com.impossibl.postgres.jdbc.ConnectionUtil.createConnection(ConnectionUtil.java:154)
    at com.impossibl.postgres.jdbc.PGDriver.connect(PGDriver.java:77)
    at com.impossibl.postgres.jdbc.PGDriver.connect(PGDriver.java:52)
    at java.sql.DriverManager.getConnection(DriverManager.java:664)
    at java.sql.DriverManager.getConnection(DriverManager.java:208)
    at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:57)
    at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:63)
    at com.zaxxer.hikari.pool.HikariPool.addConnection(HikariPool.java:398)
    at com.zaxxer.hikari.pool.HikariPool.fillPool(HikariPool.java:474)
    at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:159)
    at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:112)
    at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:102)
    at com.realestate.backend.scope.TestHttpSingletonScope$DataSourceFactory.createValue(TestHttpSingletonScope.java:94)
    at com.realestate.backend.scope.TestHttpSingletonScope$DataSourceFactory.createValue(TestHttpSingletonScope.java:56)
    at org.bitbucket.cowwoc.pouch.ConcurrentLazyFactory.getValue(ConcurrentLazyFactory.java:79)
    at com.realestate.backend.scope.TestHttpSingletonScope.getDataSource(TestHttpSingletonScope.java:40)
    at com.realestate.backend.scope.DefaultRequestScope.getDataSource(DefaultRequestScope.java:65)
    at com.realestate.backend.scope.DefaultRequestScope$ConnectionFactory.createValue(DefaultRequestScope.java:172)
    at com.realestate.backend.scope.DefaultRequestScope$ConnectionFactory.createValue(DefaultRequestScope.java:147)
    at org.bitbucket.cowwoc.pouch.LazyReference.getValue(LazyReference.java:48)
    at org.bitbucket.cowwoc.pouch.LazyFactory.getValue(LazyFactory.java:47)
    at com.realestate.backend.scope.DefaultRequestScope.getConnection(DefaultRequestScope.java:113)
    at com.realestate.backend.Session.<init>(Session.java:56)
    at com.realestate.backend.scope.DefaultRequestScope$SessionFactory.createValue(DefaultRequestScope.java:210)
    at com.realestate.backend.scope.DefaultRequestScope$SessionFactory.createValue(DefaultRequestScope.java:205)
    at org.bitbucket.cowwoc.pouch.LazyReference.getValue(LazyReference.java:48)
    at org.bitbucket.cowwoc.pouch.LazyFactory.getValue(LazyFactory.java:47)
    at com.realestate.backend.scope.DefaultRequestScope.getSession(DefaultRequestScope.java:107)
    at com.realestate.backend.resource.AuthenticationsResource.createAuthentication(AuthenticationsResource.java:134)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
    at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:151)
    at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:171)
    at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:152)
    at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:104)
    at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:384)
    at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:342)
    at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:101)
    at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:271)
    ... 31 common frames omitted
```

I don't have concrete repro steps yet.

**Comment by cowwoc** [comment]
I think I know what is going on...
1. Thread 1 hits `if (instanceRefs.compareAndSet(0, 1))`, flipping the value from 0 to 1 and entering the first code block.
2. Thread 2 hits `if (instanceRefs.compareAndSet(0, 1))`, and enters the second code block.
3. Thread 2 executes `assert instance != null;` before Thread 1 has reached `instance = new ThreadedHousekeeper();`

In short: you need to lock over the entire code block instead of just over the first line. You can use [LazyConcurrentFactory](https://bitbucket.org/cowwoc/pouch/src/10a7c40c1ff8b7652eed68680f9cb1dfad1013d7/src/main/java/org/bitbucket/cowwoc/pouch/ConcurrentLazyFactory.java?at=default) (or equivalent) to achieve this. LazyConcurrentFactory is bundled as part of my library: https://bitbucket.org/cowwoc/pouch/

**Comment by kdubb** [comment]
This is a perfect example of premature optimization.  This is called in 1 place, while creating a connection, it should just be a snync'ed method.   It was idiotic to do anything else.

**Comment by cowwoc** [comment]
@kdubb It happens ;)

I suggest configuring your unit tests to run in parallel. This will make them run faster, as well as catching these kinds of bugs.

**Comment by kdubb** [comment]
Running unit tests in parallel will not work without some serious updates to the unit tests.  They create/drop schema a shared database.

**Comment by cowwoc** [comment]
@kdubb Here is what worked for me:

```
private static final AtomicInteger databaseId = new AtomicInteger();
private final String schema = "test" + databaseId.getAndIncrement();
[...]
// Create the schema
try (Connection connection = dataSource.getConnection())
{
    try (Statement statement = connection.createStatement())
    {
        statement.executeUpdate("DROP SCHEMA IF EXISTS " + schema + " CASCADE");
        statement.executeUpdate("CREATE SCHEMA IF NOT EXISTS " + schema);
        connection.commit();
    }
}
catch (SQLException e)
{
    throw new QueryException(e);
}
[...]
Flyway flyway = new Flyway();
flyway.setDataSource(result);
flyway.setSchemas(schema);
flyway.setLocations(...);
flyway.setPlaceholders(ImmutableMap.of("CREATE.TABLE", "CREATE UNLOGGED TABLE"));
flyway.setCallbacks(new FlywayCallbacks(schema));
flyway.setCleanOnValidationError(true);
flyway.migrate();
```

I've got one SQL script for populating the database. That script contains place-holders. Example:

```
${CREATE.TABLE} resource_redirected (type_id SMALLINT DEFAULT NEXTVAL('resource_redirected_sequence'),
    string_id VARCHAR(254), id BIGINT NOT NULL, modification_time TIMESTAMP NOT NULL,
    PRIMARY KEY (type_id, string_id), FOREIGN KEY (type_id) REFERENCES table_type(id));
```

Then, I have Flyway replace `$(CREATE.TABLE)` with either `CREATE TABLE` or `CREATE UNLOGGED TABLE` depending on whether I am running unit tests or the main codebase.

Each unit test runs against a different schema. You can play around with this and have them run against separate databases if you wish.
