### ISSUE TITLE
"LOCK TABLE t IN EXCLUSIVE MODE" broken

### ISSUE THREAD

**Issue by Redeeman** [impossibl/pgjdbc-ng#128]
when attempting to lock, i get this an exception, I have tested with official pg driver and it works.

```
        try( Statement stmt = conn.createStatement() ) {
            stmt.execute( "LOCK TABLE t IN EXCLUSIVE MODE" );
```

autocommit mode set to false

details:
                    PGConnectionPoolDataSource dataSource = new PGConnectionPoolDataSource();
                    dataSource.setDatabaseName( props.getProperty( "db.main.name" ) );
                    dataSource.setServerName( props.getProperty( "db.main.host" ) );
                    dataSource.setUser( props.getProperty( "db.main.user" ) );
                    dataSource.setPassword( props.getProperty( "db.main.password" ) );
                    dataSource.setPortNumber( Integer.parseInt( props.getProperty( "db.main.port" ) ) );
            ... 12 more
            Caused by: java.io.IOException: error parsing command tag
                at com.impossibl.postgres.protocol.v30.ProtocolImpl.receiveCommandComplete(ProtocolImpl.java:1129)
                at com.impossibl.postgres.protocol.v30.ProtocolImpl.dispatch(ProtocolImpl.java:833)
                at com.impossibl.postgres.protocol.v30.MessageHandler.channelRead(MessageHandler.java:46)
                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:332)
                at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:318)
                at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)
                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:332)
                at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:318)
                at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787)
                at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:125)
                at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:507)
                at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:464)
                at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:378)
                at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:350)
                at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
                ... 1 more

**Comment by kdubb** [comment]
Verified fixed by #259
