### ISSUE TITLE
Intervals are locale dependant (and fail unit tests).

### ISSUE THREAD

**Issue by ksmigrod** [impossibl/pgjdbc-ng#135]
I work on workstation with Polish locale 

``` bash
ksm@ksm-3360:~$ locale
LANG=pl_PL.UTF-8
LANGUAGE=pl_PL
LC_CTYPE="pl_PL.UTF-8"
LC_NUMERIC="pl_PL.UTF-8"
LC_TIME="pl_PL.UTF-8"
LC_COLLATE="pl_PL.UTF-8"
LC_MONETARY="pl_PL.UTF-8"
LC_MESSAGES="pl_PL.UTF-8"
LC_PAPER="pl_PL.UTF-8"
LC_NAME="pl_PL.UTF-8"
LC_ADDRESS="pl_PL.UTF-8"
LC_TELEPHONE="pl_PL.UTF-8"
LC_MEASUREMENT="pl_PL.UTF-8"
LC_IDENTIFICATION="pl_PL.UTF-8"
LC_ALL=
```

There is a peculiarity in decimal format. Polish locale specifies comma (,) as decimal separator, and dot (.) as thousands separator.

Two unit tests fail with the following errors:

CodecTest

```
Tests run: 360, Failures: 0, Errors: 3, Skipped: 0, Time elapsed: 43.116 sec <<< FAILURE! - in com.impossibl.postgres.jdbc.CodecTest
testTextCodecs[test-interval](com.impossibl.postgres.jdbc.CodecTest)  Time elapsed: 0.128 sec  <<< ERROR!
java.lang.IllegalArgumentException: invalid interval
    at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1250)
    at java.lang.Double.parseDouble(Double.java:540)
    at com.impossibl.postgres.api.data.Interval.setValue(Interval.java:168)
    at com.impossibl.postgres.api.data.Interval.<init>(Interval.java:76)
    at com.impossibl.postgres.system.procs.Intervals$TxtDecoder.decode(Intervals.java:135)
    at com.impossibl.postgres.system.procs.Intervals$TxtDecoder.decode(Intervals.java:120)
    at com.impossibl.postgres.system.procs.TextDecoder.decode(TextDecoder.java:51)
    at com.impossibl.postgres.jdbc.CodecTest.inOut(CodecTest.java:254)
    at com.impossibl.postgres.jdbc.CodecTest.testTextCodecs(CodecTest.java:157)

testTextCodecs[test-interval[]](com.impossibl.postgres.jdbc.CodecTest)  Time elapsed: 0.111 sec  <<< ERROR!
java.lang.IllegalArgumentException: invalid interval
    at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1250)
    at java.lang.Double.parseDouble(Double.java:540)
    at com.impossibl.postgres.api.data.Interval.setValue(Interval.java:168)
    at com.impossibl.postgres.api.data.Interval.<init>(Interval.java:76)
    at com.impossibl.postgres.system.procs.Intervals$TxtDecoder.decode(Intervals.java:135)
    at com.impossibl.postgres.system.procs.Intervals$TxtDecoder.decode(Intervals.java:120)
    at com.impossibl.postgres.system.procs.TextDecoder.decode(TextDecoder.java:54)
    at com.impossibl.postgres.system.procs.Arrays$TxtDecoder.readArray(Arrays.java:359)
    at com.impossibl.postgres.system.procs.Arrays$TxtDecoder.readArray(Arrays.java:425)
    at com.impossibl.postgres.system.procs.Arrays$TxtDecoder.decode(Arrays.java:350)
    at com.impossibl.postgres.system.procs.TextDecoder.decode(TextDecoder.java:51)
    at com.impossibl.postgres.jdbc.CodecTest.inOut(CodecTest.java:254)
    at com.impossibl.postgres.jdbc.CodecTest.testTextCodecs(CodecTest.java:157)

testTextCodecs[test-intervalstruct](com.impossibl.postgres.jdbc.CodecTest)  Time elapsed: 0.121 sec  <<< ERROR!
java.lang.IllegalArgumentException: invalid interval
    at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1250)
    at java.lang.Double.parseDouble(Double.java:540)
    at com.impossibl.postgres.api.data.Interval.setValue(Interval.java:168)
    at com.impossibl.postgres.api.data.Interval.<init>(Interval.java:76)
    at com.impossibl.postgres.system.procs.Intervals$TxtDecoder.decode(Intervals.java:135)
    at com.impossibl.postgres.system.procs.Intervals$TxtDecoder.decode(Intervals.java:120)
    at com.impossibl.postgres.system.procs.TextDecoder.decode(TextDecoder.java:54)
    at com.impossibl.postgres.system.procs.Records$TxtDecoder.readValue(Records.java:233)
    at com.impossibl.postgres.system.procs.Records$TxtDecoder.readComposite(Records.java:309)
    at com.impossibl.postgres.system.procs.Records$TxtDecoder.decode(Records.java:218)
    at com.impossibl.postgres.system.procs.Records$TxtDecoder.decode(Records.java:197)
    at com.impossibl.postgres.system.procs.TextDecoder.decode(TextDecoder.java:51)
    at com.impossibl.postgres.jdbc.CodecTest.inOut(CodecTest.java:254)
    at com.impossibl.postgres.jdbc.CodecTest.testTextCodecs(CodecTest.java:157)
```

IntervalTest

```
Tests run: 10, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.994 sec <<< FAILURE! - in com.impossibl.postgres.jdbc.IntervalTest
testIntervalToStringCoercion(com.impossibl.postgres.jdbc.IntervalTest)  Time elapsed: 0.092 sec  <<< FAILURE!
org.junit.ComparisonFailure: expected:<... 0 hours 0 minutes 0[.]000000 seconds> but was:<... 0 hours 0 minutes 0[,]000000 seconds>
    at org.junit.Assert.assertEquals(Assert.java:115)
    at org.junit.Assert.assertEquals(Assert.java:144)
    at com.impossibl.postgres.jdbc.IntervalTest.testIntervalToStringCoercion(IntervalTest.java:147)
```

As far as I understand the code, the problem is in com.impossibl.postgres.api.data.Interval class, which uses Double.parseDouble(string) and String.format(String, Object...) which are locale dependant.

My code does not use Interval columns, therefore I'm content with driver compiled using en_US locale, and I don't have spare time to try to fix it myself, but bug is a bug.

**Comment by kdubb** [comment]
Fixed in #265... Although an outstanding task is to add alternate locales to our CI testing
