### ISSUE TITLE
Could not initialize class com.impossibl.postgres.system.procs.Procs - pgjdbc-ng-0.4

### ISSUE THREAD

**Issue by vanecanhete** [impossibl/pgjdbc-ng#138]
# I configured the jdbc as a jboss module:

``` xml
<?xml version="1.0" encoding="UTF-8"?>  
<module xmlns="urn:jboss:module:1.0" name="com.impossibl.postgres.jdbc">  
    <resources>  
        <resource-root path="pgjdbc-ng-0.4.jar"/>  
    </resources>  
    <dependencies>  
        <module name="javax.api"/>
        <module name="javax.transaction.api"/>
        <module name="javax.xml.bind.api"/>
    </dependencies>  
</module>
```

As I did with the 0.3 version. 
The jboss load the module without problems...  
# But when I try to get a connection from my application I get the next error:

14:12:01,761 INFO  [py.com.personal.is.provisioning.postgres.rest.provisionamiento.ProvisionamientoController](http-/127.0.0.1:8080-1) Creando GeneralRequest
14:12:01,761 INFO  [py.com.personal.is.provisioning.postgres.rest.provisionamiento.ProvisionamientoController](http-/127.0.0.1:8080-1) Procesando request
14:12:01,762 INFO  [py.com.personal.is.messages.Stages](http-/127.0.0.1:8080-1) [INICIO DE OBTENCIÓN DE LA CONEXIÓN A LA BD]
14:12:01,762 INFO  [py.com.personal.is.middleware.postgres.controller.AbstractController](http-/127.0.0.1:8080-1) Obteniendo conexión a la base de datos. 
14:12:01,762 INFO  [py.com.personal.is.middleware.postgres.controller.AbstractController](http-/127.0.0.1:8080-1) Volviendo a cargar el datasource.
14:12:01,762 WARN  [org.jboss.jca.core.connectionmanager.pool.strategy.OnePool](http-/127.0.0.1:8080-1) IJ000604: Throwable while attempting to get a new connection: null: javax.resource.ResourceException: Could not create connection
    at org.jboss.jca.adapters.jdbc.local.LocalManagedConnectionFactory.getLocalManagedConnection(LocalManagedConnectionFactory.java:282) [ironjacamar-jdbc-1.0.17.Final-redhat-1.jar:1.0.17.Final-redhat-1]
    at org.jboss.jca.adapters.jdbc.local.LocalManagedConnectionFactory.createManagedConnection(LocalManagedConnectionFactory.java:240) [ironjacamar-jdbc-1.0.17.Final-redhat-1.jar:1.0.17.Final-redhat-1]
    at org.jboss.jca.core.connectionmanager.pool.mcp.SemaphoreArrayListManagedConnectionPool.createConnectionEventListener(SemaphoreArrayListManagedConnectionPool.java:781)
    at org.jboss.jca.core.connectionmanager.pool.mcp.SemaphoreArrayListManagedConnectionPool.getConnection(SemaphoreArrayListManagedConnectionPool.java:344)
    at org.jboss.jca.core.connectionmanager.pool.AbstractPool.getSimpleConnection(AbstractPool.java:397)
    at org.jboss.jca.core.connectionmanager.pool.AbstractPool.getConnection(AbstractPool.java:365)
    at org.jboss.jca.core.connectionmanager.AbstractConnectionManager.getManagedConnection(AbstractConnectionManager.java:329)
    at org.jboss.jca.core.connectionmanager.tx.TxConnectionManagerImpl.getManagedConnection(TxConnectionManagerImpl.java:368)
    at org.jboss.jca.core.connectionmanager.AbstractConnectionManager.allocateConnection(AbstractConnectionManager.java:464)
    at org.jboss.jca.adapters.jdbc.WrapperDataSource.getConnection(WrapperDataSource.java:139) [ironjacamar-jdbc-1.0.17.Final-redhat-1.jar:1.0.17.Final-redhat-1]
    at py.com.personal.is.middleware.postgres.controller.AbstractController.getConnection(AbstractController.java:86) [is-middleware-postgres-0.0.2-SNAPSHOT.jar:]
    at py.com.personal.is.middleware.postgres.controller.AbstractController.procesar(AbstractController.java:220) [is-middleware-postgres-0.0.2-SNAPSHOT.jar:]
    at py.com.personal.is.provisioning.postgres.rest.provisionamiento.ProvisionamientoController.ejecutarServicioPuntual(ProvisionamientoController.java:51) [classes:]
    at py.com.personal.is.provisioning.postgres.rest.provisionamiento.ProvisionamientoServices.provisionarLinea(ProvisionamientoServices.java:43) [classes:]
    at py.com.personal.is.provisioning.postgres.rest.provisionamiento.ProvisionamientoServices$Proxy$_$$_WeldClientProxy.provisionarLinea(ProvisionamientoServices$Proxy$_$$_WeldClientProxy.java) [classes:]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) [rt.jar:1.7.0_05]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) [rt.jar:1.7.0_05]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) [rt.jar:1.7.0_05]
    at java.lang.reflect.Method.invoke(Method.java:601) [rt.jar:1.7.0_05]
    at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:167) [resteasy-jaxrs-2.3.6.Final-redhat-1.jar:2.3.6.Final-redhat-1]
    at org.jboss.resteasy.core.ResourceMethod.invokeOnTarget(ResourceMethod.java:269) [resteasy-jaxrs-2.3.6.Final-redhat-1.jar:2.3.6.Final-redhat-1]
    at org.jboss.resteasy.core.ResourceMethod.invoke(ResourceMethod.java:227) [resteasy-jaxrs-2.3.6.Final-redhat-1.jar:2.3.6.Final-redhat-1]
    at org.jboss.resteasy.core.ResourceMethod.invoke(ResourceMethod.java:216) [resteasy-jaxrs-2.3.6.Final-redhat-1.jar:2.3.6.Final-redhat-1]
    at org.jboss.resteasy.core.SynchronousDispatcher.getResponse(SynchronousDispatcher.java:542) [resteasy-jaxrs-2.3.6.Final-redhat-1.jar:2.3.6.Final-redhat-1]
    at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:524) [resteasy-jaxrs-2.3.6.Final-redhat-1.jar:2.3.6.Final-redhat-1]
    at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:126) [resteasy-jaxrs-2.3.6.Final-redhat-1.jar:2.3.6.Final-redhat-1]
    at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:208) [resteasy-jaxrs-2.3.6.Final-redhat-1.jar:2.3.6.Final-redhat-1]
    at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:55) [resteasy-jaxrs-2.3.6.Final-redhat-1.jar:2.3.6.Final-redhat-1]
    at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:50) [resteasy-jaxrs-2.3.6.Final-redhat-1.jar:2.3.6.Final-redhat-1]
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:847) [jboss-servlet-api_3.0_spec-1.0.2.Final-redhat-1.jar:1.0.2.Final-redhat-1]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:295) [jbossweb-7.2.0.Final-redhat-1.jar:7.2.0.Final-redhat-1]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214) [jbossweb-7.2.0.Final-redhat-1.jar:7.2.0.Final-redhat-1]
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:230) [jbossweb-7.2.0.Final-redhat-1.jar:7.2.0.Final-redhat-1]
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:149) [jbossweb-7.2.0.Final-redhat-1.jar:7.2.0.Final-redhat-1]
    at org.jboss.as.web.security.SecurityContextAssociationValve.invoke(SecurityContextAssociationValve.java:169) [jboss-as-web-7.2.0.Final-redhat-8.jar:7.2.0.Final-redhat-8]
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:145) [jbossweb-7.2.0.Final-redhat-1.jar:7.2.0.Final-redhat-1]
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:97) [jbossweb-7.2.0.Final-redhat-1.jar:7.2.0.Final-redhat-1]
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:102) [jbossweb-7.2.0.Final-redhat-1.jar:7.2.0.Final-redhat-1]
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:336) [jbossweb-7.2.0.Final-redhat-1.jar:7.2.0.Final-redhat-1]
    at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:856) [jbossweb-7.2.0.Final-redhat-1.jar:7.2.0.Final-redhat-1]
    at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:653) [jbossweb-7.2.0.Final-redhat-1.jar:7.2.0.Final-redhat-1]
    at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:920) [jbossweb-7.2.0.Final-redhat-1.jar:7.2.0.Final-redhat-1]
    at java.lang.Thread.run(Thread.java:722) [rt.jar:1.7.0_05]
Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.impossibl.postgres.system.procs.Procs
    at com.impossibl.postgres.types.BaseType.<init>(BaseType.java:53) [pgjdbc-ng-0.4.jar:]
    at com.impossibl.postgres.types.Registry.<init>(Registry.java:94) [pgjdbc-ng-0.4.jar:]
    at com.impossibl.postgres.system.BasicContext.<init>(BasicContext.java:129) [pgjdbc-ng-0.4.jar:]
    at com.impossibl.postgres.jdbc.PGConnectionImpl.<init>(PGConnectionImpl.java:181) [pgjdbc-ng-0.4.jar:]
    at com.impossibl.postgres.jdbc.ConnectionUtil.createConnection(ConnectionUtil.java:168) [pgjdbc-ng-0.4.jar:]
    at com.impossibl.postgres.jdbc.PGDriver.connect(PGDriver.java:60) [pgjdbc-ng-0.4.jar:]
    at com.impossibl.postgres.jdbc.PGDriver.connect(PGDriver.java:50) [pgjdbc-ng-0.4.jar:]
    at org.jboss.jca.adapters.jdbc.local.LocalManagedConnectionFactory.getLocalManagedConnection(LocalManagedConnectionFactory.java:254) [ironjacamar-jdbc-1.0.17.Final-redhat-1.jar:1.0.17.Final-redhat-1]
    ... 42 more

If somebody could help me I will be close to answer any questions..

**Comment by jesperpedersen** [comment]
I'll take a look at this - thanks for the report

**Comment by jesperpedersen** [comment]
Try https://github.com/impossibl/pgjdbc-ng/commit/7dad1111f7f5e2734ac4277c384824fc0cf9e1fe - latest develop

**Comment by vanecanhete** [comment]
I still having the problem using that commit @jesperpedersen. Any other idea? :(
Caused by: javax.resource.ResourceException: Could not create connection
    at org.jboss.jca.adapters.jdbc.local.LocalManagedConnectionFactory.getLocalManagedConnection(LocalManagedConnectionFactory.java:282) [ironjacamar-jdbc-1.0.17.Final-redhat-1.jar:1.0.17.Final-redhat-1]
    at org.jboss.jca.adapters.jdbc.local.LocalManagedConnectionFactory.createManagedConnection(LocalManagedConnectionFactory.java:240) [ironjacamar-jdbc-1.0.17.Final-redhat-1.jar:1.0.17.Final-redhat-1]
    at org.jboss.jca.core.connectionmanager.pool.mcp.SemaphoreArrayListManagedConnectionPool.createConnectionEventListener(SemaphoreArrayListManagedConnectionPool.java:781)
    at org.jboss.jca.core.connectionmanager.pool.mcp.SemaphoreArrayListManagedConnectionPool.getConnection(SemaphoreArrayListManagedConnectionPool.java:344)
    ... 41 more
Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.impossibl.postgres.system.procs.Procs
    at com.impossibl.postgres.types.Registry.<init>(Registry.java:80) [pgjdbc-ng-0.5-SNAPSHOT.jar:]
    at com.impossibl.postgres.system.BasicContext.<init>(BasicContext.java:129) [pgjdbc-ng-0.5-SNAPSHOT.jar:]
    at com.impossibl.postgres.jdbc.PGConnectionImpl.<init>(PGConnectionImpl.java:184) [pgjdbc-ng-0.5-SNAPSHOT.jar:]
    at com.impossibl.postgres.jdbc.ConnectionUtil.createConnection(ConnectionUtil.java:172) [pgjdbc-ng-0.5-SNAPSHOT.jar:]
    at com.impossibl.postgres.jdbc.PGDriver.connect(PGDriver.java:77) [pgjdbc-ng-0.5-SNAPSHOT.jar:]
    at com.impossibl.postgres.jdbc.PGDriver.connect(PGDriver.java:52) [pgjdbc-ng-0.5-SNAPSHOT.jar:]
    at org.jboss.jca.adapters.jdbc.local.LocalManagedConnectionFactory.getLocalManagedConnection(LocalManagedConnectionFactory.java:254) [ironjacamar-jdbc-1.0.17.Final-redhat-1.jar:1.0.17.Final-redhat-1]
    ... 44 more

**Comment by jesperpedersen** [comment]
@vanecan Try with a newer version of EAP, or WildFly. EAP 6.1.0 is quite old

**Comment by jesperpedersen** [comment]
Sample configuration for WildFly has been added here: https://github.com/impossibl/pgjdbc-ng/wiki/WildFly
