### ISSUE TITLE
Hang when loading attributes in BasicContext 

### ISSUE THREAD

**Issue by erikburgess** [impossibl/pgjdbc-ng#175]
Creating a connection is hanging when loading the attributes in BasicContext. The request is not timing out even though the network timeout is set on the PGDataSource. Running in a debugger and setting the network timeout in the CommandImpl causes the below exception when a timeout occurrs.

```
org.skife.jdbi.v2.exceptions.UnableToObtainConnectionException: java.sql.SQLException: Connection Error: network timeout reached
at org.skife.jdbi.v2.DBI.open(DBI.java:224)
at org.skife.jdbi.v2.sqlobject.SqlObjectBuilder.open(SqlObjectBuilder.java:52)
at org.skife.jdbi.v2.DBI.open(DBI.java:325)
at com.example.test.web.repository.AccountRespoitoryImpl.nextId(AccountRespoitoryImpl.java:32)
at com.example.test.service.AccountService.createAccount(AccountService.java:35)
at com.example.test.web.resources.AccountResource.createAccount(AccountResource.java:43)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:151)
at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:171)
at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:152)
at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:104)
at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:387)
at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:331)
at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:103)
at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:271)
at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:297)
at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:254)
at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1028)
at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:372)
at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:381)
at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:344)
at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:221)
at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:800)
at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:587)
at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:215)
at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:110)
at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
at org.eclipse.jetty.server.Server.handle(Server.java:497)
at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:245)
at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
at java.lang.Thread.run(Thread.java:745)
Caused by: 
java.sql.SQLException: Connection Error: network timeout reached
at com.impossibl.postgres.jdbc.ConnectionUtil.createConnection(ConnectionUtil.java:189)
at   com.impossibl.postgres.jdbc.AbstractDataSource.createConnection(AbstractDataSource.java:465)
at com.impossibl.postgres.jdbc.PGDataSource.getConnection(PGDataSource.java:66)
at com.impossibl.postgres.jdbc.PGDataSource.getConnection(PGDataSource.java:58)
at org.skife.jdbi.v2.DataSourceConnectionFactory.openConnection(DataSourceConnectionFactory.java:35)
at org.skife.jdbi.v2.DBI.open(DBI.java:206)
at org.skife.jdbi.v2.sqlobject.SqlObjectBuilder.open(SqlObjectBuilder.java:52)
at org.skife.jdbi.v2.DBI.open(DBI.java:325)
at com.example.test.web.repository.AccountRespoitoryImpl.nextId(AccountRespoitoryImpl.java:32)
at com.example.test.service.AccountService.createAccount(AccountService.java:35)
at com.example.test.web.resources.AccountResource.createAccount(AccountResource.java:43)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:151)
at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:171)
at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:152)
at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:104)
at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:387)
at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:331)
at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:103)
at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:271)
at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:297)
at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:254)
at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1028)
at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:372)
at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:381)
at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:344)
at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:221)
at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:800)
at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:587)
at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:215)
at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:110)
at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
at org.eclipse.jetty.server.Server.handle(Server.java:497)
at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:245)
at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
at java.lang.Thread.run(Thread.java:745)
Caused by: 
com.impossibl.postgres.utils.BlockingReadTimeoutException: network timeout reached
at com.impossibl.postgres.protocol.v30.CommandImpl.waitFor(CommandImpl.java:129)
at com.impossibl.postgres.protocol.v30.BindExecCommandImpl.execute(BindExecCommandImpl.java:346)
at com.impossibl.postgres.protocol.v30.ProtocolImpl.execute(ProtocolImpl.java:370)
at com.impossibl.postgres.system.BasicContext.preparedQuery(BasicContext.java:560)
at com.impossibl.postgres.system.BasicContext.queryBatch(BasicContext.java:552)
at com.impossibl.postgres.system.BasicContext.queryResults(BasicContext.java:424)
at com.impossibl.postgres.system.BasicContext.loadTypes(BasicContext.java:259)
at com.impossibl.postgres.system.BasicContext.init(BasicContext.java:244)
at com.impossibl.postgres.jdbc.PGConnectionImpl.init(PGConnectionImpl.java:237)
at com.impossibl.postgres.jdbc.ConnectionUtil.createConnection(ConnectionUtil.java:182)
at com.impossibl.postgres.jdbc.AbstractDataSource.createConnection(AbstractDataSource.java:465)
at com.impossibl.postgres.jdbc.PGDataSource.getConnection(PGDataSource.java:66)
at com.impossibl.postgres.jdbc.PGDataSource.getConnection(PGDataSource.java:58)
at org.skife.jdbi.v2.DataSourceConnectionFactory.openConnection(DataSourceConnectionFactory.java:35)
at org.skife.jdbi.v2.DBI.open(DBI.java:206)
at org.skife.jdbi.v2.sqlobject.SqlObjectBuilder.open(SqlObjectBuilder.java:52)
at org.skife.jdbi.v2.DBI.open(DBI.java:325)
at com.example.test.web.repository.AccountRespoitoryImpl.nextId(AccountRespoitoryImpl.java:32)
at com.example.test.service.AccountService.createAccount(AccountService.java:35)
at com.example.test.web.resources.AccountResource.createAccount(AccountResource.java:43)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:151)
at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:171)
at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:152)
at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:104)
at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:387)
at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:331)
at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:103)
at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:271)
at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:297)
at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:254)
at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1028)
at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:372)
at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:381)
at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:344)
at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:221)
at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:800)
at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:587)
at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:215)
at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:110)
at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
at org.eclipse.jetty.server.Server.handle(Server.java:497)
at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:245)
at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
at java.lang.Thread.run(Thread.java:745) 
```

**Comment by jesperpedersen** [comment]
pgjdbc-ng version ?
PostgreSQL version ?
Access with psql works ?

**Comment by erikburgess** [comment]
Forgot to include that

pgjdbc-ng version is 0.5
PostgreSQL version 9.4.2
Yes access with psql works.

Also seeing the same issue in pgjdbc-ng 0.3 I updated the version while debugging.

**Comment by jesperpedersen** [comment]
-complete.jar or linked Netty (and version if so) ?
And connection configuration...

**Comment by kdubb** [comment]
I would venture to guess that the JVM is configured to use a different network interface than what psql is using.   It's quite clearly saying "network timeout" and, well, we know the driver connects extremely reliably; as I've never seen or heard of an issue "connecting".

**Comment by erikburgess** [comment]
I am going to say the complete jar it is downloaded form maven.org

The connection configuration is
    this.dataSource = new PGDataSource();
    this.dataSource.setHost("localhost");
    this.dataSource.setPort(5432);
    this.dataSource.setDatabase("dev");
    this.dataSource.setUser("test");
    this.dataSource.setPassword("test");

Also I was not having any issues yesterday the only thing that has changed is updating OSX.

**Comment by kdubb** [comment]
@erikburgess This has to be a network configuration issue.  OS X (which I use as well) likes to fire up all kinds of IPv6 interfaces.  If you updated to 10.11 beta I know they are driving IPv6 hard.

I happen to be at WWDC at this moment lol

**Comment by erikburgess** [comment]
@kdubb Yes changing the host to the loopback address fixes the connection issue.

Although there still seems to be a problem with the timeout since the connection hangs when the issue is seen and only times out if I set the network timeout from the debugger.

**Comment by kdubb** [comment]
@erikburgess I would venture to guess PG is listening on 127.0.0.1 (e.g. IPv4) only.  OS X is starting to default to IPv6 so your localhost is mapping to whatever that loopback address is.  You could also change PG/s config to listen on both IPv6 & IPv4 and see if that also fixes the problem.

As for the the "hang", default timeouts are like 90 or 120 seconds (who knows why).  So you may just not be waiting long enough.  Since you said it throws properly when you reduce the timeout to a reasonable value then I'd say it's probably working correctly.

**Comment by erikburgess** [comment]
@kdubb The debugger is showing the network timeout set to 9223372036854775807

**Comment by jesperpedersen** [comment]
@erikburgess The timeout is set here - https://github.com/impossibl/pgjdbc-ng/blob/develop/src/main/java/com/impossibl/postgres/jdbc/PGConnectionImpl.java#L187 so you will have to debug from there

**Comment by kdubb** [comment]
Our default is 0.  The goal of that was to kick in the system default.  Somehow your timeout is getting set to forever.  Would be nice to know how that's happening.

**Comment by kdubb** [comment]
Closing since this behavior hasn't been exhibited anywhere else.  Feel free to reopen with more information.

**Comment by kdubb** [comment]
@erikburgess The current head revision has changes I believe would probably solve this issue you were having. Specific PR #272.  The key here is type loading/refreshing during result parsing.  If you can it would be great to have you verify this fix.

**Comment by erikburgess** [comment]
@kdubb 

I am not seeing the issue with the same pgjbdc version on OS X El Capitan. Additionally the issue was seen when the datasource host was set to localhost when it was explicitly set it to  the ipv4 loopback there was no issue. Also if I recall correctly there was an OS X update after which the issue was not reproducible. 

`this.dataSource.setHost("localhost");`

`this.dataSource.setHost("127.0.0.1")`

**Comment by butlnor** [comment]
Can this BasicContext.loadTypes be configured somehow, so that it's skipped? 

We have many problems with it, as we have a large DB with ten thousands of tables, and it takes a lot of time, and half of the times it even hangs, so that there is a network timeout. And most of the heap is filled by this metadata.

As I read, this DB metadata is loaded in advance, because then some binary mode can be used. But, we don't need binary mode, we use text SQLs that should be directly executed on the DB server.

If I modify the PGJDBC-NG sources for local use, with commenting out loading the metadata, what problems can I expect?

**Comment by kdubb** [comment]
@butlnor
pgjdbc-ng version ?
PostgreSQL version ?
Access with psql works ?

The latest version of the driver loads an extremely small set of information and any "timeout" would be very puzzling as loading a large number of rows isn't really a known problem.

**Comment by butlnor** [comment]
> 
> 
> @butlnor
> pgjdbc-ng version ?
> PostgreSQL version ?
> Access with psql works ?
> 
> The latest version of the driver loads an extremely small set of information and any "timeout" would be very puzzling as loading a large number of rows isn't really a known problem.

pgjdbc-ng is 0.7.1. It's a production service, it's not that easy to upgrade it, as it's not compatible (for example, method setDatabase was changed in 0.8.6).
PG version 9.3.1. 
Didn't try psql, but when using dBeaver, there are never any problems.

**Comment by kdubb** [comment]
Well switching to the latest version will likely solve your specific issue(s). I would highly recommend moving off of the 0.7 series driver.

**Comment by butlnor** [comment]
But still, the question is: if I am using solely textual SQL statements, do I need this catalog/metadata (however it's called)? Could I comment out the loading of the types completely? What could be the problems for me?

**Comment by kdubb** [comment]
The 0.8 series driver already does essentially this. It only loads a small set of types and, if necessary, it loads other types on demand.
