### ISSUE TITLE
sql parsing error

### ISSUE THREAD

**Issue by colinlieberman** [impossibl/pgjdbc-ng#183]
Hi there. With the 0.5 version of the driver, I get the following error using liquibase:

$ liquibase --url=jdbc:pgsql://localhost/mydb --changeLogFile=Changelog.xml --driver=com.impossibl.postgres.jdbc.PGDriver update
SEVERE 6/22/15 1:16 PM: liquibase: Changelog.xml: {redacted}: Change Set {redacted} failed.  Error: java.sql.SQLException: Error parsing SQL at position 896 

[... lqb stack trace ... ]
    at com.impossibl.postgres.jdbc.PGConnectionImpl.parseSQL(PGConnectionImpl.java:409)
    at com.impossibl.postgres.jdbc.PGSimpleStatement.execute(PGSimpleStatement.java:122)

here's a pastebin of the redacted SQL file: http://pastebin.com/XXy1vUEP; according vim, before the redaction, character 896 is the end of line 25 

here's the full lqb stack trace if it's helpful:

liquibase.exception.DatabaseException: java.sql.SQLException: Error parsing SQL at position 896 ( ... sql ...)
    at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:316)
    at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:55)
    at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:122)
    at liquibase.database.AbstractJdbcDatabase.execute(AbstractJdbcDatabase.java:1227)
    at liquibase.database.AbstractJdbcDatabase.executeStatements(AbstractJdbcDatabase.java:1210)
    at liquibase.changelog.ChangeSet.execute(ChangeSet.java:550)
    at liquibase.changelog.visitor.UpdateVisitor.visit(UpdateVisitor.java:43)
    at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:73)
    at liquibase.Liquibase.update(Liquibase.java:200)
    at liquibase.integration.commandline.Main.doMigration(Main.java:1044)
    at liquibase.integration.commandline.Main.run(Main.java:175)
    at liquibase.integration.commandline.Main.main(Main.java:94)
Caused by: java.sql.SQLException: Error parsing SQL at position 896 ( ... sql ...)
    at com.impossibl.postgres.jdbc.PGConnectionImpl.parseSQL(PGConnectionImpl.java:409)
    at com.impossibl.postgres.jdbc.PGSimpleStatement.execute(PGSimpleStatement.java:122)
    at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:314)
    ... 11 more

**Comment by jesperpedersen** [comment]
Is the pastebin the entire query sent ? I don't see 'sql' anywhere in it at least...

See if you can expand the SQLTextTests file with the expression that is failing, if it is passing with psql

**Comment by colinlieberman** [comment]
Sorry for any confusion. Where I put " ( ... sql ...)" in the stack trace, that was a contraction of the full stack trace to separate the SQL in the lqb migration file from the trace itself. I was trying to make it easier to read.

Expanded the whole shebang looks like this, where the only change is the redaction of employer-specific stuff:

```
liquibase.exception.DatabaseException: java.sql.SQLException: Error parsing SQL at position 896 (--
-- PostgreSQL database dump
--

SET statement_timeout = 0;

SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET client_min_messages = warning;

SET search_path = "public", pg_catalog;

--
-- Data for Name: redacted; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO "redacted" ("id", "name") VALUES (1, 'redacted');
INSERT INTO "redacted" ("id", "name") VALUES (2, 'redacted');
INSERT INTO "redacted" ("id", "name") VALUES (3, 'redacted');
INSERT INTO "redacted" ("id", "name") VALUES (4, 'redacted');


--
-- Name: redacted; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('"redacted"', 4, true);


--
-- PostgreSQL database dump complete
--)
at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:316)
at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:55)
at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:122)
at liquibase.database.AbstractJdbcDatabase.execute(AbstractJdbcDatabase.java:1227)
at liquibase.database.AbstractJdbcDatabase.executeStatements(AbstractJdbcDatabase.java:1210)
at liquibase.changelog.ChangeSet.execute(ChangeSet.java:550)
at liquibase.changelog.visitor.UpdateVisitor.visit(UpdateVisitor.java:43)
at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:73)
at liquibase.Liquibase.update(Liquibase.java:200)
at liquibase.integration.commandline.Main.doMigration(Main.java:1044)
at liquibase.integration.commandline.Main.run(Main.java:175)
at liquibase.integration.commandline.Main.main(Main.java:94)
Caused by: java.sql.SQLException: Error parsing SQL at position 896 (--
-- PostgreSQL database dump
--

SET statement_timeout = 0;

SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET client_min_messages = warning;

SET search_path = "public", pg_catalog;

--
-- Data for Name: redacted; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO "redacted" ("id", "name") VALUES (1, 'redacted');
INSERT INTO "redacted" ("id", "name") VALUES (2, 'redacted');
INSERT INTO "redacted" ("id", "name") VALUES (3, 'redacted');
INSERT INTO "redacted" ("id", "name") VALUES (4, 'redacted');


--
-- Name: redacted; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('"redacted"', 4, true);


--
-- PostgreSQL database dump complete
--)
at com.impossibl.postgres.jdbc.PGConnectionImpl.parseSQL(PGConnectionImpl.java:409)
at com.impossibl.postgres.jdbc.PGSimpleStatement.execute(PGSimpleStatement.java:122)
at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:314)
... 11 more
```

**Comment by jesperpedersen** [comment]
Should be fixed now. Thanks for the report
