### ISSUE TITLE
IndexOutOfBoundException is thrown when retrieving column names

### ISSUE THREAD

**Issue by jdebouil** [impossibl/pgjdbc-ng#185]
Using version 0.5, following exception is thrown :
java.lang.IndexOutOfBoundsException: Index: 45, Size: 45
    at java.util.ArrayList.rangeCheck(ArrayList.java:635) ~[na:1.7.0_51]
    at java.util.ArrayList.get(ArrayList.java:411) ~[na:1.7.0_51]
    at com.impossibl.postgres.types.CompositeType.getAttribute(CompositeType.java:87) ~[pgjdbc-ng-0.5.jar:na]
    at com.impossibl.postgres.jdbc.PGResultSetMetaData.getRelAttr(PGResultSetMetaData.java:104) ~[pgjdbc-ng-0.5.jar:na]
    at com.impossibl.postgres.jdbc.PGResultSetMetaData.getColumnName(PGResultSetMetaData.java:211) ~[pgjdbc-ng-0.5.jar:na]
    at com.digitech.common.dal.sgbd.JdbcUtils.computeColumnNames(JdbcUtils.java:889) ~[common-dal-3.3.0-SNAPSHOT.jar:na]
    at com.digitech.common.dal.sgbd.JdbcUtils.getColumnNames(JdbcUtils.java:624) ~[common-dal-3.3.0-SNAPSHOT.jar:na]

**Comment by jesperpedersen** [comment]
Do you have the SQL that triggered this ? And the Java code ? Does the query work using `psql` ?

The exception should of course be a SQLException instead at least...

**Comment by jdebouil** [comment]
The exception is thrown when retrieving column names from metadata. No sql request is used.

**Comment by jesperpedersen** [comment]
Yeah, I know. But, there were a SQL statement executed in order to get a ResultSet.

I have added a size violation check to `develop`, so go from there

**Comment by jdebouil** [comment]
The SQL statement is : 
select \* from  _tableName_ where 1=0

**Comment by kdubb** [comment]
Given the limited details, and that this cannot be reproduced with the current head revision, closing.  If you can reproduce still reproduce it please re-open and add more details.

FYI... It's also covered in the unit test `ResultSetMetaDataTest`.
