### ISSUE TITLE
Netty 4.0.29 regression

### ISSUE THREAD

**Issue by jesperpedersen** [impossibl/pgjdbc-ng#187]
Placeholder until I can figure out what is going on with these regressions going from Netty 4.0.28.

Entire test suite is failing with

```
Tests run: 42, Failures: 0, Errors: 42, Skipped: 0, Time elapsed: 0.159 sec <<< FAILURE! - in com.impossibl.postgres.jdbc.ArrayTest
testRetrieveResultSets(com.impossibl.postgres.jdbc.ArrayTest)  Time elapsed: 0.008 sec  <<< ERROR!
com.impossibl.postgres.jdbc.PGSQLSimpleException: Connection Error: invalid frontend message type 0
        at com.impossibl.postgres.jdbc.ErrorUtils.makeSQLException(ErrorUtils.java:159)
        at com.impossibl.postgres.jdbc.ConnectionUtil.createConnection(ConnectionUtil.java:193)
        at com.impossibl.postgres.jdbc.PGDriver.connect(PGDriver.java:77)
        at com.impossibl.postgres.jdbc.PGDriver.connect(PGDriver.java:52)
        at java.sql.DriverManager.getConnection(DriverManager.java:571)
        at java.sql.DriverManager.getConnection(DriverManager.java:187)
        at com.impossibl.postgres.jdbc.TestUtil.openDB(TestUtil.java:128)
        at com.impossibl.postgres.jdbc.TestUtil.openDB(TestUtil.java:116)
        at com.impossibl.postgres.jdbc.ArrayTest.before(ArrayTest.java:67)
```

Then report to upstream #netty (@trustin and @normanmaurer)

We need Netty 4.0.29+ due to https://github.com/netty/netty/commit/74c0f4ce1482cacc52e2a804db5358bab01e92cd

**Comment by brcolow** [comment]
Any update on this? I am in the precarious situation of needing the fix in Netty. I tried added the 4.0.30.Final dependency to my pom before I declare the dependency on pgjdbc-ng, but to no avail.

**Comment by jesperpedersen** [comment]
@brcolow I havn't had time to look at it yet - yes, 4.0.30.Final is effected too.

We would need java.util.logging.Level.ALL messages for ConnectionTest#testDoubleClose (should be enough) for a run with 4.0.28.Final and then a run with 4.0.29.Final to compare.

If you have time feel free to work on it :)

**Comment by jesperpedersen** [comment]
A dump from PrepareCommandImpl using 4.0.31.Final, which also has the regression:

```
Running com.impossibl.postgres.jdbc.ConnectionTest
         +-------------------------------------------------+
         |  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f |
+--------+-------------------------------------------------+----------------+
|00000000| 00 00 03 1e ff 00 20 73 65 6c 65 63 74 20 20 20 |...... select   |
|00000010| 74 2e 6f 69 64 2c 20 74 79 70 6e 61 6d 65 20 61 |t.oid, typname a|
|00000020| 73 20 22 6e 61 6d 65 22 2c 20 74 79 70 6c 65 6e |s "name", typlen|
|00000030| 20 61 73 20 22 6c 65 6e 67 74 68 22 2c 20 74 79 | as "length", ty|
|00000040| 70 74 79 70 65 20 61 73 20 22 64 69 73 63 72 69 |ptype as "discri|
|00000050| 6d 69 6e 61 74 6f 72 22 2c 20 74 79 70 63 61 74 |minator", typcat|
|00000060| 65 67 6f 72 79 20 61 73 20 22 63 61 74 65 67 6f |egory as "catego|
|00000070| 72 79 22 2c 20 74 79 70 64 65 6c 69 6d 20 61 73 |ry", typdelim as|
|00000080| 20 22 64 65 6c 69 6d 69 6e 61 74 6f 72 22 2c 20 | "deliminator", |
|00000090| 74 79 70 72 65 6c 69 64 20 61 73 20 22 72 65 6c |typrelid as "rel|
|000000a0| 61 74 69 6f 6e 49 64 22 2c 20 20 20 74 79 70 65 |ationId",   type|
|000000b0| 6c 65 6d 20 61 73 20 22 65 6c 65 6d 65 6e 74 54 |lem as "elementT|
|000000c0| 79 70 65 49 64 22 2c 20 74 79 70 61 72 72 61 79 |ypeId", typarray|
|000000d0| 20 61 73 20 22 61 72 72 61 79 54 79 70 65 49 64 | as "arrayTypeId|
|000000e0| 22 2c 20 74 79 70 69 6e 70 75 74 3a 3a 6f 69 64 |", typinput::oid|
|000000f0| 20 61 73 20 22 69 6e 70 75 74 49 64 22 2c 20 74 | as "inputId", t|
|00000100| 79 70 6f 75 74 70 75 74 3a 3a 6f 69 64 20 61 73 |ypoutput::oid as|
|00000110| 20 22 6f 75 74 70 75 74 49 64 22 2c 20 74 79 70 | "outputId", typ|
|00000120| 72 65 63 65 69 76 65 3a 3a 6f 69 64 20 61 73 20 |receive::oid as |
|00000130| 22 72 65 63 65 69 76 65 49 64 22 2c 20 74 79 70 |"receiveId", typ|
|00000140| 73 65 6e 64 3a 3a 6f 69 64 20 61 73 20 22 73 65 |send::oid as "se|
|00000150| 6e 64 49 64 22 2c 20 20 20 74 79 70 6d 6f 64 69 |ndId",   typmodi|
|00000160| 6e 3a 3a 6f 69 64 20 61 73 20 22 6d 6f 64 49 6e |n::oid as "modIn|
|00000170| 49 64 22 2c 20 74 79 70 6d 6f 64 6f 75 74 3a 3a |Id", typmodout::|
|00000180| 6f 69 64 20 61 73 20 22 6d 6f 64 4f 75 74 49 64 |oid as "modOutId|
|00000190| 22 2c 20 74 79 70 61 6c 69 67 6e 20 61 73 20 61 |", typalign as a|
|000001a0| 6c 69 67 6e 6d 65 6e 74 2c 20 6e 2e 6e 73 70 6e |lignment, n.nspn|
|000001b0| 61 6d 65 20 61 73 20 22 6e 61 6d 65 73 70 61 63 |ame as "namespac|
|000001c0| 65 22 2c 20 20 20 20 74 79 70 62 61 73 65 74 79 |e",    typbasety|
|000001d0| 70 65 20 61 73 20 22 64 6f 6d 61 69 6e 42 61 73 |pe as "domainBas|
|000001e0| 65 54 79 70 65 49 64 22 2c 20 74 79 70 74 79 70 |eTypeId", typtyp|
|000001f0| 6d 6f 64 20 61 73 20 22 64 6f 6d 61 69 6e 54 79 |mod as "domainTy|
|00000200| 70 65 4d 6f 64 22 2c 20 74 79 70 6e 6f 74 6e 75 |peMod", typnotnu|
|00000210| 6c 6c 20 61 73 20 22 64 6f 6d 61 69 6e 4e 6f 74 |ll as "domainNot|
|00000220| 4e 75 6c 6c 22 2c 20 70 67 5f 63 61 74 61 6c 6f |Null", pg_catalo|
|00000230| 67 2e 70 67 5f 67 65 74 5f 65 78 70 72 28 74 79 |g.pg_get_expr(ty|
|00000240| 70 64 65 66 61 75 6c 74 62 69 6e 2c 30 29 20 61 |pdefaultbin,0) a|
|00000250| 73 20 22 64 6f 6d 61 69 6e 44 65 66 61 75 6c 74 |s "domainDefault|
|00000260| 22 2c 20 20 20 20 72 6e 67 73 75 62 74 79 70 65 |",    rngsubtype|
|00000270| 20 61 73 20 22 72 61 6e 67 65 42 61 73 65 54 79 | as "rangeBaseTy|
|00000280| 70 65 49 64 22 20 20 66 72 6f 6d 20 20 20 70 67 |peId"  from   pg|
|00000290| 5f 63 61 74 61 6c 6f 67 2e 70 67 5f 74 79 70 65 |_catalog.pg_type|
|000002a0| 20 74 20 6c 65 66 74 20 6a 6f 69 6e 20 70 67 5f | t left join pg_|
|000002b0| 63 61 74 61 6c 6f 67 2e 70 67 5f 6e 61 6d 65 73 |catalog.pg_names|
|000002c0| 70 61 63 65 20 6e 20 6f 6e 20 28 74 2e 74 79 70 |pace n on (t.typ|
|000002d0| 6e 61 6d 65 73 70 61 63 65 20 3d 20 6e 2e 6f 69 |namespace = n.oi|
|000002e0| 64 29 20 20 6c 65 66 74 20 6a 6f 69 6e 20 70 67 |d)  left join pg|
|000002f0| 5f 63 61 74 61 6c 6f 67 2e 70 67 5f 72 61 6e 67 |_catalog.pg_rang|
|00000300| 65 20 72 20 6f 6e 20 28 74 2e 6f 69 64 20 3d 20 |e r on (t.oid = |
|00000310| 72 2e 72 6e 67 74 79 70 69 64 29 00 00 00 44 00 |r.rngtypid)...D.|
|00000320| 00 00 06 53 00 53 00 00 00 04                   |...S.S....      |
+--------+-------------------------------------------------+----------------+
Error: Notice(FATAL, 08P01, invalid frontend message type 0)
```

@normanmaurer Any hints to further debug this would be great -- the dump is from here:  https://github.com/impossibl/pgjdbc-ng/blob/develop/src/main/java/com/impossibl/postgres/protocol/v30/PrepareCommandImpl.java#L156

**Comment by jesperpedersen** [comment]
A hacked 4.0.28 gives

```
         +-------------------------------------------------+
         |  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f |
+--------+-------------------------------------------------+----------------+
|00000000| 50 00 00 03 1d 00 20 73 65 6c 65 63 74 20 20 20 |P..... select   |
|00000010| 74 2e 6f 69 64 2c 20 74 79 70 6e 61 6d 65 20 61 |t.oid, typname a|
|00000020| 73 20 22 6e 61 6d 65 22 2c 20 74 79 70 6c 65 6e |s "name", typlen|
|00000030| 20 61 73 20 22 6c 65 6e 67 74 68 22 2c 20 74 79 | as "length", ty|
|00000040| 70 74 79 70 65 20 61 73 20 22 64 69 73 63 72 69 |ptype as "discri|
|00000050| 6d 69 6e 61 74 6f 72 22 2c 20 74 79 70 63 61 74 |minator", typcat|
|00000060| 65 67 6f 72 79 20 61 73 20 22 63 61 74 65 67 6f |egory as "catego|
|00000070| 72 79 22 2c 20 74 79 70 64 65 6c 69 6d 20 61 73 |ry", typdelim as|
|00000080| 20 22 64 65 6c 69 6d 69 6e 61 74 6f 72 22 2c 20 | "deliminator", |
|00000090| 74 79 70 72 65 6c 69 64 20 61 73 20 22 72 65 6c |typrelid as "rel|
|000000a0| 61 74 69 6f 6e 49 64 22 2c 20 20 20 74 79 70 65 |ationId",   type|
|000000b0| 6c 65 6d 20 61 73 20 22 65 6c 65 6d 65 6e 74 54 |lem as "elementT|
|000000c0| 79 70 65 49 64 22 2c 20 74 79 70 61 72 72 61 79 |ypeId", typarray|
|000000d0| 20 61 73 20 22 61 72 72 61 79 54 79 70 65 49 64 | as "arrayTypeId|
|000000e0| 22 2c 20 74 79 70 69 6e 70 75 74 3a 3a 6f 69 64 |", typinput::oid|
|000000f0| 20 61 73 20 22 69 6e 70 75 74 49 64 22 2c 20 74 | as "inputId", t|
|00000100| 79 70 6f 75 74 70 75 74 3a 3a 6f 69 64 20 61 73 |ypoutput::oid as|
|00000110| 20 22 6f 75 74 70 75 74 49 64 22 2c 20 74 79 70 | "outputId", typ|
|00000120| 72 65 63 65 69 76 65 3a 3a 6f 69 64 20 61 73 20 |receive::oid as |
|00000130| 22 72 65 63 65 69 76 65 49 64 22 2c 20 74 79 70 |"receiveId", typ|
|00000140| 73 65 6e 64 3a 3a 6f 69 64 20 61 73 20 22 73 65 |send::oid as "se|
|00000150| 6e 64 49 64 22 2c 20 20 20 74 79 70 6d 6f 64 69 |ndId",   typmodi|
|00000160| 6e 3a 3a 6f 69 64 20 61 73 20 22 6d 6f 64 49 6e |n::oid as "modIn|
|00000170| 49 64 22 2c 20 74 79 70 6d 6f 64 6f 75 74 3a 3a |Id", typmodout::|
|00000180| 6f 69 64 20 61 73 20 22 6d 6f 64 4f 75 74 49 64 |oid as "modOutId|
|00000190| 22 2c 20 74 79 70 61 6c 69 67 6e 20 61 73 20 61 |", typalign as a|
|000001a0| 6c 69 67 6e 6d 65 6e 74 2c 20 6e 2e 6e 73 70 6e |lignment, n.nspn|
|000001b0| 61 6d 65 20 61 73 20 22 6e 61 6d 65 73 70 61 63 |ame as "namespac|
|000001c0| 65 22 2c 20 20 20 20 74 79 70 62 61 73 65 74 79 |e",    typbasety|
|000001d0| 70 65 20 61 73 20 22 64 6f 6d 61 69 6e 42 61 73 |pe as "domainBas|
|000001e0| 65 54 79 70 65 49 64 22 2c 20 74 79 70 74 79 70 |eTypeId", typtyp|
|000001f0| 6d 6f 64 20 61 73 20 22 64 6f 6d 61 69 6e 54 79 |mod as "domainTy|
|00000200| 70 65 4d 6f 64 22 2c 20 74 79 70 6e 6f 74 6e 75 |peMod", typnotnu|
|00000210| 6c 6c 20 61 73 20 22 64 6f 6d 61 69 6e 4e 6f 74 |ll as "domainNot|
|00000220| 4e 75 6c 6c 22 2c 20 70 67 5f 63 61 74 61 6c 6f |Null", pg_catalo|
|00000230| 67 2e 70 67 5f 67 65 74 5f 65 78 70 72 28 74 79 |g.pg_get_expr(ty|
|00000240| 70 64 65 66 61 75 6c 74 62 69 6e 2c 30 29 20 61 |pdefaultbin,0) a|
|00000250| 73 20 22 64 6f 6d 61 69 6e 44 65 66 61 75 6c 74 |s "domainDefault|
|00000260| 22 2c 20 20 20 20 72 6e 67 73 75 62 74 79 70 65 |",    rngsubtype|
|00000270| 20 61 73 20 22 72 61 6e 67 65 42 61 73 65 54 79 | as "rangeBaseTy|
|00000280| 70 65 49 64 22 20 20 66 72 6f 6d 20 20 20 70 67 |peId"  from   pg|
|00000290| 5f 63 61 74 61 6c 6f 67 2e 70 67 5f 74 79 70 65 |_catalog.pg_type|
|000002a0| 20 74 20 6c 65 66 74 20 6a 6f 69 6e 20 70 67 5f | t left join pg_|
|000002b0| 63 61 74 61 6c 6f 67 2e 70 67 5f 6e 61 6d 65 73 |catalog.pg_names|
|000002c0| 70 61 63 65 20 6e 20 6f 6e 20 28 74 2e 74 79 70 |pace n on (t.typ|
|000002d0| 6e 61 6d 65 73 70 61 63 65 20 3d 20 6e 2e 6f 69 |namespace = n.oi|
|000002e0| 64 29 20 20 6c 65 66 74 20 6a 6f 69 6e 20 70 67 |d)  left join pg|
|000002f0| 5f 63 61 74 61 6c 6f 67 2e 70 67 5f 72 61 6e 67 |_catalog.pg_rang|
|00000300| 65 20 72 20 6f 6e 20 28 74 2e 6f 69 64 20 3d 20 |e r on (t.oid = |
|00000310| 72 2e 72 6e 67 74 79 70 69 64 29 00 00 00 44 00 |r.rngtypid)...D.|
|00000320| 00 00 06 53 00 53 00 00 00 04                   |...S.S....      |
+--------+-------------------------------------------------+----------------+
```

So, it is clear that the message has definitely changed

**Comment by jesperpedersen** [comment]
4.0.28:

```
50 00 00 03 1d
```

4.0.29:

```
00 00 03 1e ff
```

Maybe https://github.com/netty/netty/commit/979fdfd3d3e641fd8e003db19ae976d8e6e8adbe and interaction in
https://github.com/impossibl/pgjdbc-ng/blob/develop/src/main/java/com/impossibl/postgres/protocol/v30/ProtocolImpl.java#L742
https://github.com/impossibl/pgjdbc-ng/blob/develop/src/main/java/com/impossibl/postgres/protocol/v30/ProtocolImpl.java#L752

**Comment by normanmaurer** [comment]
@jesperpedersen use the UnpooledByteBufAllocator (which is the default btw) and see if it makes a difference.

**Comment by jesperpedersen** [comment]
@normanmaurer You nailed it ! Using  io.netty.buffer.PooledByteBufAllocator led to the error

**Comment by kdubb** [comment]
So to make it work with Pooled (just to understand the error) it seems we need to reset the writer index before re-using a ByteBuf from the pool?

**Comment by normanmaurer** [comment]
@jesperpedersen so you say as soon as you use `PooledByteBufAllocator` you see this error ?

**Comment by jesperpedersen** [comment]
@normanmaurer correct

**Comment by normanmaurer** [comment]
@jesperpedersen and this happens since version 4.0.29 and also with latest stable one (4.0.31.Final) right ? Just to understand it better and be able to find the root cause easier.

**Comment by jesperpedersen** [comment]
@normanmaurer Yup - regression is between 4.0.28 and 4.0.29 - maybe https://github.com/netty/netty/commit/979fdfd3d3e641fd8e003db19ae976d8e6e8adbe ?

**Comment by kdubb** [comment]
@jesperpedersen  I think you're onto something

**Comment by jesperpedersen** [comment]
@kdubb I consider this issue the only possible blocker for the 0.6 release

**Comment by normanmaurer** [comment]
@jesperpedersen I don't think this can be the problem. I will see if I can find out whats going on tomorrow

**Comment by normanmaurer** [comment]
@jesperpedersen I think I have an idea... stay tuned.

**Comment by normanmaurer** [comment]
@jesperpedersen can you please check https://github.com/netty/netty/pull/4278. This fixes it for me

**Comment by jesperpedersen** [comment]
@normanmaurer Works, thanks !

**Comment by kdubb** [comment]
@normanmaurer Nice Job! Thanks!

**Comment by jesperpedersen** [comment]
Netty 4.0.32.Final has been integrated

**Comment by normanmaurer** [comment]
@jesperpedersen haha... you are even faster then I'm able to announce ;) But almost there. Thanks again!

**Comment by brcolow** [comment]
~~Awesome! Really great work - thanks so much. Would it be possible to get a new release with this commit? Thanks much.~~

Edit: I see #203 has already been created - sorry about that =)
