### ISSUE TITLE
Add support for CITEXT type

### ISSUE THREAD

**Issue by guylabs** [impossibl/pgjdbc-ng#188]
Hi,

I wanted to try this driver but unfortunately the `CITEXT` type is not supported. This is the exception I get when querying the database with a `CITEXT` type field:

```
Caused by: java.lang.IllegalStateException: type has no supported parameter format
    at com.impossibl.postgres.types.Type.getParameterFormat(Type.java:307)
    at com.impossibl.postgres.protocol.v30.ProtocolImpl.lengthOfParams(ProtocolImpl.java:723)
    at com.impossibl.postgres.protocol.v30.ProtocolImpl.writeBind(ProtocolImpl.java:508)
    at com.impossibl.postgres.protocol.v30.BindExecCommandImpl.execute(BindExecCommandImpl.java:319)
    at com.impossibl.postgres.protocol.v30.ProtocolImpl.execute(ProtocolImpl.java:370)
    at com.impossibl.postgres.jdbc.PGConnectionImpl.execute(PGConnectionImpl.java:434)
    at com.impossibl.postgres.jdbc.PGStatement.executeStatement(PGStatement.java:375)
    at com.impossibl.postgres.jdbc.PGPreparedStatement.execute(PGPreparedStatement.java:261)
    at com.impossibl.postgres.jdbc.PGPreparedStatement.executeQuery(PGPreparedStatement.java:277)
    at com.impossibl.postgres.jdbc.PGPreparedStatement.executeQuery(PGPreparedStatement.java:92)
    at com.zaxxer.hikari.proxy.PreparedStatementProxy.executeQuery(PreparedStatementProxy.java:52)
    at com.zaxxer.hikari.proxy.PreparedStatementJavassistProxy.executeQuery(PreparedStatementJavassistProxy.java)
    at org.springframework.jdbc.core.JdbcTemplate$1.doInPreparedStatement(JdbcTemplate.java:646)
    at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:589)
    at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:639)
    at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:664)
    at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:704)
    at org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate.query(NamedParameterJdbcTemplate.java:179)
```

It would be nice when you could support the `CITEXT` type. It's nice that you took the opportunity to implement a new updated driver which supports the new features.

Thanks and regards,

Guy

**Comment by jesperpedersen** [comment]
Thanks for the report.

This brings up an interesting discussion about what we should do about data types that we don't have a `Proc` implementation for. An option could be to add an option to do a `String` fallback. Question is what the default value should be for that though. There are pros/cons for both `false`/`true`.

That said, I would be ok with including `Proc` implementations for all data types distributed with the standard PostgreSQL repository. In this case it is simple, as it is a `String` mapping.

Thoughts welcome !

**Comment by kdubb** [comment]
citext should be supported?  It was just an alias on "Strings"

**Comment by jesperpedersen** [comment]
I think you are thinking of `cstring` -- https://github.com/impossibl/pgjdbc-ng/blob/develop/src/main/java/com/impossibl/postgres/system/procs/Strings.java#L54

`CITEXT` is an extension type.

**Comment by kdubb** [comment]
No I was misremembering.  We tried using citext in the Impossibl server project (a now defunct project that gave rise to this driver).  I immediately went and added it to Strings.java and it had issues (I cannot remember what).  We also removed it from the server so I skipped it and went on my merry way.

**Comment by kdubb** [comment]
Adding it back to Strings.java and seeing if there are still problems is step 1.  I cannot figure why it wouldn't "just work".

**Comment by jesperpedersen** [comment]
Well, it is sort of related to the `jsonb` discussion too -- yes, they are `String`'s, but they should have a `java.sql.Types.OTHER` id in the end. But, we can take that discussion later

**Comment by kdubb** [comment]
Case insensitive text should have Types.OTHER?  That seems incorrect.  jsonb I agree.

**Comment by jesperpedersen** [comment]
No, not `CITEXT`, but `json` f.ex. in Strings.java

**Comment by kdubb** [comment]
Yes that's why XML is it's own type, specifically to give it it's own type in PG and JDBC. JSON obviously needs the same.

**Comment by guylabs** [comment]
Hi,

are there any news on this issue or plans if you will support it? I could also help with the issue if you want to.

Thanks and regards,

Guy

**Comment by jesperpedersen** [comment]
@guylabs Feel free to work on this - start by modifying Strings.java to include it, and see what happens
