### ISSUE TITLE
Deadlock issue with 0.5

### ISSUE THREAD

**Issue by markworden** [impossibl/pgjdbc-ng#194]
I ran into a deadlock issue with a thread periodically performing an action and executing a check to see if the connection was valid.  Another thread happen to have been handling a change notification and then attempting to find a specific row in the DB.

Notification Thread:

"PG-JDBC EventLoop (5)" #22 daemon prio=5 os_prio=0 tid=0x00007f412783d800 nid=0x472e in Object.wait() [0x00007f4151423000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
        at java.lang.Object.wait(Native Method)
        at com.impossibl.postgres.protocol.v30.CommandImpl.waitFor(CommandImpl.java:119)
        - locked <0x0000000783c67118> (a com.impossibl.postgres.protocol.v30.QueryCommandImpl$QueryListener)
        at com.impossibl.postgres.protocol.v30.QueryCommandImpl.execute(QueryCommandImpl.java:173)
        at com.impossibl.postgres.protocol.v30.ProtocolImpl.execute(ProtocolImpl.java:370)
        - locked <0x00000006ca41a5b0> (a com.impossibl.postgres.protocol.v30.ProtocolImpl)
        at com.impossibl.postgres.system.BasicContext.query(BasicContext.java:484)
        at com.impossibl.postgres.jdbc.PGConnectionImpl.execute(PGConnectionImpl.java:479)
        at com.impossibl.postgres.jdbc.PGConnectionImpl.setReadOnly(PGConnectionImpl.java:746)
        at sun.reflect.GeneratedMethodAccessor101.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.apache.tomcat.jdbc.pool.ProxyConnection.invoke(ProxyConnection.java:126)
        at org.apache.tomcat.jdbc.pool.JdbcInterceptor.invoke(JdbcInterceptor.java:108)
        at org.apache.tomcat.jdbc.pool.DisposableConnectionFacade.invoke(DisposableConnectionFacade.java:81)
        at com.sun.proxy.$Proxy63.setReadOnly(Unknown Source)
        at org.springframework.jdbc.datasource.DataSourceUtils.prepareConnectionForTransaction(DataSourceUtils.java:155)
        at org.springframework.orm.jpa.vendor.HibernateJpaDialect.beginTransaction(HibernateJpaDialect.java:154)
        at org.springframework.orm.jpa.JpaTransactionManager.doBegin(JpaTransactionManager.java:380)
        at org.springframework.transaction.support.AbstractPlatformTransactionManager.getTransaction(AbstractPlatformTransactionManager.java:373)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.createTransactionIfNecessary(TransactionAspectSupport.java:463)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:276)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:136)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.springframework.data.jpa.repository.support.CrudMethodMetadataPostProcessor$CrudMethodMetadataPopulatingMethodIntercceptor.invoke(CrudMethodMetadataPostProcessor.java:122)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207)
        at com.sun.proxy.$Proxy117.findOne(Unknown Source)
...

Periodic Thread:
"Thread-10" #39 prio=5 os_prio=0 tid=0x00007f412d5bc800 nid=0x4752 in Object.wait() [0x00007f40f67f4000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
        at java.lang.Object.wait(Native Method)
        at com.impossibl.postgres.protocol.v30.CommandImpl.waitFor(CommandImpl.java:119)
        - locked <0x000000078ce775d0> (a com.impossibl.postgres.protocol.v30.QueryCommandImpl$QueryListener)
        at com.impossibl.postgres.protocol.v30.QueryCommandImpl.execute(QueryCommandImpl.java:173)
        at com.impossibl.postgres.protocol.v30.ProtocolImpl.execute(ProtocolImpl.java:370)
        - locked <0x00000006cd46a268> (a com.impossibl.postgres.protocol.v30.ProtocolImpl)
        at com.impossibl.postgres.system.BasicContext.queryResults(BasicContext.java:446)
        at com.impossibl.postgres.system.BasicContext.queryFirstResultString(BasicContext.java:533)
        at com.impossibl.postgres.jdbc.PGConnectionImpl.executeForString(PGConnectionImpl.java:525)
        at com.impossibl.postgres.jdbc.PGConnectionImpl.isValid(PGConnectionImpl.java:656)
        - locked <0x00000006cd0386b8> (a com.impossibl.postgres.jdbc.PGConnectionImpl)
...

**Comment by markworden** [comment]
I would like to reject my described issue above.  I probably should not have been making a DB query in the notification callback PG-JDBC EventLoop thread.  If there is concurrence to that, feel free to close.

**Comment by kdubb** [comment]
@markworden I haven't had a chance to look into the deadlock you presented. Certainly the notification system presents interesting problems like this and I would like to investigate ways to make it more bulletproof.  I'll leave it open until somebody can look into it in depth.

**Comment by dineshudayakumar** [comment]
I am seeing similar issue.

I have one periodic scheduler which uses connection.isValid(1) to check whether the connection is valid every 5 seconds. And that thread is hung indefinitely. Here is the stack traces from the thread dump

Periodic scheduler thread name - pool-15-thread-1 which is in waitfor() indefinitely and holding the monitor for PGConnectionImpl@0x0000000093EE4350 and PG-JDBC EventLoop (1) is blocked on the monitor PGConnectionImpl@0x0000000093EE4350 owned by the pool-15-thread-1

Any inputs why the pool-15-thread-1 is hung in waitfor() ?

3XMTHREADINFO      "pool-15-thread-1" J9VMThread:0x0000000005075800, j9thread_t:0x00007FC8CEC7E3F0, java/lang/Thread:0x0000000093F46230, state:CW, prio=5
3XMJAVALTHREAD            (java/lang/Thread getId:0xC8, isDaemon:false)
3XMTHREADINFO1            (native thread ID:0x958, native priority:0x5, native policy:UNKNOWN, vmstate:CW, vm thread flags:0x00080101)
3XMTHREADINFO2            (native stack address range from:0x00007FC8B67C0000, to:0x00007FC8B6800000, size:0x40000)
3XMCPUTIME               CPU usage total: 2.612505053 secs, current category="Application"
3XMTHREADBLOCK     Waiting on: com/impossibl/postgres/protocol/v30/QueryCommandImpl$Listener@0x00000000919C48D0 Owned by: <unowned>
3XMHEAPALLOC             Heap bytes allocated since last GC cycle=0 (0x0)
3XMTHREADINFO3           Java callstack:
4XESTACKTRACE                at java/lang/Object.wait(Native Method)
4XESTACKTRACE                at java/lang/Object.wait(Object.java:201(Compiled Code))
4XESTACKTRACE                at com/impossibl/postgres/protocol/v30/CommandImpl.waitFor(CommandImpl.java:119(Compiled Code))
5XESTACKTRACE                   (entered lock: com/impossibl/postgres/protocol/v30/QueryCommandImpl$Listener@0x00000000919C48D0, entry count: 1)
4XESTACKTRACE                at com/impossibl/postgres/protocol/v30/QueryCommandImpl.execute(QueryCommandImpl.java:163(Compiled Code))
4XESTACKTRACE                at com/impossibl/postgres/protocol/v30/ProtocolImpl.execute(ProtocolImpl.java:371(Compiled Code))
5XESTACKTRACE                   (entered lock: com/impossibl/postgres/protocol/v30/ProtocolImpl@0x0000000094077338, entry count: 1)
4XESTACKTRACE                at com/impossibl/postgres/system/BasicContext.queryResults(BasicContext.java:531(Compiled Code))
4XESTACKTRACE                at com/impossibl/postgres/system/BasicContext.queryFirstResultString(BasicContext.java:576(Compiled Code))
4XESTACKTRACE                at com/impossibl/postgres/jdbc/PGConnectionImpl.executeForString(PGConnectionImpl.java:544(Compiled Code))
4XESTACKTRACE                at com/impossibl/postgres/jdbc/PGConnectionImpl.isValid(PGConnectionImpl.java:731(Compiled Code))
5XESTACKTRACE                   (entered lock: com/impossibl/postgres/jdbc/PGConnectionImpl@0x0000000093EE4350, entry count: 1)
4XESTACKTRACE                at com/avaya/zephyr/platform/resources/PlatformResourcesNotificationListenerImpl$PgConnectionVerifier.run(PlatformResourcesNotificationListenerImpl.java:142(Compiled Code))
5XESTACKTRACE                   (entered lock: java/lang/Object@0x0000000093EE43F8, entry count: 1)
4XESTACKTRACE                at java/util/concurrent/Executors$RunnableAdapter.call(Executors.java:522(Compiled Code))
4XESTACKTRACE                at java/util/concurrent/FutureTask.runAndReset(FutureTask.java:319(Compiled Code))
4XESTACKTRACE                at java/util/concurrent/ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:191(Compiled Code))
4XESTACKTRACE                at java/util/concurrent/ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305(Compiled Code))
4XESTACKTRACE                at java/util/concurrent/ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1153(Compiled Code))
4XESTACKTRACE                at java/util/concurrent/ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
4XESTACKTRACE                at java/lang/Thread.run(Thread.java:785)
3XMTHREADINFO3           Native callstack:
4XENATIVESTACK               (0x00007FC8E10AF882 [libj9prt28.so+0x2f882])
4XENATIVESTACK               (0x00007FC8E10BED05 [libj9prt28.so+0x3ed05])
4XENATIVESTACK               (0x00007FC8E10AF3FC [libj9prt28.so+0x2f3fc])
4XENATIVESTACK               (0x00007FC8E10AF4FE [libj9prt28.so+0x2f4fe])
4XENATIVESTACK               (0x00007FC8E10BED05 [libj9prt28.so+0x3ed05])
4XENATIVESTACK               (0x00007FC8E10AEFDF [libj9prt28.so+0x2efdf])
4XENATIVESTACK               (0x00007FC8E10A8677 [libj9prt28.so+0x28677])
4XENATIVESTACK               (0x00007FC8E2D51680 [libpthread.so.0+0xf680])
4XENATIVESTACK               pthread_cond_timedwait+0x132 (0x00007FC8E2D4DCF2 [libpthread.so.0+0xbcf2])
4XENATIVESTACK               (0x00007FC8E14FC764 [libj9thr28.so+0x7764])
4XENATIVESTACK               (0x00007FC8E17BBE6A [libj9vm28.so+0xb1e6a])
4XENATIVESTACK               (0x00007FC8E1756C3F [libj9vm28.so+0x4cc3f])
4XENATIVESTACK               (0x00007FC8B7026C24 [<unknown>+0x0])



3XMTHREADINFO      "PG-JDBC EventLoop (1)" J9VMThread:0x0000000005158C00, j9thread_t:0x00007FC8CC03F790, java/lang/Thread:0x0000000093F463A0, state:B, prio=5
3XMJAVALTHREAD            (java/lang/Thread getId:0xCA, isDaemon:true)
3XMTHREADINFO1            (native thread ID:0x9FE, native priority:0x5, native policy:UNKNOWN, vmstate:B, vm thread flags:0x00000201)
3XMTHREADINFO2            (native stack address range from:0x00007FC8B673E000, to:0x00007FC8B677E000, size:0x40000)
3XMCPUTIME               CPU usage total: 13.008269614 secs, current category="Application"
3XMTHREADBLOCK     Blocked on: com/impossibl/postgres/jdbc/PGConnectionImpl@0x0000000093EE4350 Owned by: "pool-15-thread-1" (J9VMThread:0x0000000005075800, java/lang/Thread:0x0000000093F46230)
3XMHEAPALLOC             Heap bytes allocated since last GC cycle=0 (0x0)
3XMTHREADINFO3           Java callstack:
4XESTACKTRACE                at com/impossibl/postgres/protocol/v30/ProtocolImpl.receiveNotification(ProtocolImpl.java:1143(Compiled Code))
4XESTACKTRACE                at com/impossibl/postgres/protocol/v30/ProtocolImpl.dispatch(ProtocolImpl.java:781(Compiled Code))
4XESTACKTRACE                at com/impossibl/postgres/protocol/v30/MessageHandler.channelRead(MessageHandler.java:45(Compiled Code))
4XESTACKTRACE                at io/netty/channel/AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318(Compiled Code))
4XESTACKTRACE                at io/netty/channel/AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304(Compiled Code))
4XESTACKTRACE                at io/netty/handler/codec/ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:276(Compiled Code))
4XESTACKTRACE                at io/netty/handler/codec/ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:263(Compiled Code))
4XESTACKTRACE                at io/netty/channel/AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318(Compiled Code))
4XESTACKTRACE                at io/netty/channel/AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304(Compiled Code))
4XESTACKTRACE                at io/netty/channel/DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846(Compiled Code))
4XESTACKTRACE                at io/netty/channel/nio/AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131(Compiled Code))
4XESTACKTRACE                at io/netty/channel/nio/NioEventLoop.processSelectedKey(NioEventLoop.java:511(Compiled Code))
4XESTACKTRACE                at io/netty/channel/nio/NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468(Compiled Code))
4XESTACKTRACE                at io/netty/channel/nio/NioEventLoop.processSelectedKeys(NioEventLoop.java:382(Compiled Code))
4XESTACKTRACE                at io/netty/channel/nio/NioEventLoop.run(NioEventLoop.java:354(Compiled Code))
4XESTACKTRACE                at io/netty/util/concurrent/SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
4XESTACKTRACE                at java/lang/Thread.run(Thread.java:785)
3XMTHREADINFO3           Native callstack:
4XENATIVESTACK               (0x00007FC8E10AF882 [libj9prt28.so+0x2f882])
4XENATIVESTACK               (0x00007FC8E10BED05 [libj9prt28.so+0x3ed05])
4XENATIVESTACK               (0x00007FC8E10AF3FC [libj9prt28.so+0x2f3fc])
4XENATIVESTACK               (0x00007FC8E10AF4FE [libj9prt28.so+0x2f4fe])
4XENATIVESTACK               (0x00007FC8E10BED05 [libj9prt28.so+0x3ed05])
4XENATIVESTACK               (0x00007FC8E10AEFDF [libj9prt28.so+0x2efdf])
4XENATIVESTACK               (0x00007FC8E10A8677 [libj9prt28.so+0x28677])
4XENATIVESTACK               (0x00007FC8E2D51680 [libpthread.so.0+0xf680])
4XENATIVESTACK               pthread_cond_wait+0xc3 (0x00007FC8E2D4D943 [libpthread.so.0+0xb943])
4XENATIVESTACK               (0x00007FC8E14FC33D [libj9thr28.so+0x733d])
4XENATIVESTACK               (0x00007FC8E1767A94 [libj9vm28.so+0x5da94])
4XENATIVESTACK               (0x00007FC8E17688F1 [libj9vm28.so+0x5e8f1])
4XENATIVESTACK               (0x00007FC8E1766A95 [libj9vm28.so+0x5ca95])
4XENATIVESTACK               (0x00007FC8D93803F4 [libj9jit28.so+0x8e53f4])

**Comment by kdubb** [comment]
Querying in notification listeners should work as long as you're managing the connections correctly (one per thread); it's now in the test suite via #356
