### ISSUE TITLE
issue with pgjdbc-ng

### ISSUE THREAD

**Issue by abhishekparwal** [impossibl/pgjdbc-ng#198]
@brettwooldridge 
@kdubb 
@jesperpedersen 

I am using pgjdc-ng with hikari cp. my project is in java 1.8 and is using functions like lambda.

I am trying to use this library and getting this error. Is this related to https://github.com/impossibl/pgjdbc-ng/pull/165 ? And if no, can you kindly point me to the issue.

Stacktrace:

java.io.IOException: invalid utility query
    at com.impossibl.postgres.system.BasicContext.prepareQuery(BasicContext.java:406) [pgjdbc-ng-0.5.jar:na]
    at com.impossibl.postgres.system.BasicContext.queryBatch(BasicContext.java:550) [pgjdbc-ng-0.5.jar:na]
    at com.impossibl.postgres.system.BasicContext.queryResults(BasicContext.java:424) [pgjdbc-ng-0.5.jar:na]
    at com.impossibl.postgres.system.BasicContext.refreshTypes(BasicContext.java:329) [pgjdbc-ng-0.5.jar:na]
    at com.impossibl.postgres.system.BasicContext.refreshType(BasicContext.java:297) [pgjdbc-ng-0.5.jar:na]
    at com.impossibl.postgres.types.Registry.loadType(Registry.java:146) [pgjdbc-ng-0.5.jar:na]
    at com.impossibl.postgres.types.Registry.update(Registry.java:388) [pgjdbc-ng-0.5.jar:na]
    at com.impossibl.postgres.system.BasicContext.loadTypes(BasicContext.java:268) [pgjdbc-ng-0.5.jar:na]
    at com.impossibl.postgres.system.BasicContext.init(BasicContext.java:244) [pgjdbc-ng-0.5.jar:na]
    at com.impossibl.postgres.jdbc.PGConnectionImpl.init(PGConnectionImpl.java:237) [pgjdbc-ng-0.5.jar:na]
    at com.impossibl.postgres.jdbc.ConnectionUtil.createConnection(ConnectionUtil.java:182) [pgjdbc-ng-0.5.jar:na]
    at com.impossibl.postgres.jdbc.AbstractDataSource.createConnection(AbstractDataSource.java:465) [pgjdbc-ng-0.5.jar:na]
    at com.impossibl.postgres.jdbc.PGDataSource.getConnection(PGDataSource.java:66) [pgjdbc-ng-0.5.jar:na]
    at com.impossibl.postgres.jdbc.PGDataSource.getConnection(PGDataSource.java:58) [pgjdbc-ng-0.5.jar:na]
    at com.zaxxer.hikari.pool.HikariPool.addConnection(HikariPool.java:496) [HikariCP-2.4.1.jar:na]
    at com.zaxxer.hikari.pool.HikariPool.initializeConnections(HikariPool.java:565) [HikariCP-2.4.1.jar:na]
    at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:152) [HikariCP-2.4.1.jar:na]
    at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:73) [HikariCP-2.4.1.jar:na]
    at org.hibernate.hikaricp.internal.HikariCPConnectionProvider.configure(HikariCPConnectionProvider.java:59) [hibernate-hikaricp-5.0.1.Final.jar:5.0.1.Final]
    at org.hibernate.boot.registry.internal.StandardServiceRegistryImpl.configureService(StandardServiceRegistryImpl.java:94) [hibernate-core-5.0.1.Final.jar:5.0.1.Final]
    at org.hibernate.service.internal.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:217) [hibernate-core-5.0.1.Final.jar:5.0.1.Final]
    at org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:189) [hibernate-core-5.0.1.Final.jar:5.0.1.Final]
    at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.buildJdbcConnectionAccess(JdbcEnvironmentInitiator.java:145) [hibernate-core-5.0.1.Final.jar:5.0.1.Final]
    at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.initiateService(JdbcEnvironmentInitiator.java:66) [hibernate-core-5.0.1.Final.jar:5.0.1.Final]
    at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.initiateService(JdbcEnvironmentInitiator.java:35) [hibernate-core-5.0.1.Final.jar:5.0.1.Final]
    at org.hibernate.boot.registry.internal.StandardServiceRegistryImpl.initiateService(StandardServiceRegistryImpl.java:88) [hibernate-core-5.0.1.Final.jar:5.0.1.Final]
    at org.hibernate.service.internal.AbstractServiceRegistryImpl.createService(AbstractServiceRegistryImpl.java:234) [hibernate-core-5.0.1.Final.jar:5.0.1.Final]
    at org.hibernate.service.internal.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:208) [hibernate-core-5.0.1.Final.jar:5.0.1.Final]
    at org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:189) [hibernate-core-5.0.1.Final.jar:5.0.1.Final]
    at org.hibernate.engine.jdbc.internal.JdbcServicesImpl.configure(JdbcServicesImpl.java:51) [hibernate-core-5.0.1.Final.jar:5.0.1.Final]
    at org.hibernate.boot.registry.internal.StandardServiceRegistryImpl.configureService(StandardServiceRegistryImpl.java:94) [hibernate-core-5.0.1.Final.jar:5.0.1.Final]
    at org.hibernate.service.internal.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:217) [hibernate-core-5.0.1.Final.jar:5.0.1.Final]
    at org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:189) [hibernate-core-5.0.1.Final.jar:5.0.1.Final]
    at org.hibernate.boot.model.process.spi.MetadataBuildingProcess.handleTypes(MetadataBuildingProcess.java:352) [hibernate-core-5.0.1.Final.jar:5.0.1.Final]
    at org.hibernate.boot.model.process.spi.MetadataBuildingProcess.complete(MetadataBuildingProcess.java:111) [hibernate-core-5.0.1.Final.jar:5.0.1.Final]
    at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.metadata(EntityManagerFactoryBuilderImpl.java:770) [hibernate-entitymanager-5.0.1.Final.jar:5.0.1.Final]
    at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:797) [hibernate-entitymanager-5.0.1.Final.jar:5.0.1.Final]
    at org.hibernate.jpa.HibernatePersistenceProvider.createEntityManagerFactory(HibernatePersistenceProvider.java:58) [hibernate-entitymanager-5.0.1.Final.jar:5.0.1.Final]

Thanks in advance.

**Comment by kdubb** [comment]
Seems like an issue with a non supported version of Postgres.  What server version are you using?

**Comment by abhishekparwal** [comment]
SELECT version();

##                                                       version                                                      

 EnterpriseDB 9.2.1.3 on x86_64-unknown-linux-gnu, compiled by gcc (GCC) 4.1.2 20080704 (Red Hat 4.1.2-52), 64-bit

queryTxt was  -@refresh-type when this code was called.

**Comment by kdubb** [comment]
It looks like you have some sort of circularly defined UDT.  @refresh-type is a utility query (aka internally used prepared query) and it's undefined because it's trying to be used while the driver is trying to load types.

**Comment by abhishekparwal** [comment]
It  works  when  I replace it  with  official postgres driver jar.  And  I
am not defining any udt.  I am using hibernate  version 5.

**Comment by kdubb** [comment]
Yes the official drive doesn't attempt to download all types like we do.  I'm assuming the issue has to do with a UDT defined by EnterpriseDB rather than yourself.  I've never tested the driver on EnterpriseDB myself.

**Comment by abhishekparwal** [comment]
is there any workaround? Or I have to switch to official driver? Any plans to fix it?

**Comment by kdubb** [comment]
Without some debugging I'm not able to offer a workaround or a patch.  I need to get into a EnterpriseDB instance and see what the issue is. Unfortunately my currently available time is very limited.

**Comment by jesperpedersen** [comment]
EnterpriseDB has a lot of extra types, so you need to verify their pg_type catalog definitions. However, they have their own JDBC driver, so I suggest you use that one.

However, feel free reopen if you have a patch for this.
