### ISSUE TITLE
issue with pgjdbc-ng

### ISSUE THREAD

**Issue by abhishekparwal** [impossibl/pgjdbc-ng#204]
@brettwooldridge 
@kdubb 
@jesperpedersen 

I am using pgjdc-ng with hikari cp. I am using postgres:

select version();
##                                                   version                                                  

 PostgreSQL 9.3.9 on x86_64-unknown-linux-gnu, compiled by gcc (Ubuntu 4.8.4-2ubuntu1~14.04) 4.8.4, 64-bit
(1 row)

I am getting this error. 

Caused by: com.zaxxer.hikari.pool.PoolInitializationException: Exception during pool initialization: Connection Error: invalid frontend message type 0
    at com.zaxxer.hikari.pool.HikariPool.initializeConnections(HikariPool.java:581) ~[HikariCP-2.4.1.jar:na]
    at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:152) ~[HikariCP-2.4.1.jar:na]
    at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:73) ~[HikariCP-2.4.1.jar:na]
    at org.hibernate.hikaricp.internal.HikariCPConnectionProvider.configure(HikariCPConnectionProvider.java:59) ~[hibernate-hikaricp-5.0.1.Final.jar:5.0.1.Final]
    ... 47 common frames omitted
Caused by: com.impossibl.postgres.jdbc.PGSQLSimpleException: Connection Error: invalid frontend message type 0
    at com.impossibl.postgres.jdbc.ErrorUtils.makeSQLException(ErrorUtils.java:159) ~[pgjdbc-ng-0.5.jar:na]
    at com.impossibl.postgres.jdbc.ConnectionUtil.createConnection(ConnectionUtil.java:193) ~[pgjdbc-ng-0.5.jar:na]
    at com.impossibl.postgres.jdbc.AbstractDataSource.createConnection(AbstractDataSource.java:465) ~[pgjdbc-ng-0.5.jar:na]
    at com.impossibl.postgres.jdbc.PGDataSource.getConnection(PGDataSource.java:66) ~[pgjdbc-ng-0.5.jar:na]
    at com.impossibl.postgres.jdbc.PGDataSource.getConnection(PGDataSource.java:58) ~[pgjdbc-ng-0.5.jar:na]
    at com.zaxxer.hikari.pool.HikariPool.addConnection(HikariPool.java:496) ~[HikariCP-2.4.1.jar:na]
    at com.zaxxer.hikari.pool.HikariPool.initializeConnections(HikariPool.java:565) ~[HikariCP-2.4.1.jar:na]

On basic debugging found that it was issuing this query:
select   t.oid, typname as "name", typlen as "length", typtype as "discriminator", typcategory as "category", typdelim as "deliminator", typrelid as "relationId",   typelem as "elementTypeId", typarray as "arrayTypeId", typinput::oid as "inputId", typoutput::oid as "outputId", typreceive::oid as "receiveId", typsend::oid as "sendId",   typmodin::oid as "modInId", typmodout::oid as "modOutId", typalign as alignment, n.nspname as "namespace",    typbasetype as "domainBaseTypeId", typtypmod as "domainTypeMod", typnotnull as "domainNotNull", pg_catalog.pg_get_expr(typdefaultbin,0) as "domainDefault",    rngsubtype as "rangeBaseTypeId"  from   pg_catalog.pg_type t left join pg_catalog.pg_namespace n on (t.typnamespace = n.oid)  left join pg_catalog.pg_range r on (t.oid = r.rngtypid);

Can you point me to the issue?

**Comment by jesperpedersen** [comment]
Make sure that you are using Netty 4.0.32+

**Comment by abhishekparwal** [comment]
thanks. it solved the issue.
