### ISSUE TITLE
Exception with new ssl data sources options

### ISSUE THREAD

**Issue by brcolow** [impossibl/pgjdbc-ng#210]
Hello,

I am using the latest commit 441b1204db to test the ssl data sources options. With the following line:

``` java
config.addDataSourceProperty("ssl.cert.file", "/server.crt");
```

where config is:

``` java
config = new HikariConfig();
```

from HikariCP. I get the exception:

```
12:44:41.746 [main] ERROR com.zaxxer.hikari.util.PropertyElf - Property ssl.cert.file does not exist on target class com.imp
ossibl.postgres.jdbc.PGDataSource
12:44:41.747 [main] ERROR net.cryptodirect.centurion.Centurion - Uncaught exception on thread: Thread[main,5,main]
12:44:41.756 [main] ERROR net.cryptodirect.centurion.Centurion - Exception:
java.lang.RuntimeException: java.beans.IntrospectionException: Method not found: setSsl.cert.file
        at com.zaxxer.hikari.util.PropertyElf.setProperty(PropertyElf.java:141) ~[centurion-1.0-SNAPSHOT.jar:na]
        at com.zaxxer.hikari.util.PropertyElf.setTargetFromProperties(PropertyElf.java:64) ~[centurion-1.0-SNAPSHOT.jar:na]
        at com.zaxxer.hikari.pool.PoolElf.initializeDataSource(PoolElf.java:154) ~[centurion-1.0-SNAPSHOT.jar:na]
        at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:113) ~[centurion-1.0-SNAPSHOT.jar:na]
        at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:73) ~[centurion-1.0-SNAPSHOT.jar:na]
        at net.cryptodirect.centurion.db.Database.<init>(Database.java:99) ~[centurion-1.0-SNAPSHOT.jar:na]
        at net.cryptodirect.centurion.Centurion.main(Centurion.java:37) ~[centurion-1.0-SNAPSHOT.jar:na]
Caused by: java.beans.IntrospectionException: Method not found: setSsl.cert.file
        at java.beans.PropertyDescriptor.<init>(PropertyDescriptor.java:110) ~[na:1.8.0_60]
```

It would appear as though it wants the property without the dots, and in camel-case

However, replacing with:

`config.addDataSourceProperty("ssl.cert.file", "/server.crt");`

Seems to result in the identical exception:

```
12:48:27.406 [main] ERROR com.zaxxer.hikari.util.PropertyElf - Property sslCertFile does not exist on target class com.impossibl.postgres.jdbc.PGDataSource
12:48:27.407 [main] ERROR net.cryptodirect.centurion.Centurion - Uncaught exception on thread: Thread[main,5,main]
12:48:27.414 [main] ERROR net.cryptodirect.centurion.Centurion - Exception:
java.lang.RuntimeException: java.beans.IntrospectionException: Method not found: setSslCertFile
        at com.zaxxer.hikari.util.PropertyElf.setProperty(PropertyElf.java:141) ~[centurion-1.0-SNAPSHOT.jar:na]
        at com.zaxxer.hikari.util.PropertyElf.setTargetFromProperties(PropertyElf.java:64) ~[centurion-1.0-SNAPSHOT.jar:na]
        at com.zaxxer.hikari.pool.PoolElf.initializeDataSource(PoolElf.java:154) ~[centurion-1.0-SNAPSHOT.jar:na]
        at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:113) ~[centurion-1.0-SNAPSHOT.jar:na]
        at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:73) ~[centurion-1.0-SNAPSHOT.jar:na]
        at net.cryptodirect.centurion.db.Database.<init>(Database.java:99) ~[centurion-1.0-SNAPSHOT.jar:na]
        at net.cryptodirect.centurion.Centurion.main(Centurion.java:37) ~[centurion-1.0-SNAPSHOT.jar:na]
Caused by: java.beans.IntrospectionException: Method not found: setSslCertFile
        at java.beans.PropertyDescriptor.<init>(PropertyDescriptor.java:110) ~[na:1.8.0_60]
        at com.zaxxer.hikari.util.PropertyElf.setProperty(PropertyElf.java:132) ~[centurion-1.0-SNAPSHOT.jar:na]
```

Using pgjdbc-ng at commit 441b1204db,
HikariCP 2.4.1

**Comment by jesperpedersen** [comment]
Hi, The data source properties doesn't have '.'s in them. See README.md

**Comment by brcolow** [comment]
Darn, the second line was supposed to be config.addDataSourceProperty("sslCertFile", "/server.crt");

**Comment by jesperpedersen** [comment]
Likely SSLCertificateFile

**Comment by brcolow** [comment]
Ah, indeed, I missed that in the readme. thank you.

**Comment by kdubb** [comment]
Seems like we should normalize these.  The SSL parameters are currently the only ones that have dots in the public config parameters.

**Comment by brcolow** [comment]
Yes, it was a bit confusing...(not to defend my lack of RTFM) =)

**Comment by jesperpedersen** [comment]
Are you thinking sslCertificateFile ? I think shorter names for the connection URL plus properties map is ok.

But there is a point in having it similar. Data source configurations tends to be verbose in their properties though.

**Comment by jesperpedersen** [comment]
Also, note that currently it is 'SSL' - not 'Ssl' in the method names. Written as 'SSLBlah' for app servers, not 'sslBlah'

**Comment by brcolow** [comment]
Just figured I'd report that everything with the new SSL + datasources stuff seems to be working for me :)
