### ISSUE TITLE
Strange NullPointerException in QueryListener.rowData(QueryCommandImpl.java:75)

### ISSUE THREAD

**Issue by andreak** [impossibl/pgjdbc-ng#211]
Hi all.

Using driver=0.5 (PostgreSQL 9.4.4), I got this today:

```
Caused by: java.lang.NullPointerException
        at com.impossibl.postgres.protocol.v30.QueryCommandImpl$QueryListener.rowData(QueryCommandImpl.java:75)
        at com.impossibl.postgres.protocol.v30.ProtocolImpl.receiveRowData(ProtocolImpl.java:1000)
        at com.impossibl.postgres.protocol.v30.ProtocolImpl.dispatch(ProtocolImpl.java:790)
        at com.impossibl.postgres.protocol.v30.MessageHandler.channelRead(MessageHandler.java:46)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:339)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:324)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:242)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:339)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:324)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:847)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:111)
```

The strange thing is that restarting the app 2-3 times made the error go away, with no traces in PG-logs.

Any idea what may have caused this?

Thanks.

**Comment by jesperpedersen** [comment]
Could you try pgjdbc-ng 0.6 with Netty 4.0.32+ to see if the problem is still there ?

If so, we would need to look at the query sent, and see why that causes the NPE.

Thanks.

**Comment by andreak** [comment]
This is unfortunately not so easy as I've only seen this problem once (today) and it only manifested itself 2-3 times in production, where we don't log queries. After restarting the app (a webapp in Tomcat using the tomcat-jdbc pool) 2-3 times it went away.

I'm not familiar with the code-path, do you see any reason why the code in question (QueryCommandImpl.java:75, resultBatch or resultBatch.fields) can be null?

Thanks.

**Comment by andreak** [comment]
I've debugged this and it seems to be caused by an OOME.
Closing issue.
