### ISSUE TITLE
Failing unit test? testKillConnection(com.impossibl.postgres.jdbc.ConnectionTest)

### ISSUE THREAD

**Issue by dstipp** [impossibl/pgjdbc-ng#216]
Is anyone else seeing this failure?

```
Tests run: 12, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 3.86 sec <<< FAILURE! - in com.impossibl.postgres.jdbc.ConnectionTest
testKillConnection(com.impossibl.postgres.jdbc.ConnectionTest)  Time elapsed: 0.144 sec  <<< ERROR!
com.impossibl.postgres.jdbc.PGSQLSimpleException: must be superuser to signal other server processes
    at com.impossibl.postgres.jdbc.ErrorUtils.makeSQLException(ErrorUtils.java:159)
    at com.impossibl.postgres.jdbc.ErrorUtils.makeSQLException(ErrorUtils.java:136)
    at com.impossibl.postgres.jdbc.PGConnectionImpl.execute(PGConnectionImpl.java:442)
    at com.impossibl.postgres.jdbc.PGStatement.executeStatement(PGStatement.java:375)
    at com.impossibl.postgres.jdbc.PGSimpleStatement.execute(PGSimpleStatement.java:105)
    at com.impossibl.postgres.jdbc.PGSimpleStatement.execute(PGSimpleStatement.java:124)
    at com.impossibl.postgres.jdbc.ConnectionTest.testKillConnection(ConnectionTest.java:386)
```

I appear to get it on JDK 7 & 8 on PostgreSQL 9.1 only (passes on 9.2, 9.3, 9.4) and wanted to check if this was isolated to my setup or if others see this as well. (Found in the Travis CI builds running 'mvn -e test' against 441b120)

**Comment by kdubb** [comment]
I don't remember this from my 9.1 days but if it's failing on travis I assume it's a valid bug.

**Comment by dstipp** [comment]
Hm.  I wonder if it might be a PostgreSQL configuration difference on travis between the different versions?  I get something similar running with a local IDE but remote DB.  Will look at configuration differences and see if that nets anything.

**Comment by kdubb** [comment]
Yes, It appears to be a setup difference as the command succeeds on travis for 9.2+. My solution was to skip the test on 9.1 for now.  Not optimal I know but it was all I could muster.

**Comment by kdubb** [comment]
Moving with the times... 9.1 support is dead for us.
