### ISSUE TITLE
getting npe while executing prepared statement 

### ISSUE THREAD

**Issue by abhishekparwal** [impossibl/pgjdbc-ng#252]
```
java.lang.NullPointerException
    at com.impossibl.postgres.jdbc.PGPreparedStatement.executeBatch(PGPreparedStatement.java:378)

```

which points to 

`if (!allowBatchSelects() && resultBatch.command.equals("SELECT")) {
`
using 0.6 version of pgjdbc-ng driver

getting npe while executing prepared statement 

```
insert 
    into
        person
        (id, role) 
    values
        (?, ?)

```

**Comment by rjohnsondev** [comment]
I'm running into this pretty frequently myself, seems pretty random and no idea how to reliably replicate at this point.

**Comment by kdubb** [comment]
Clearly code that reproduces it would be grand.  I'd settle for a stack trace.

**Comment by rjohnsondev** [comment]
Yeah, will continue to dig; I was getting it pretty consistently during a 2-hour import process, and managed to confirm that it's the `command` which is null. The last import worked to completion however and I don't have a full stack trace on hand; the line pasted by abhishekparwal was the only line in the driver itself however. I'm now running the latest code from develop, and have added a couple of additional checks to try and get a better idea of the state of things when that null does creep in.  Will let you know once it happens again and I have more info.

**Comment by rjohnsondev** [comment]
Okay, managed to trigger one after a couple of hours. Here is a full stack trace; this was caught by the addition of:

``` java
          if (resultBatch.command == null) {
            System.out.println("Got a null batch command!");
            Thread.dumpStack();
          }
```

in `PGPreparedStatement.java:377`.

Apologies for the clojure noise:

``` java
Got a null batch command!
java.lang.Exception: Stack trace
    at java.lang.Thread.dumpStack(Thread.java:1329)
    at com.impossibl.postgres.jdbc.PGPreparedStatement.executeBatch(PGPreparedStatement.java:384)
    at clojure.java.jdbc$execute_batch.invokeStatic(jdbc.clj:426)
    at clojure.java.jdbc$execute_batch.invoke(jdbc.clj:419)
    at clojure.java.jdbc$db_do_execute_prepared_statement$fn__769.invoke(jdbc.clj:792)
    at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:637)
    at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:585)
    at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:598)
    at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:585)
    at clojure.java.jdbc$db_do_execute_prepared_statement.invokeStatic(jdbc.clj:791)
    at clojure.java.jdbc$db_do_execute_prepared_statement.invoke(jdbc.clj:778)
    at clojure.java.jdbc$db_do_prepared.invokeStatic(jdbc.clj:814)
    at clojure.java.jdbc$db_do_prepared.invoke(jdbc.clj:795)
    at clojure.java.jdbc$execute_BANG_$execute_helper__806.invoke(jdbc.clj:961)
    at clojure.java.jdbc$execute_BANG_.invokeStatic(jdbc.clj:963)
    at clojure.java.jdbc$execute_BANG_.invoke(jdbc.clj:943)
    at clojure.java.jdbc$execute_BANG_.invokeStatic(jdbc.clj:954)
    at clojure.java.jdbc$execute_BANG_.invoke(jdbc.clj:943)
    at yesql.generate$execute_handler.invokeStatic(generate.clj:76)
    at yesql.generate$execute_handler.invoke(generate.clj:74)
    at yesql.generate$generate_query_fn$real_fn__2137.invoke(generate.clj:120)
    at yesql.generate$generate_query_fn$query_wrapper_fn__2144.invoke(generate.clj:142)
    at clojure.lang.AFn.applyToHelper(AFn.java:156)
    at clojure.lang.AFn.applyTo(AFn.java:144)
    at clojure.lang.AFunction$1.doInvoke(AFunction.java:29)
    at clojure.lang.RestFn.invoke(RestFn.java:421)
    at nbase.ingestor.import$insert_emails$fn__12827.invoke(import.clj:472)
    at nbase.ingestor.import$insert_emails.invokeStatic(import.clj:420)
    at nbase.ingestor.import$insert_emails.invoke(import.clj:415)
    at nbase.ingestor.core$import_eml_seq$fn__15721$fn__15730.invoke(core.clj:276)
    at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:613)
    at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:585)
    at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:598)
    at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:585)
    at nbase.ingestor.core$import_eml_seq$fn__15721.invoke(core.clj:274)
    at nbase.ingestor.core$import_eml_seq.invokeStatic(core.clj:272)
    at nbase.ingestor.core$import_eml_seq.invoke(core.clj:267)
    at nbase.ingestor.core$do_import$fn__15754.invoke(core.clj:340)
    at nbase.ingestor.core$do_import.invokeStatic(core.clj:339)
    at nbase.ingestor.core$do_import.invoke(core.clj:330)
    at nbase.ingestor.core$ingest.invokeStatic(core.clj:431)
    at nbase.ingestor.core$ingest.invoke(core.clj:428)
    at nbase.ingestor.core$main_loop.invokeStatic(core.clj:476)
    at nbase.ingestor.core$main_loop.invoke(core.clj:472)
    at nbase.ingestor.core$_main.invokeStatic(core.clj:525)
    at nbase.ingestor.core$_main.doInvoke(core.clj:521)
    at clojure.lang.RestFn.invoke(RestFn.java:397)
    at clojure.lang.Var.invoke(Var.java:375)
    at user$eval5.invokeStatic(form-init4671133772564503859.clj:1)
    at user$eval5.invoke(form-init4671133772564503859.clj:1)
    at clojure.lang.Compiler.eval(Compiler.java:6927)
    at clojure.lang.Compiler.eval(Compiler.java:6917)
    at clojure.lang.Compiler.load(Compiler.java:7379)
    at clojure.lang.Compiler.loadFile(Compiler.java:7317)
    at clojure.main$load_script.invokeStatic(main.clj:275)
    at clojure.main$init_opt.invokeStatic(main.clj:277)
    at clojure.main$init_opt.invoke(main.clj:277)
    at clojure.main$initialize.invokeStatic(main.clj:308)
    at clojure.main$null_opt.invokeStatic(main.clj:342)
    at clojure.main$null_opt.invoke(main.clj:339)
    at clojure.main$main.invokeStatic(main.clj:421)
    at clojure.main$main.doInvoke(main.clj:384)
    at clojure.lang.RestFn.invoke(RestFn.java:421)
    at clojure.lang.Var.invoke(Var.java:383)
    at clojure.lang.AFn.applyToHelper(AFn.java:156)
    at clojure.lang.Var.applyTo(Var.java:700)
    at clojure.main.main(main.java:37)
```

**Comment by rjohnsondev** [comment]
Okay, so this is where I'm up to; this seems to trigger the npe... very occasionally:

``` java
  @Test
  public void testNullCommandComplete() throws Exception {

    Statement stmt = conn.createStatement();
    stmt.executeUpdate("DROP TABLE IF EXISTS person");
    stmt.close();

    stmt = conn.createStatement();
    stmt.executeUpdate("CREATE TABLE person (id INT PRIMARY KEY, role TEXT)");
    stmt.close();

    PGNotificationListener listener = new PGNotificationListener() {
      @Override
      public void notification(int processId, String channelName, String payload) {
        System.out.println(processId + "-" + channelName + ": " + payload);
      }
    };

    Connection conn3 = TestUtil.openDB();
    ((PGConnectionImpl)conn3).addNotificationListener(listener);

    stmt = conn3.createStatement();
    stmt.executeUpdate("LISTEN person_chan");
    stmt.close();

    Thread thread = new Thread() {
      public void run() {
        try {
          Connection conn2 = TestUtil.openDB();
          for (int x = 0; x < 1000000; x++) {
            Statement stmt1 = conn2.createStatement();
            stmt1.executeUpdate("NOTIFY person_chan, 'this is a massive string which has nothing to do with anything ever'");
            stmt1.close();

            Thread.sleep(50);
          }
          conn2.close();
        }
        catch (Exception err) {
          System.out.println(err);
        }
      }
    };
    thread.start();

    conn.setAutoCommit(false);

    PreparedStatement pstmt = conn.prepareStatement(
        "INSERT INTO person (id, role) VALUES (?, ?)");
    for (int i = 1; i < 100000; ++i) {
      pstmt.setInt(1, i);
      pstmt.setString(2, "" + i);
      pstmt.addBatch();
      pstmt.executeBatch();
      if (i % 1000 == 0) {
        System.out.println(i);
        conn.commit();
      }
    }
    pstmt.close();

    conn.setAutoCommit(true);

    pstmt = conn.prepareStatement("DROP TABLE person");
    pstmt.executeUpdate();
    pstmt.close();
  }
```

Adding this into `protocol/v30/BindExecCommandImpl.java:308` `public List<ResultBatch> getResultBatches() {`:

``` java
    if (resultBatch.command == null) {
      for (StackTraceElement[] value : Thread.getAllStackTraces().values()) {
        for (StackTraceElement ste : value) {
          System.out.println(ste);
        }
        System.out.println("----------");
      }
      System.out.println("Got a null command here");
      System.out.println("Status " + status);
      System.out.println("Status is suspended " + (status == Status.Suspended));
      System.out.println("Error " + error);
      System.out.println("Exception " + exception);
    }

```

Hasn't really revealed anything much more to my eyes:

```
java.lang.Thread.sleep(Native Method)
com.impossibl.postgres.jdbc.PreparedStatementTest$2.run(PreparedStatementTest.java:1340)
----------
----------
java.lang.Object.wait(Native Method)
java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:143)
java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:164)
java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:209)
----------
java.lang.Object.wait(Native Method)
java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:143)
java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:164)
com.impossibl.postgres.jdbc.ThreadedHousekeeper$1.run(ThreadedHousekeeper.java:183)
----------
java.lang.Thread.dumpThreads(Native Method)
java.lang.Thread.getAllStackTraces(Thread.java:1603)
com.impossibl.postgres.protocol.v30.BindExecCommandImpl.getResultBatches(BindExecCommandImpl.java:309)
com.impossibl.postgres.jdbc.PGPreparedStatement.executeBatch(PGPreparedStatement.java:372)
com.impossibl.postgres.jdbc.PreparedStatementTest.testNullCommandComplete(PreparedStatementTest.java:1359)
sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
java.lang.reflect.Method.invoke(Method.java:498)
org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
org.junit.runners.ParentRunner.run(ParentRunner.java:309)
org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:283)
org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:173)
org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:128)
org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
----------
sun.nio.ch.EPollArrayWrapper.epollWait(Native Method)
sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:269)
sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:93)
sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:622)
io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:310)
io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
java.lang.Thread.run(Thread.java:745)
----------
java.lang.Object.wait(Native Method)
java.lang.Object.wait(Object.java:502)
java.lang.ref.Reference.tryHandlePending(Reference.java:191)
java.lang.ref.Reference$ReferenceHandler.run(Reference.java:153)
----------
sun.nio.ch.EPollArrayWrapper.epollWait(Native Method)
sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:269)
sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:93)
sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:622)
io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:310)
io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
java.lang.Thread.run(Thread.java:745)
----------
java.lang.Thread.sleep(Native Method)
io.netty.util.ThreadDeathWatcher$Watcher.run(ThreadDeathWatcher.java:147)
io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
java.lang.Thread.run(Thread.java:745)
----------
Got a null command here
Status Completed
Status is suspended false
Error null
Exception null
```

**Comment by rjohnsondev** [comment]
attached is a rather massive log file with driver logging set to FINEST and the error being thrown.
[errs.txt.gz](https://github.com/impossibl/pgjdbc-ng/files/318424/errs.txt.gz)
[out.txt](https://github.com/impossibl/pgjdbc-ng/files/318423/out.txt)

**Comment by rjohnsondev** [comment]
here is another example, I've added the listener instances to the log output in the hope something anomalous would reveal itself
[errs.txt.gz](https://github.com/impossibl/pgjdbc-ng/files/318506/errs.txt.gz)
[out.txt](https://github.com/impossibl/pgjdbc-ng/files/318507/out.txt)

**Comment by rjohnsondev** [comment]
While I'm not really familiar with the postgres protocol nor pgjdbc's internals, from what I can see in the logs it seems that the server is sending a NO-DATA immediately prior to the COMPLETE for the INSERTs.

As the NO-DATA marks the [listener as completed](https://github.com/impossibl/pgjdbc-ng/blob/develop/src/main/java/com/impossibl/postgres/protocol/v30/BindExecCommandImpl.java#L95) if the observing thread is notified after the NO-DATA but before the COMPLETE is processed (spurious wake-up?), the command will be left null.

Commenting out the completed status on NO-DATA does seem to stop the null pointer exceptions, which supports the theory, although I'm guessing this is unlikely the correct fix.

**Comment by kdubb** [comment]
@rjohnsondev You sir rock! With all the details provided I was able to verify this.

Your fix is actually correct. A `NoData` message from the server is sent in response to the `Describe` command. Since in the `BindExecCommandImpl` the`Describe` command is always a prefix to `Bind`/`Execute` it means the `NoData` message shouldn't ever complete the command series.
