### ISSUE TITLE
IllformedLocaleException getting a connection

### ISSUE THREAD

**Issue by aergul** [impossibl/pgjdbc-ng#271]
We get the following exception with current snapshot of develop branch (a snapshot as of July 10, 2016 does work fine):

```
at java.util.Locale$Builder.setLanguageTag(Locale.java:2426)
at com.impossibl.postgres.system.BasicContext.loadLocale(BasicContext.java:272)
at com.impossibl.postgres.system.BasicContext.init(BasicContext.java:262)
at com.impossibl.postgres.jdbc.PGConnectionImpl.init(PGConnectionImpl.java:247)
at com.impossibl.postgres.jdbc.ConnectionUtil.createConnection(ConnectionUtil.java:182)
at com.impossibl.postgres.jdbc.AbstractDataSource.createConnection(AbstractDataSource.java:747)
at com.impossibl.postgres.jdbc.PGDataSource.getConnection(PGDataSource.java:66)
at com.impossibl.postgres.jdbc.PGDataSource.getConnection(PGDataSource.java:58)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
```

java.util.IllformedLocaleException: java.util.IllformedLocaleException: Invalid subtag: C [at index 0]

Postgres 9.3 running on AWS RDS with pg_settings:
"name";"setting"
"lc_numeric";"C"
"lc_time";"C"

**Comment by kdubb** [comment]
Completely forgot about "C" and "POSIX" locales.

**Comment by kdubb** [comment]
Should be fixed in #275

**Comment by aergul** [comment]
#275 worked great for us, thanks!

**Comment by 543802360** [comment]
hello,we have got the same problem.when i connect the local postgresql ,pgjdbc-ng works fine,but when connect to the remote pgsql,we encounter the problem as follws：
Exception in thread "main" java.util.IllformedLocaleException: Invalid subtag: Chinese (Simplified) [at index 0]
	at java.util.Locale$Builder.setLanguageTag(Locale.java:2311)
	at com.impossibl.postgres.system.BasicContext.loadLocale(BasicContext.java:298)
	at com.impossibl.postgres.system.BasicContext.init(BasicContext.java:273)
	at com.impossibl.postgres.jdbc.PGConnectionImpl.init(PGConnectionImpl.java:251)
	at com.impossibl.postgres.jdbc.ConnectionUtil.createConnection(ConnectionUtil.java:182)
	at com.impossibl.postgres.jdbc.AbstractDataSource.createConnection(AbstractDataSource.java:723)
	at com.impossibl.postgres.jdbc.PGDataSource.getConnection(PGDataSource.java:66)
	at com.impossibl.postgres.jdbc.PGDataSource.getConnection(PGDataSource.java:58)
	at com.notify.tax.xj.ListenNotify.<init>(ListenNotify.java:50)
	at com.notify.tax.xj.main.main(main.java:13)

**Comment by 543802360** [comment]
please help,thank u
