### ISSUE TITLE
pgjdbc-ng 0.6 Array in batch issue

### ISSUE THREAD

**Issue by abishai** [impossibl/pgjdbc-ng#300]
```
CREATE TABLE foo
(
  arr integer[]
)
```
```
		PreparedStatement stmt = connection.prepareStatement("INSERT INTO foo(arr) VALUES (?)");
		stmt.setArray(1, connection.createArrayOf("integer", new Integer[] {1}));
		stmt.addBatch();
		stmt.executeBatch();
		stmt.close();
```

```
Exception in thread "main" java.lang.IllegalArgumentException: Argument is not an array
	at java.lang.reflect.Array.getLength(Native Method)
	at com.impossibl.postgres.system.procs.Arrays$BinEncoder.subLength(Arrays.java:316)
	at com.impossibl.postgres.system.procs.Arrays$BinEncoder.length(Arrays.java:296)
	at com.impossibl.postgres.protocol.v30.ProtocolImpl.lengthOfParams(ProtocolImpl.java:724)
	at com.impossibl.postgres.protocol.v30.ProtocolImpl.writeBind(ProtocolImpl.java:508)
	at com.impossibl.postgres.protocol.v30.BindExecCommandImpl.execute(BindExecCommandImpl.java:319)
	at com.impossibl.postgres.protocol.v30.ProtocolImpl.execute(ProtocolImpl.java:370)
	at com.impossibl.postgres.jdbc.PGConnectionImpl.execute(PGConnectionImpl.java:438)
	at com.impossibl.postgres.jdbc.PGPreparedStatement.executeBatch(PGPreparedStatement.java:368)
```
Looks like I can't execute batch if it has arrays. ```stmt.execute()``` works.

**Comment by kdubb** [comment]
Fixed in #349
