### ISSUE TITLE
Websphere8.5 Postgres driver pgjdbc-ng-0.7-complete.jar Datasource not working with hibernate integration

### ISSUE THREAD

**Issue by nikwan** [impossibl/pgjdbc-ng#312]
Websphere8.5 datasource not working facing exception:

Database version: 9.1
Driver version: pgjdbc-ng-0.7-complete.jar
Hibernate Version: 3.1

At Websphere console **Test connection** get succeeded. But if it access through the hibernate with JNDI call datasource name **jdbc/test_master** it gives below exception

**[3/3/17 11:04:34:722 IST] 00000080 InternalGener I   DSRA8203I: Database product name : PostgreSQL
[3/3/17 11:04:34:722 IST] 00000080 InternalGener I   DSRA8204I: Database product version : 9.1.2
[3/3/17 11:04:34:722 IST] 00000080 InternalGener I   DSRA8205I: JDBC driver name  : PostgreSQL JDBC - NG
[3/3/17 11:04:34:722 IST] 00000080 InternalGener I   DSRA8206I: JDBC driver version  : 0.1.0
[3/3/17 11:04:34:722 IST] 00000080 InternalGener I   DSRA8218I: JDBC driver specification level  : 4.1
[3/3/17 11:04:34:722 IST] 00000080 SystemErr     R 5203 [ORB.thread.pool : 0] WARN org.hibernate.cfg.SettingsFactory - Could not obtain connection to query metadata
[3/3/17 11:04:34:722 IST] 00000080 SystemErr     R java.sql.SQLException: Operation not implemented DSRA0010E: SQL State = null, Error Code = 0
[3/3/17 11:04:34:722 IST] 00000080 SystemErr     R 	at com.impossibl.postgres.jdbc.Exceptions.<clinit>(Exceptions.java:36)
[3/3/17 11:04:34:722 IST] 00000080 SystemErr     R 	at com.impossibl.postgres.jdbc.PGConnectionImpl.getClientInfo(PGConnectionImpl.java:1190)**

hibernate configuration:

`<property name="hibernate.connection.datasource">jdbc/test_master</property>
		<property name="transaction.factory_class">org.hibernate.transaction.CMTTransactionFactory</property>
		<property name="hibernate.transaction.manager_lookup_class">org.hibernate.transaction.WebSphereTransactionManagerLookup</property>`

**Comment by kdubb** [comment]
According to the stack trace this was due to client info not being implemented (even though database meta-data said it did).  Fixed in #360
