### ISSUE TITLE
getBlob error

### ISSUE THREAD

**Issue by guai** [impossibl/pgjdbc-ng#329]
```java
package foo.bar;

import com.impossibl.postgres.jdbc.PGDataSource;
import lombok.Cleanup;
import lombok.SneakyThrows;

import java.sql.Blob;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;

public class Main {
	@SneakyThrows
	public static void main(String[] args) {
		PGDataSource dataSource = new PGDataSource();
		dataSource.setHost("localhost");
		dataSource.setPort(5432);
		dataSource.setDatabase("test");
		dataSource.setUser("postgres");
		dataSource.setPassword("postgres");
		@Cleanup Connection connection = dataSource.getConnection();
		@Cleanup Statement select = connection.createStatement();
		select.execute("SELECT val FROM test where id = 1");
		@Cleanup ResultSet resultSet = select.getResultSet();
		resultSet.next();
		Blob blob = resultSet.getBlob(1);
	}
}
```
with this simple example having table `CREATE TABLE test (id serial primary KEY, val bytea);` with just one row with `id = 1` and some data in `val` gives me:
```
Exception in thread "main" java.sql.SQLException: Coercion from 'com.impossibl.postgres.system.procs.Bytes$BinDecoder$1' to 'java.sql.Blob' is not supported (com.impossibl.postgres.system.procs.Bytes$BinDecoder$1@5167f57d)
	at com.impossibl.postgres.jdbc.SQLTypeUtils.createCoercionException(SQLTypeUtils.java:1177)
	at com.impossibl.postgres.jdbc.SQLTypeUtils.coerceToBlob(SQLTypeUtils.java:732)
	at com.impossibl.postgres.jdbc.PGResultSet.getBlob(PGResultSet.java:860)
	at foo.bar.Main.main(Main.java:26)
```
version `group: 'com.impossibl.pgjdbc-ng', name: 'pgjdbc-ng', version: '0.7.1'`

**Comment by kdubb** [comment]
Fixed in #349
