### ISSUE TITLE
failure with netty-4.1.5.Final in classpath

### ISSUE THREAD

**Issue by yurique** [impossibl/pgjdbc-ng#332]
When there's a non `4.1.8.Final` (`4.1.5.Final` in my case) version of netty on the classpath I'm getting this:

```
[ERROR] Exception in thread "main" com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: Connection Error: java.lang.NoSuchMethodError: io.netty.channel.DefaultChannelId.newInstance()Lio/netty/channel/DefaultChannelId;
[ERROR] 	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:512)
[ERROR] 	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:105)
[ERROR] 	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:71)
...
[ERROR] Caused by: java.sql.SQLException: Connection Error: java.lang.NoSuchMethodError: io.netty.channel.DefaultChannelId.newInstance()Lio/netty/channel/DefaultChannelId;
[ERROR] 	at com.impossibl.postgres.jdbc.ConnectionUtil.createConnection(ConnectionUtil.java:189)
[ERROR] 	at com.impossibl.postgres.jdbc.AbstractDataSource.createConnection(AbstractDataSource.java:723)
[ERROR] 	at com.impossibl.postgres.jdbc.PGDataSource.getConnection(PGDataSource.java:66)
[ERROR] 	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:341)
[ERROR] 	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:506)
[ERROR] 	... 35 more
[ERROR] Caused by: java.io.IOException: java.lang.NoSuchMethodError: io.netty.channel.DefaultChannelId.newInstance()Lio/netty/channel/DefaultChannelId;
[ERROR] 	at com.impossibl.postgres.protocol.v30.ProtocolFactoryImpl.translateConnectionException(ProtocolFactoryImpl.java:291)
[ERROR] 	at com.impossibl.postgres.protocol.v30.ProtocolFactoryImpl.connect(ProtocolFactoryImpl.java:199)
[ERROR] 	at com.impossibl.postgres.protocol.v30.ProtocolFactoryImpl.connect(ProtocolFactoryImpl.java:90)
[ERROR] 	at com.impossibl.postgres.system.BasicContext.<init>(BasicContext.java:146)
[ERROR] 	at com.impossibl.postgres.jdbc.PGConnectionImpl.<init>(PGConnectionImpl.java:196)
[ERROR] 	at com.impossibl.postgres.jdbc.ConnectionUtil.createConnection(ConnectionUtil.java:180)
[ERROR] 	... 39 more
[ERROR] Caused by: java.lang.NoSuchMethodError: io.netty.channel.DefaultChannelId.newInstance()Lio/netty/channel/DefaultChannelId;
[ERROR] 	at io.netty.channel.AbstractChannel.newId(AbstractChannel.java:111)
[ERROR] 	at io.netty.channel.AbstractChannel.<init>(AbstractChannel.java:83)
[ERROR] 	at io.netty.channel.nio.AbstractNioChannel.<init>(AbstractNioChannel.java:84)
[ERROR] 	at io.netty.channel.nio.AbstractNioByteChannel.<init>(AbstractNioByteChannel.java:55)
[ERROR] 	at io.netty.channel.socket.nio.NioSocketChannel.<init>(NioSocketChannel.java:98)
[ERROR] 	at io.netty.channel.socket.nio.NioSocketChannel.<init>(NioSocketChannel.java:88)
[ERROR] 	at io.netty.channel.socket.nio.NioSocketChannel.<init>(NioSocketChannel.java:81)
[ERROR] 	at io.netty.channel.socket.nio.NioSocketChannel.<init>(NioSocketChannel.java:74)
[ERROR] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[ERROR] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[ERROR] 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[ERROR] 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[ERROR] 	at java.lang.Class.newInstance(Class.java:442)
[ERROR] 	at io.netty.channel.ReflectiveChannelFactory.newChannel(ReflectiveChannelFactory.java:39)
[ERROR] 	at io.netty.bootstrap.AbstractBootstrap.initAndRegister(AbstractBootstrap.java:321)
[ERROR] 	at io.netty.bootstrap.Bootstrap.doResolveAndConnect(Bootstrap.java:163)
[ERROR] 	at io.netty.bootstrap.Bootstrap.connect(Bootstrap.java:145)
[ERROR] 	at com.impossibl.postgres.protocol.v30.ProtocolFactoryImpl.connect(ProtocolFactoryImpl.java:101)
[ERROR] 	... 43 more

```
Is this a  binary compatibility issue with `netty` or can this be fixed in `pgjdbc-ng`?

**Comment by He-Pin** [comment]
how about upgrade to newer netty version?

**Comment by yurique** [comment]
@hepin1989, you mean upgrading `pgjdbc-ng` to newer netty? That would work for me :)

But it looks like `pgjdbc-ng` is compiled against 4.1.8 and newer versions have something binary different, so it won't work.

**Comment by yurique** [comment]
It turned out that another lib (async-http-client) included a copy of `io.netty.channel.DefaultChannelId` class in its jar (which was not binary compatible with netty on the classpath). It was rather tricky to spot.

**Comment by moaxcp** [comment]
I just ran into this with upgrading amazon-kinesis-client. Thanks @yurique for pointing me in the right direction!
