### ISSUE TITLE
io.netty.util.internal.OutOfDirectMemoryError

### ISSUE THREAD

**Issue by andreak** [impossibl/pgjdbc-ng#337]
Using 0.7.1 with Pg-10 (also happened with Pg-9.6)

After some time I get this Exception:

```
io.netty.util.internal.OutOfDirectMemoryError: failed to allocate 16777216 byte(s) of direct memory (used: 2097152000, max: 2112618496)
        at io.netty.util.internal.PlatformDependent.incrementMemoryCounter(PlatformDependent.java:624)
        at io.netty.util.internal.PlatformDependent.allocateDirectNoCleaner(PlatformDependent.java:578)
        at io.netty.buffer.PoolArena$DirectArena.allocateDirect(PoolArena.java:718)
        at io.netty.buffer.PoolArena$DirectArena.newChunk(PoolArena.java:707)
        at io.netty.buffer.PoolArena.allocateNormal(PoolArena.java:239)
        at io.netty.buffer.PoolArena.allocate(PoolArena.java:221)
        at io.netty.buffer.PoolArena.allocate(PoolArena.java:141)
        at io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:287)
        at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:179)
        at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:170)
        at io.netty.buffer.AbstractByteBufAllocator.buffer(AbstractByteBufAllocator.java:107)
        at com.impossibl.postgres.protocol.v30.BindExecCommandImpl.execute(BindExecCommandImpl.java:243)
        at com.impossibl.postgres.protocol.v30.ProtocolImpl.execute(ProtocolImpl.java:371)
        at com.impossibl.postgres.jdbc.PGConnectionImpl.execute(PGConnectionImpl.java:443)
        at com.impossibl.postgres.jdbc.PGStatement.executeStatement(PGStatement.java:380)
        at com.impossibl.postgres.jdbc.PGPreparedStatement.execute(PGPreparedStatement.java:273)
        at com.impossibl.postgres.jdbc.PGPreparedStatement.executeQuery(PGPreparedStatement.java:289)
        at com.impossibl.postgres.jdbc.PGPreparedStatement.executeQuery(PGPreparedStatement.java:96)
        at sun.reflect.GeneratedMethodAccessor130.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.tomcat.jdbc.pool.interceptor.AbstractQueryReport$StatementProxy.invoke(AbstractQueryReport.java:210)
        at com.sun.proxy.$Proxy105.executeQuery(Unknown Source)
        at sun.reflect.GeneratedMethodAccessor130.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:114)
        at com.sun.proxy.$Proxy105.executeQuery(Unknown Source)
        at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.executeSelect(DatabaseAccessor.java:1009)
        at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.basicExecuteCall(DatabaseAccessor.java:644)
        at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.executeCall(DatabaseAccessor.java:560)
        at org.eclipse.persistence.internal.sessions.AbstractSession.basicExecuteCall(AbstractSession.java:2056)
        at org.eclipse.persistence.sessions.server.ClientSession.executeCall(ClientSession.java:306)
        at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.executeCall(DatasourceCallQueryMechanism.java:242)
        at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.executeCall(DatasourceCallQueryMechanism.java:228)
        at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.executeSelectCall(DatasourceCallQueryMechanism.java:299)
        at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.selectAllRows(DatasourceCallQueryMechanism.java:694)
        at org.eclipse.persistence.internal.queries.ExpressionQueryMechanism.selectAllRowsFromTable(ExpressionQueryMechanism.java:2740)
        at org.eclipse.persistence.internal.queries.ExpressionQueryMechanism.selectAllRows(ExpressionQueryMechanism.java:2693)
        at org.eclipse.persistence.queries.ReadAllQuery.executeObjectLevelReadQuery(ReadAllQuery.java:559)
        at org.eclipse.persistence.queries.ObjectLevelReadQuery.executeDatabaseQuery(ObjectLevelReadQuery.java:1175)
        at org.eclipse.persistence.queries.DatabaseQuery.execute(DatabaseQuery.java:904)
        at org.eclipse.persistence.queries.ObjectLevelReadQuery.execute(ObjectLevelReadQuery.java:1134)
        at org.eclipse.persistence.queries.ReadAllQuery.execute(ReadAllQuery.java:460)
        at org.eclipse.persistence.queries.ObjectLevelReadQuery.executeInUnitOfWork(ObjectLevelReadQuery.java:1222)
        at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.internalExecuteQuery(UnitOfWorkImpl.java:2896)
        at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1857)
        at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1839)
        at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1804)
        at org.eclipse.persistence.internal.jpa.QueryImpl.executeReadQuery(QueryImpl.java:258)
        at org.eclipse.persistence.internal.jpa.QueryImpl.getSingleResult(QueryImpl.java:521)
        at org.eclipse.persistence.internal.jpa.EJBQueryImpl.getSingleResult(EJBQueryImpl.java:400)
        at org.scala_libs.jpa.ScalaQuery.$anonfun$findOne$1(ScalaQuery.scala:42)
        at org.scala_libs.jpa.Utils$.findToOption(Utils.scala:26)
        at org.scala_libs.jpa.ScalaQuery.findOne(ScalaQuery.scala:42)
        at no.officenet.origo.email.domain.service.repository.EmailAccountRepository.findAccount(EmailAccountRepository.scala:189)
```

Any ideas how to debug this?

**Comment by kdubb** [comment]
Am I wrong or does it look like you're just "out of memory"?  Or are you wondering why it's trying to allocation 16mb?

**Comment by andreak** [comment]
The VM has 4GB physical memory + 4GB swap.

At the time of the exception the system had allocated 2.9GB swap, and the JVM was operating with -Xmx2g. The JVM had allocated 1.3 GB heap (according to munin).

So what's happening is that jetty is trying to allocate 16MB when it already has used 2097152000 (2000MB) and max is 2112618496 (2014.75MB)?

I don't really know why jetty thinks it has used 2gb when the "used heap" is at 1.3...

I really don't understand what's going on here and why jetty's managing memory this way.... Care to explain?

Thanks.

**Comment by andreak** [comment]
I got it again just now and according to VisualVM I have plenty free heap-space.

Size: 2,886,291,456 B

Used: 1,597,561,648 B

Max: 3,221,225,472 B
![image](https://user-images.githubusercontent.com/321577/33653474-8740ca6e-da6d-11e7-87c2-d6dc0c340c15.png)


```
2017-12-06 09:15:19,881 ERROR [ajp-nio-8089-exec-3162] - [origo] [F6953029334814WZRIR]  TransactionInterceptor         - Application exception overridden by rollback error
io.netty.util.internal.OutOfDirectMemoryError: failed to allocate 16777216 byte(s) of direct memory (used: 3170893824, max: 3186360320)
        at io.netty.util.internal.PlatformDependent.incrementMemoryCounter(PlatformDependent.java:624)
        at io.netty.util.internal.PlatformDependent.allocateDirectNoCleaner(PlatformDependent.java:578)
        at io.netty.buffer.PoolArena$DirectArena.allocateDirect(PoolArena.java:718)
        at io.netty.buffer.PoolArena$DirectArena.newChunk(PoolArena.java:707)
        at io.netty.buffer.PoolArena.allocateNormal(PoolArena.java:239)
        at io.netty.buffer.PoolArena.allocate(PoolArena.java:221)
        at io.netty.buffer.PoolArena.reallocate(PoolArena.java:381)
        at io.netty.buffer.PooledByteBuf.capacity(PooledByteBuf.java:122)
        at io.netty.buffer.AbstractByteBuf.ensureWritable0(AbstractByteBuf.java:284)
        at io.netty.buffer.AbstractByteBuf.ensureWritable(AbstractByteBuf.java:265)
        at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1036)
        at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1044)
        at com.impossibl.postgres.utils.ByteBufs.writeCString(ByteBufs.java:52)
        at com.impossibl.postgres.utils.ByteBufs.writeCString(ByteBufs.java:47)
        at com.impossibl.postgres.protocol.v30.ProtocolImpl.writeParse(ProtocolImpl.java:482)
        at com.impossibl.postgres.protocol.v30.PrepareCommandImpl.execute(PrepareCommandImpl.java:151)
        at com.impossibl.postgres.protocol.v30.ProtocolImpl.execute(ProtocolImpl.java:371)
        at com.impossibl.postgres.jdbc.PGConnectionImpl.execute(PGConnectionImpl.java:443)
        at com.impossibl.postgres.jdbc.PGPreparedStatement$1.call(PGPreparedStatement.java:209)
        at com.impossibl.postgres.jdbc.PGPreparedStatement$1.call(PGPreparedStatement.java:199)
        at com.impossibl.postgres.jdbc.PGConnectionImpl.getCachedStatement(PGConnectionImpl.java:1363)
        at com.impossibl.postgres.jdbc.PGPreparedStatement.parseIfNeeded(PGPreparedStatement.java:199)
        at com.impossibl.postgres.jdbc.PGPreparedStatement.execute(PGPreparedStatement.java:268)
        at com.impossibl.postgres.jdbc.PGPreparedStatement.executeQuery(PGPreparedStatement.java:289)
        at com.impossibl.postgres.jdbc.PGPreparedStatement.executeQuery(PGPreparedStatement.java:96)
        at sun.reflect.GeneratedMethodAccessor131.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.tomcat.jdbc.pool.interceptor.AbstractQueryReport$StatementProxy.invoke(AbstractQueryReport.java:210)
        at com.sun.proxy.$Proxy99.executeQuery(Unknown Source)
        at sun.reflect.GeneratedMethodAccessor131.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:114)
        at com.sun.proxy.$Proxy99.executeQuery(Unknown Source)
        at org.springframework.jdbc.core.JdbcTemplate$1.doInPreparedStatement(JdbcTemplate.java:692)
        at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:633)
        at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:684)
        at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:716)
        at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:726)
        at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:776)
        at no.officenet.util.search.QueryGeneratorFactory.query(QueryGeneratorFactory.java:41)
        at no.officenet.origo.report.calendar.CalendarReportService.$anonfun$getCalendarEntryOldList$3(CalendarReportServiceImpl.scala:45)
```

**Comment by andreak** [comment]
After we've moved lots of java.sql.Blobs out of the database I haven't seen this in over a year, so I'm closing it.
