### ISSUE TITLE
getJavaCompatibleLocale should use Locale.ENGLISH when mapping PostgreSQL Locales

### ISSUE THREAD

**Issue by sergej-reiser** [impossibl/pgjdbc-ng#397]
Similar issue to #287

Trying to use pgjdbc-ng we are experiencing an issue on german windows machines and PostgreSQL-9.6.

Consider the following example:
```java
@Test
public void connect() throws Exception {
    String url = "jdbc:pgsql://localhost:5432/test_DB";
    String user = "postgres";
    String password = "postgres";

    try (Connection connection = DriverManager.getConnection(url, user, password)) {
        System.out.println(connection.getMetaData().getDatabaseProductVersion());
    }
}
```
When trying to connect to the postgres instance running with default locales (German_Germany.1252) the following exception occurs:
```java
java.util.IllformedLocaleException: Ill-formed region: Germany [at index 0]

	at java.util.Locale$Builder.setRegion(Locale.java:2495)
	at com.impossibl.postgres.system.BasicContext.loadLocale(BasicContext.java:345)
	at com.impossibl.postgres.system.BasicContext.init(BasicContext.java:318)
	at com.impossibl.postgres.jdbc.PGDirectConnection.init(PGDirectConnection.java:276)
	at com.impossibl.postgres.jdbc.ConnectionUtil.createConnection(ConnectionUtil.java:205)
	at com.impossibl.postgres.jdbc.ConnectionUtil.createConnection(ConnectionUtil.java:165)
	at com.impossibl.postgres.jdbc.PGDriver.connect(PGDriver.java:113)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
```

Upon further investigation we found that [Locales.getJavaCompatibleLocale()](https://github.com/impossibl/pgjdbc-ng/blob/develop/driver/src/main/java/com/impossibl/postgres/utils/Locales.java) fails to map German_Germany.1252 to the de_DE Locale.

```java
public static String getJavaCompatibleLocale(String localeSpec) {
    String[] parts = localeSpec.split("\\.");
    if (parts.length == 1)
        return localeSpec;
    parts = parts[0].split("_");
    if (parts.length != 2) {
        return localeSpec;
    }
    // Manual search for locale...
    for (Locale locale : Locale.getAvailableLocales()) {
        if (locale.getDisplayLanguage().equals(parts[0]) && locale.getDisplayCountry().equals(parts[1])) {
            return locale.toString();
        }
    }
    return localeSpec;
}
```
The mapping fails because of locale.getDisplayLanguage() and locale.getDisplayCountry() are being invoked without a specific Locale, which leads to java using the default locale. The default locale on our machines is Locale.GERMANY.
locale.getDisplayLanguage would return **Deutsch** and locale.getDisplayCountry would return **Deutschland**. Obviously not matching **German** and **Germany**.

The method invocations should look like this:
```java
public static String getJavaCompatibleLocale(String localeSpec) {
    String[] parts = localeSpec.split("\\.");
    if (parts.length == 1)
        return localeSpec;
    parts = parts[0].split("_");
    if (parts.length != 2) {
        return localeSpec;
    }
    // Manual search for locale...
    for (Locale locale : Locale.getAvailableLocales()) {
        // Use Locale.ENGLISH 
        if (locale.getDisplayLanguage(Locale.ENGLISH).equals(parts[0]) && locale.getDisplayCountry(Locale.ENGLISH).equals(parts[1])) {
            return locale.toString();
        }
    }
    return localeSpec;
}
```
The only way for us to use pgjdbc-ng right now is to temporarily switch our default Locale like so:
```java
@Test
public void connect() throws Exception {
    String url = "jdbc:pgsql://localhost:5432/test_DB";
    String user = "postgres";
    String password = "postgres";

    Locale previousDefault = Locale.getDefault();
    Locale.setDefault(Locale.ENGLISH);
    try (Connection connection = DriverManager.getConnection(url, user, password)) {
        System.out.println(connection.getMetaData().getDatabaseProductVersion());
    }
    Locale.setDefault(previousDefault);
}
```

**Comment by mlaffargue** [comment]
Same problem here with :
```
java.util.IllformedLocaleException: Ill-formed region: United States [at index 0]
        at java.util.Locale$Builder.setRegion(Locale.java:2495)
        at com.impossibl.postgres.system.BasicContext.loadLocale(BasicContext.java:345)
        at com.impossibl.postgres.system.BasicContext.init(BasicContext.java:318)
        at com.impossibl.postgres.jdbc.PGDirectConnection.init(PGDirectConnection.java:276)
        at com.impossibl.postgres.jdbc.ConnectionUtil.createConnection(ConnectionUtil.java:205)
        at com.impossibl.postgres.jdbc.ConnectionUtil.createConnection(ConnectionUtil.java:165)
        at com.impossibl.postgres.jdbc.AbstractDataSource.createConnection(AbstractDataSource.java:122)
        at com.impossibl.postgres.jdbc.PGDataSource.getConnection(PGDataSource.java:71)
        at com.impossibl.postgres.jdbc.PGDataSource.getConnection(PGDataSource.java:63)
```

**Comment by andreasboos** [comment]
+1.
Same problem here too: My java locale is "português" and postgres DB is "Portuguese".

Can you try to use default SO locale when this issue happen and just warning in console?

I resolve here, for while, just putting the default SO locale over a try/catch into BasicContext class.

**Comment by ltruppe** [comment]
Same problem here with 
`java.util.IllformedLocaleException: Ill-formed region: Austria [at index 0]`

**Comment by kdubb** [comment]
@sergej-reiser @mlaffargue @andreasboos @ltruppe Apologies all for this issue lingering for so long. This truly slipped passed me.

#431 _should_ fix this.  I have limited windows access and your help testing the fixes would be much appreciated!
