### ISSUE TITLE
readObject return null instead of NullPointerException

### ISSUE THREAD

**Issue by tlf30** [impossibl/pgjdbc-ng#406]
I think that it would be better for `readObject` to return a null value when the object in the database is null instead of a `NullPointerException` when using a `SQLData` UDT. 

This would fix UDTs generated from the UDT generator from crashing when reading a UDT that contains a UDT that is null.

**Comment by kdubb** [comment]
@tlf30 Can you provide more information? Stack trace?

**Comment by tlf30** [comment]
@kdubb yes, here is the stack trace (I have censored some of the classpath)
```
java.lang.NullPointerException
        at com.impossibl.postgres.system.procs.Records$BinDecoder.decodeValue(Records.java:139)
        at com.impossibl.postgres.system.procs.BaseBinaryDecoder.decode(BaseDecoders.java:79)
        at com.impossibl.postgres.system.procs.BaseBinaryDecoder.decode(BaseDecoders.java:49)
        at com.impossibl.postgres.jdbc.PGSQLInput.getNextAttributeObject(PGSQLInput.java:116)
        at com.impossibl.postgres.jdbc.PGSQLInput.getNextAttributeValue(PGSQLInput.java:106)
        at com.impossibl.postgres.jdbc.PGSQLInput.readObject(PGSQLInput.java:214)
        at io.tlf.mappings.generated.Chara.readSQL(Chara.java:75)
        at com.impossibl.postgres.system.procs.Records.convertOutput(Records.java:109)
        at com.impossibl.postgres.system.procs.Records$BinDecoder.decodeValue(Records.java:164)
        at com.impossibl.postgres.system.procs.BaseBinaryDecoder.decode(BaseDecoders.java:79)
        at com.impossibl.postgres.system.procs.BaseBinaryDecoder.decode(BaseDecoders.java:49)
        at com.impossibl.postgres.protocol.v30.BufferRowData.getField(BufferRowData.java:157)
        at com.impossibl.postgres.jdbc.ListScroller.getRowField(PGResultSet.java:1858)
        at com.impossibl.postgres.jdbc.PGResultSet.getObj(PGResultSet.java:301)
        at com.impossibl.postgres.jdbc.PGResultSet.getVal(PGResultSet.java:294)
        at com.impossibl.postgres.jdbc.PGResultSet.getObject(PGResultSet.java:891)
        at com.impossibl.postgres.jdbc.PGResultSet.getObject(PGResultSet.java:1092)
        at io.tlf.SqlSerializer.load(SqlSerializer.java:198)
```
The field that throws the npe on read is a UDT inside the Chara UDT, and in the database has a null value.

**Comment by tlf30** [comment]
This is a test project showing the NPE: https://github.com/tlf30/pgjdbc-ng-test2
This is the NPE from the test project:
```
java.lang.NullPointerException
	at com.impossibl.postgres.system.procs.Records$BinDecoder.decodeValue(Records.java:139)
	at com.impossibl.postgres.system.procs.BaseBinaryDecoder.decode(BaseDecoders.java:79)
	at com.impossibl.postgres.system.procs.BaseBinaryDecoder.decode(BaseDecoders.java:49)
	at com.impossibl.postgres.jdbc.PGSQLInput.getNextAttributeObject(PGSQLInput.java:116)
	at com.impossibl.postgres.jdbc.PGSQLInput.getNextAttributeValue(PGSQLInput.java:106)
	at com.impossibl.postgres.jdbc.PGSQLInput.readObject(PGSQLInput.java:214)
	at io.tlf.sqltest2.Chara.readSQL(Chara.java:74)
	at com.impossibl.postgres.system.procs.Records.convertOutput(Records.java:109)
	at com.impossibl.postgres.system.procs.Records$BinDecoder.decodeValue(Records.java:164)
	at com.impossibl.postgres.system.procs.BaseBinaryDecoder.decode(BaseDecoders.java:79)
	at com.impossibl.postgres.system.procs.BaseBinaryDecoder.decode(BaseDecoders.java:49)
	at com.impossibl.postgres.protocol.v30.BufferRowData.getField(BufferRowData.java:157)
	at com.impossibl.postgres.jdbc.ListScroller.getRowField(PGResultSet.java:1858)
	at com.impossibl.postgres.jdbc.PGResultSet.getObj(PGResultSet.java:301)
	at com.impossibl.postgres.jdbc.PGResultSet.getVal(PGResultSet.java:294)
	at com.impossibl.postgres.jdbc.PGResultSet.getObject(PGResultSet.java:891)
	at com.impossibl.postgres.jdbc.PGResultSet.getObject(PGResultSet.java:1092)
	at io.tlf.sqltest2.Main.test2(Main.java:76)
	at io.tlf.sqltest2.Main.main(Main.java:24)
```

**Comment by kdubb** [comment]
Please try PR #408.  I've added a UDT handling test that is very similar to your example, with an array of UDTs; it tests for nulls in the array and null values in the UDT.

**Comment by tlf30** [comment]
Thanks, I'll do that in a couple hours when I get back to my desk.

**Comment by tlf30** [comment]
@kdubb is it not possible to build on windows? I attempted to build the branch and got this error: 
```
 ./gradlew clean assemble
Downloading https://services.gradle.org/distributions/gradle-5.4-all.zip
..............................................................................................................................

Welcome to Gradle 5.4!

Here are the highlights of this release:
 - Run builds with JDK12
 - New API for Incremental Tasks
 - Updates to native projects, including Swift 5 support

For more details see https://docs.gradle.org/5.4/release-notes.html

Starting a Gradle Daemon (subsequent builds will be faster)


FAILURE: Build failed with an exception.

* Where:
Script 'C:\Users\Trevor\Desktop\outside\pgjdbc-ng\driver\src\build\testing.gradle.kts' line: 150

* What went wrong:
View 'posix' not available

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.4/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 3m 30s
```

Perhaps I am doing something wrong, I do not use gradle very often.

**Comment by kdubb** [comment]
I have no idea, building and testing on Windows is currently not maintained. I'm pretty sure it will but may require tweaks.  

FYI, the error you are experiencing is with a file permissions check done in `testing.gradle.kts` that looks for the correct posix permissions;  I would imagine that's the only platform dependent item currently in the build.

**Comment by tlf30** [comment]
Ah OK. I am moving over to a Linux box.

**Comment by kdubb** [comment]
@tlf30 Update? I'm ready to merge #408 but I'd like to ensure it completely fixes your issues.

**Comment by tlf30** [comment]
@kdubb I have had issues building on linux. For some reason the artifact will not deploy to my local maven repo.

**Comment by tlf30** [comment]
@kdubb sorry for the late delay. I was able to test the snapshot last night. The previous errors are gone. Nulls seem to be working correctly. I noticed a different issue that has to do with the types, but I do not have time right now to look into it. Once I figure out what is going on, I will build a test case and open an issue for it. 

Thank you for all the hard work, I really appreciate it!
