### ISSUE TITLE
PGSQLSimpleException: wrong data type: 2249, expected 143374

### ISSUE THREAD

**Issue by tlf30** [impossibl/pgjdbc-ng#414]
Hello @kdubb 
Sorry for the very large delay in getting back to trouble shooting the UDTs. I was working on a job up in the arctic circle (not much internet up there 😛 ). 

Using my test2 test case (https://github.com/tlf30/pgjdbc-ng-test2), I am running into this issue:

```
**** Running Test2
Connecting to db...
Reading test data
Writing test data
com.impossibl.postgres.jdbc.PGSQLSimpleException: wrong data type: 2249, expected 143374
	at com.impossibl.postgres.jdbc.ErrorUtils.makeSQLException(ErrorUtils.java:197)
	at com.impossibl.postgres.jdbc.ErrorUtils.makeSQLException(ErrorUtils.java:174)
	at com.impossibl.postgres.jdbc.ErrorUtils.makeSQLException(ErrorUtils.java:161)
	at com.impossibl.postgres.jdbc.PGDirectConnection.execute(PGDirectConnection.java:508)
	at com.impossibl.postgres.jdbc.PGDirectConnection.executeTimed(PGDirectConnection.java:516)
	at com.impossibl.postgres.jdbc.PreparedQuery.executeStatement(PreparedQuery.java:119)
	at com.impossibl.postgres.jdbc.PreparedQuery.execute(PreparedQuery.java:186)
	at com.impossibl.postgres.jdbc.PGStatement.executeStatement(PGStatement.java:373)
	at com.impossibl.postgres.jdbc.PGPreparedStatement.execute(PGPreparedStatement.java:339)
	at com.impossibl.postgres.jdbc.PGPreparedStatement.executeLargeUpdate(PGPreparedStatement.java:373)
	at com.impossibl.postgres.jdbc.PGPreparedStatement.executeUpdate(PGPreparedStatement.java:367)
	at io.tlf.sqltest2.Main.test2(Main.java:88)
	at io.tlf.sqltest2.Main.main(Main.java:24)
```

This is utilizing the UDT Generator. 

Any help would be very appreciated. 

Thank you,
Trevor Flynn

**Comment by tlf30** [comment]
After some investigation, still not sure what is broken, but type `143374` is the `L` type in the database script. 
Some digging, the generator is producing in Chara.java:
```
@Override
  public void writeSQL(SQLOutput out) throws SQLException {
    out.writeObject(this.a, JDBCType.ARRAY);
    out.writeObject(this.b, JDBCType.ARRAY);
    out.writeObject(this.c, JDBCType.ARRAY);
    out.writeObject(this.d, PGType.RECORD);
    out.writeObject(this.e, PGType.RECORD);
  }
```

But this works:
```
@Override
  public void writeSQL(SQLOutput out) throws SQLException {
    out.writeObject(this.a, JDBCType.ARRAY);
    out.writeObject(this.b, JDBCType.ARRAY);
    out.writeObject(this.c, JDBCType.ARRAY);
    out.writeObject(this.d);
    out.writeObject(this.e);
  }
```

Except in this case the `e` var here is null and I get this error:
```
com.impossibl.postgres.jdbc.PGSQLSimpleException: wrong data type: 25, expected 143383
	at com.impossibl.postgres.jdbc.ErrorUtils.makeSQLException(ErrorUtils.java:197)
	at com.impossibl.postgres.jdbc.ErrorUtils.makeSQLException(ErrorUtils.java:174)
	at com.impossibl.postgres.jdbc.ErrorUtils.makeSQLException(ErrorUtils.java:161)
	at com.impossibl.postgres.jdbc.PGDirectConnection.execute(PGDirectConnection.java:508)
	at com.impossibl.postgres.jdbc.PGDirectConnection.executeTimed(PGDirectConnection.java:516)
	at com.impossibl.postgres.jdbc.PreparedQuery.executeStatement(PreparedQuery.java:119)
	at com.impossibl.postgres.jdbc.PreparedQuery.execute(PreparedQuery.java:186)
	at com.impossibl.postgres.jdbc.PGStatement.executeStatement(PGStatement.java:373)
	at com.impossibl.postgres.jdbc.PGPreparedStatement.execute(PGPreparedStatement.java:339)
	at com.impossibl.postgres.jdbc.PGPreparedStatement.executeLargeUpdate(PGPreparedStatement.java:373)
	at com.impossibl.postgres.jdbc.PGPreparedStatement.executeUpdate(PGPreparedStatement.java:367)
	at io.tlf.sqltest2.Main.test2(Main.java:88)
	at io.tlf.sqltest2.Main.main(Main.java:24)
```
Which indicates that it thinks it got a `TEXT` type instead of NULL?

**Comment by tlf30** [comment]
@kdubb have you had a chance to take a look into this? I am working from home for the next two weeks and would like to get this resolved on my end before I go back. 

Thanks for the help,
Trevor Flynn

**Comment by kdubb** [comment]
I've finally had a chance to look at this... it was _another_ UDT generation issue.

#435 Uses generates specific types to fix the issue and it is working using your test project!

**Comment by tlf30** [comment]
You are awesome, thank you!
I will test it out in the morning, I really appreciate your time working on this!

**Comment by tlf30** [comment]
That fix worked great, thank you!
