### ISSUE TITLE
Can't even connect: IllformedLocaleException: Invalid subtag: C 

### ISSUE THREAD

**Issue by rnikander** [impossibl/pgjdbc-ng#416]
I compiled and installed PostgreSQL 12 beta from source using the default instructions. I can't connect. The exception is below, along with data that it appears to be choking on.

    SELECT name, setting FROM pg_settings WHERE name IN ('lc_numeric', 'lc_time')
    mydb-> ;
        name    | setting 
    ------------+---------
     lc_numeric | C.UTF-8
     lc_time    | C.UTF-8

    Exception in thread "main" java.util.IllformedLocaleException: Invalid subtag: C [at index 0]
	at java.base/java.util.Locale$Builder.setLanguageTag(Locale.java:2566)
	at com.impossibl.postgres.system.BasicContext.loadLocale(BasicContext.java:345)
	at com.impossibl.postgres.system.BasicContext.init(BasicContext.java:318)
	at com.impossibl.postgres.jdbc.PGDirectConnection.init(PGDirectConnection.java:276)
	at com.impossibl.postgres.jdbc.ConnectionUtil.createConnection(ConnectionUtil.java:205)
	at com.impossibl.postgres.jdbc.ConnectionUtil.createConnection(ConnectionUtil.java:165)
	at com.impossibl.postgres.jdbc.PGDriver.connect(PGDriver.java:113)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)

**Comment by kdubb** [comment]
Fixed in #431
