### ISSUE TITLE
Null Pointer exception when write a customized type in an array

### ISSUE THREAD

**Issue by lyguan** [impossibl/pgjdbc-ng#419]
Hi, I define a composite type in postgresql, and mapping a java object which implements SQLData
`public class ReportDataPointSQLData implements SQLData {
@override
public void readSQL(SQLInput stream, String typeName) throws SQLException {

    this.obj.setDataPointId(stream.readString());
    this.obj.setValue(stream.readBigDecimal());
    this.obj.setCalcMark(stream.readInt());
}

@Override
public void writeSQL(SQLOutput stream) throws SQLException {

    if (this.obj.getDataPointId() != null) {
        stream.writeString(this.obj.getDataPointId());
    } else {
        stream.writeObject(null, JDBCType.VARCHAR);
    }
    if (this.obj.getValue() != null) {
        stream.writeBigDecimal(this.obj.getValue());
    } else {
        stream.writeObject(null, JDBCType.DECIMAL);
    }
    if (this.obj.getCalcMark() != null) {
        stream.writeInt(this.obj.getCalcMark());
    } else {
        stream.writeObject(null, JDBCType.INTEGER);
    }
}
}`
sometimes, there are some column which's value is null. I am trying insert an array which it's item's type is ReportDataPointSQLData. But it throw a exception;
java.lang.NullPointerException
at com.impossibl.postgres.system.procs.BaseBinaryDecoder.decode(BaseDecoders.java:76)
at com.impossibl.postgres.system.procs.BaseBinaryDecoder.decode(BaseDecoders.java:49)
at com.impossibl.postgres.jdbc.PGSQLInput.getNextAttributeObject(PGSQLInput.java:116)
at com.impossibl.postgres.jdbc.PGSQLInput.getNextAttributeValue(PGSQLInput.java:106)
at com.impossibl.postgres.jdbc.PGSQLInput.readInt(PGSQLInput.java:149)
at com.morningstar.equitydata.lib.postgresql.model.ReportDataPointSQLData.readSQL(ReportDataPointSQLData.java:38)
at com.impossibl.postgres.system.procs.Records.convertOutput(Records.java:109)
at com.impossibl.postgres.system.procs.Records$BinDecoder.decodeValue(Records.java:164)
at com.impossibl.postgres.system.procs.BaseBinaryDecoder.decode(BaseDecoders.java:79)
at com.impossibl.postgres.system.procs.BaseBinaryDecoder.decode(BaseDecoders.java:49)
at com.impossibl.postgres.jdbc.PGBuffersArray.getArray(PGBuffersArray.java:221)
at com.impossibl.postgres.jdbc.PGBuffersArray.getArray(PGBuffersArray.java:168)
at com.impossibl.postgres.jdbc.PGArray.getArray(PGArray.java:91)
at com.impossibl.postgres.system.procs.Arrays$BinEncoder.encodeValue(Arrays.java:153)
at com.impossibl.postgres.system.procs.BaseBinaryEncoder.encode(BaseEncoders.java:59)
at com.impossibl.postgres.system.procs.BaseBinaryEncoder.encode(BaseEncoders.java:41)
at com.impossibl.postgres.jdbc.PGPreparedStatement.set(PGPreparedStatement.java:191)
at com.impossibl.postgres.jdbc.PGPreparedStatement.set(PGPreparedStatement.java:161)
at com.impossibl.postgres.jdbc.PGPreparedStatement.setArray(PGPreparedStatement.java:837)

Could any one can tell me what should i do?

**Comment by tlf30** [comment]
There are currently some issues with using UDTs, @kdubb has been very responsive on getting them fixed. I also currently have a lb UDT issue open. I recommend using the UDTGenerator for creating the object wrappers.

**Comment by lyguan** [comment]
@tlf30 Hi, Thanks for your reply. How to use "UDT Generator for creating the object wrappers"? Is that means let the java object implements interface "SQLData"?

**Comment by kdubb** [comment]
@lyguan I believe this error is due to an issue. that @tlf30 and I worked through a while ago. Try your code with the driver built from HEAD of `develop`; or wait until the next release.
