### ISSUE TITLE
Unable to create initial connections of pool: java.text.ParseException: Unparseable number: "-1"

### ISSUE THREAD

**Issue by andreak** [impossibl/pgjdbc-ng#420]
I'm getting the following Exception with version 0.8.2, jdk-11

The jdbc-URL is: jdbc:pgsql://localhost:5433/andreak

It seems this query is run in the backend:
```sql
SELECT t.oid,
       typname,
       typlen,
       typtype,
       typcategory,
       typdelim,
       typrelid,
       typelem,
       typarray,
       typinput::text,
       typoutput::text,
       typreceive::text,
       typsend::text,
       typmodin::text,
       typmodout::text,
       typalign,
       n.nspname,
       typbasetype,
       typtypmod,
       typnotnull,
       pg_catalog.pg_get_expr(typdefaultbin, 0),
       rngsubtype
FROM pg_catalog.pg_type t
         LEFT JOIN pg_catalog.pg_namespace n ON (t.typnamespace = n.oid)
         LEFT JOIN pg_catalog.pg_range r ON (t.oid = r.rngtypid)
WHERE typrelid = 0;
```

```
jul. 01, 2019 2:38:06 P.M. org.apache.tomcat.jdbc.pool.ConnectionPool init
SEVERE: Unable to create initial connections of pool.
com.impossibl.postgres.jdbc.PGSQLSimpleException: Connection Error: java.text.ParseException: Unparseable number: "-1"
        at com.impossibl.postgres.jdbc.ErrorUtils.makeSQLException(ErrorUtils.java:137)
        at com.impossibl.postgres.jdbc.ConnectionUtil.createConnection(ConnectionUtil.java:212)
        at com.impossibl.postgres.jdbc.ConnectionUtil.createConnection(ConnectionUtil.java:165)
        at com.impossibl.postgres.jdbc.PGDriver.connect(PGDriver.java:113)
        at org.apache.tomcat.jdbc.pool.PooledConnection.connectUsingDriver(PooledConnection.java:310)
        at org.apache.tomcat.jdbc.pool.PooledConnection.connect(PooledConnection.java:203)
        at org.apache.tomcat.jdbc.pool.ConnectionPool.createConnection(ConnectionPool.java:735)
        at org.apache.tomcat.jdbc.pool.ConnectionPool.borrowConnection(ConnectionPool.java:667)
        at org.apache.tomcat.jdbc.pool.ConnectionPool.init(ConnectionPool.java:482)
        at org.apache.tomcat.jdbc.pool.ConnectionPool.<init>(ConnectionPool.java:154)
        at org.apache.tomcat.jdbc.pool.DataSourceProxy.pCreatePool(DataSourceProxy.java:118)
        at org.apache.tomcat.jdbc.pool.DataSourceProxy.createPool(DataSourceProxy.java:107)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.__invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:45009)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:45012)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeCustomInitMethod(AbstractAutowireCapableBeanFactory.java:1903)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1846)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1774)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:593)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
        at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:367)
        at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveValueIfNecessary(BeanDefinitionValueResolver.java:110)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyPropertyValues(AbstractAutowireCapableBeanFactory.java:1681)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1433)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:592)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
        at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1105)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:867)
        at org.springframework.context.support.AbstractApplicationContext.__refresh(AbstractApplicationContext.java:549)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:41010)
        at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:400)
        at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:291)
        at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:103)
        at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4939)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5434)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1559)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1549)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.io.IOException: java.text.ParseException: Unparseable number: "-1"
        at com.impossibl.postgres.system.procs.BaseTextDecoder.decode(BaseDecoders.java:221)
        at com.impossibl.postgres.system.procs.BaseTextDecoder.decode(BaseDecoders.java:196)
        at com.impossibl.postgres.protocol.v30.BufferRowData.getField(BufferRowData.java:145)
        at com.impossibl.postgres.system.tables.Table.getFieldOfRow(Table.java:86)
        at com.impossibl.postgres.system.tables.PGTypeTable$Row.load(PGTypeTable.java:115)
        at com.impossibl.postgres.system.tables.PGTypeTable.createRow(PGTypeTable.java:272)
        at com.impossibl.postgres.system.tables.PGTypeTable.createRow(PGTypeTable.java:46)
        at com.impossibl.postgres.system.tables.Tables.convertRows(Tables.java:83)
        at com.impossibl.postgres.system.tables.Table.query(Table.java:79)
        at com.impossibl.postgres.system.BasicContext.lambda$loadTypes$1(BasicContext.java:380)
        at com.impossibl.postgres.types.SharedRegistry.seed(SharedRegistry.java:291)
        at com.impossibl.postgres.system.BasicContext.loadTypes(BasicContext.java:428)
        at com.impossibl.postgres.system.BasicContext.init(BasicContext.java:314)
        at com.impossibl.postgres.jdbc.PGDirectConnection.init(PGDirectConnection.java:276)
        at com.impossibl.postgres.jdbc.ConnectionUtil.createConnection(ConnectionUtil.java:205)
        ... 51 more
Caused by: java.text.ParseException: Unparseable number: "-1"
        at java.base/java.text.NumberFormat.parse(NumberFormat.java:431)
        at com.impossibl.postgres.system.procs.Int4s$TxtDecoder.decodeNativeValue(Int4s.java:96)
        at com.impossibl.postgres.system.procs.Int4s$TxtDecoder.decodeNativeValue(Int4s.java:83)
        at com.impossibl.postgres.system.procs.AutoConvertingTextDecoder.decodeValue(BaseDecoders.java:287)
        at com.impossibl.postgres.system.procs.BaseTextDecoder.decode(BaseDecoders.java:218)
        ... 65 more
```

Any hints on what's causing this?

**Comment by andreak** [comment]
Ping!
(sorry for being the squeaky wheel, but I really whish I'd be able to use newer driver-versions)
IDEA is also reporting such error when trying to connect using its DataSource-config.
Am I the only one not being able to connect to PG using 0.8.2 driver?
I've tried with v11 and 12beta3, neither work...

Any feedback appreciated:-)

**Comment by kdubb** [comment]
PostgreSQL 9.4-11 are covered by current testing on jdk8-11.  So it unless I'm mistaken it must be something unique to your installation.

First glance from the stack trace would say your system catalog is different than "usual". Although I can't explain why `NumberFormat` cannot parse `-1`.

**Comment by andreak** [comment]
The following simple program produces the error:
```java
public class PgJdbcNgTester {
	public static void main(String... args) throws Exception {
		java.util.Properties props = new java.util.Properties();
		props.setProperty("user", "andreak");
		props.setProperty("password", "fish");
		java.sql.DriverManager.getConnection("jdbc:pgsql://localhost:5432/visena", props);
	}
}
```
I compile with:
```
javac -cp /home/andreak/.m2/repository/com/impossibl/pgjdbc-ng/pgjdbc-ng/0.8.2/pgjdbc-ng-0.8.2-all.jar:. PgJdbcNgTester.java
```
And run with:
```
java -cp /home/andreak/.m2/repository/com/impossibl/pgjdbc-ng/pgjdbc-ng/0.8.2/pgjdbc-ng-0.8.2-all.jar:. PgJdbcNgTester
```
Gives the exception:
```
Exception in thread "main" com.impossibl.postgres.jdbc.PGSQLSimpleException: Connection Error: java.text.ParseException: Unparseable number: "-1"
        at com.impossibl.postgres.jdbc.ErrorUtils.makeSQLException(ErrorUtils.java:137)
        at com.impossibl.postgres.jdbc.ConnectionUtil.createConnection(ConnectionUtil.java:212)
        at com.impossibl.postgres.jdbc.ConnectionUtil.createConnection(ConnectionUtil.java:165)
        at com.impossibl.postgres.jdbc.PGDriver.connect(PGDriver.java:113)
        at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
        at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:189)
        at PgJdbcNgTester.main(PgJdbcNgTester.java:6)
Caused by: java.io.IOException: java.text.ParseException: Unparseable number: "-1"
        at com.impossibl.postgres.system.procs.BaseTextDecoder.decode(BaseDecoders.java:221)
        at com.impossibl.postgres.system.procs.BaseTextDecoder.decode(BaseDecoders.java:196)
        at com.impossibl.postgres.protocol.v30.BufferRowData.getField(BufferRowData.java:145)
        at com.impossibl.postgres.system.tables.Table.getFieldOfRow(Table.java:86)
        at com.impossibl.postgres.system.tables.PGTypeTable$Row.load(PGTypeTable.java:115)
        at com.impossibl.postgres.system.tables.PGTypeTable.createRow(PGTypeTable.java:272)
        at com.impossibl.postgres.system.tables.PGTypeTable.createRow(PGTypeTable.java:46)
        at com.impossibl.postgres.system.tables.Tables.convertRows(Tables.java:83)
        at com.impossibl.postgres.system.tables.Table.query(Table.java:79)
        at com.impossibl.postgres.system.BasicContext.lambda$loadTypes$1(BasicContext.java:380)
        at com.impossibl.postgres.types.SharedRegistry.seed(SharedRegistry.java:291)
        at com.impossibl.postgres.system.BasicContext.loadTypes(BasicContext.java:428)
        at com.impossibl.postgres.system.BasicContext.init(BasicContext.java:314)
        at com.impossibl.postgres.jdbc.PGDirectConnection.init(PGDirectConnection.java:276)
        at com.impossibl.postgres.jdbc.ConnectionUtil.createConnection(ConnectionUtil.java:205)
        ... 5 more
Caused by: java.text.ParseException: Unparseable number: "-1"
        at java.base/java.text.NumberFormat.parse(NumberFormat.java:431)
        at com.impossibl.postgres.system.procs.Int4s$TxtDecoder.decodeNativeValue(Int4s.java:96)
        at com.impossibl.postgres.system.procs.Int4s$TxtDecoder.decodeNativeValue(Int4s.java:83)
        at com.impossibl.postgres.system.procs.AutoConvertingTextDecoder.decodeValue(BaseDecoders.java:287)
        at com.impossibl.postgres.system.procs.BaseTextDecoder.decode(BaseDecoders.java:218)
        ... 19 more
```

I've stepped thru this in debugger and it seems ```BasicContext.integerFormatter```, when initialized in ```init()```, returns an instance with ```negativePrefix="−"``` ('−'8722, not '-'45), so when ```loadTypes()``` is called it barfs because it cannot recognize "-1" because it has '-'45 as negativePrefix, not '−'8722.

If I change the value from '−'8722 to '-'45 in the debugger then everything proceeds ok.

Could it be anything with my locale-settings?
```
$ locale
LANG=nb_NO.UTF-8
LANGUAGE=en_US
LC_CTYPE="nb_NO.UTF-8"
LC_NUMERIC=nb_NO.UTF-8
LC_TIME=nb_NO.UTF-8
LC_COLLATE="nb_NO.UTF-8"
LC_MONETARY=nb_NO.UTF-8
LC_MESSAGES="nb_NO.UTF-8"
LC_PAPER=nb_NO.UTF-8
LC_NAME=nb_NO.UTF-8
LC_ADDRESS=nb_NO.UTF-8
LC_TELEPHONE=nb_NO.UTF-8
LC_MEASUREMENT=nb_NO.UTF-8
LC_IDENTIFICATION=nb_NO.UTF-8
LC_ALL=
```

**Comment by andreak** [comment]
It's strange that this works with the same JVM/env with version 0.7.1 of the driver

**Comment by andreak** [comment]
In ```BasicContext.init```(line 305); If I change from ```NumberFormat.getIntegerInstance()``` to ```NumberFormat.getIntegerInstance(Locale.US)``` then negativePrefix="-"(45), but when calling ```NumberFormat.getIntegerInstance(Locale.getDefault())``` then it returns negativePrefix="−"(8722)

I'm sure this must bite others using non-English locales?

**Comment by kdubb** [comment]
Seems clear it must be a problem... I'm also thinking that `-` (45) is probably the dominant negation character in a lot of locales and therefore passes unnoticed.

**Comment by kdubb** [comment]
https://github.com/impossibl/pgjdbc-ng/blob/632d1268f26b9582eaa49bede28a8eba991e3a0d/driver/src/main/java/com/impossibl/postgres/system/BasicContext.java#L358 
The `integerFormatter` is replaced with one loaded from the server's locale. Which is what the driver needs to match in the long run.  Is that also setting it to `nb_NO`?

**Comment by kdubb** [comment]
Actually, I don't believe it's ever getting to the line I referenced... `loadLocale` is called after `loadTypes`.

**Comment by andreak** [comment]
From what I can see it seems like PG doesn't return String-representations of numbers locale-compatible with how Java's ```NumberFormat.getIntegerInstance()``` parses them and always uses '-'(45) as negativePrefix. Maybe revert to use Integer.valueOf (like 0.7.1, right?) instead of integerFormatter?

Anyway, isn't it a bit strange to initialize ```integerFormatter``` in ```BasicContext.init``` _then_ to re-initialize it to a locale-aware ```NumberFormat```-instance in ```BasicContext.loadLocale()```?

BTW, ```decimalFormatter``` and ```currencyFormatter``` also suffer from the same issue

**Comment by kdubb** [comment]
The idea was to initialize it to "something sensible" prior to getting an authoritative response from Postgres.  Ideally Postgres's startup packet would report lc_numeric and the like so we wouldn't have to query it for that information.  I'm gonna look into it and see if that's the case or not.

**Comment by andreak** [comment]
(Sorry, didn't see you replies before I reloaded the page as Github didn't push them...)

The locale-query: ```SELECT name, setting FROM pg_settings WHERE name IN ('lc_numeric', 'lc_time');``` returns:
```
+------------+-------------+
|    name    |   setting   |
+------------+-------------+
| lc_numeric | nb_NO.UTF-8 |
| lc_time    | nb_NO.UTF-8 |
+------------+-------------+
(2 rows)
```
So even the locales match, it doesn't help....

**Comment by andreak** [comment]
... but you're correct that ```loadLocale``` is never called because it dies in ```loadTypes```

**Comment by andreak** [comment]
...so I'm guessing that even if PG _is_ reporting the value of ```lc_numeric``` in some way the output will _still_ be wrong (not match what ```NumberFormat.getIntegerInstance()``` expects), because it doesn't respect the "negativePrefix"-part obviously. It will still (is still) sending '-'(45) and not '−'(8722), meaning ```NumberFormat.getIntegerInstance()``` will never be able to parse PG's negative values, IIUC.

**Comment by kdubb** [comment]
https://www.postgresql.org/docs/current/runtime-config-client.html#GUC-LC-NUMERIC

I'm a bit confused at the moment.  It seems lc_numeric and the like have nothing to do with SQL output but I'm not sure what it all means in totality.  The docs give the example `to_char`, does that mean that unless I am calling an `lc_numeric` "enabled" function on the server, all output are 'C' locale?

**Comment by andreak** [comment]
Yes - I guess. All I've seen until now confirms this - that no output is default "lc_numeric aware" unless you use explicit formatting-functions.

**Comment by andreak** [comment]
Even in ```to_char``` it seems negative-prefix isn't respected/used:
```
andreak@[local]:5432 11.5 andreak=# show lc_numeric;
+-------------+
| lc_numeric  |
+-------------+
| nb_NO.UTF-8 |
+-------------+
(1 row)

andreak@[local]:5432 11.5 andreak=# select to_char(0 - 2, '9');
+---------+
| to_char |
+---------+
| -2      |
+---------+
(1 row)
```
all with '-'(45)

**Comment by kdubb** [comment]
Yeah... it seems to completely ignore it without `to_char` and `to_number`.

```sql
test=# set lc_numeric='fr_FR';

test=# select to_number('13,4', '99D9');
 to_number 
-----------
      13.4
(1 row)

test=# select to_char(13.4, '99D9');
 to_char 
---------
  13,4
(1 row)

test=# select 13,4::float4;
 ?column? | float4 
----------+--------
       13 |      4
(1 row)
```

**Comment by kdubb** [comment]
Haha we're on the same page here.  So it's clear I need to always use 'C' when parsing server output.

Now, when parsing text from the application, should that assume C as well? Or should that use the JVM locale?

**Comment by andreak** [comment]
I'm really not sure... When will this become an issue, when data is sent as String and not Integer? I've never had any issues with this with previous PG-drivers so "do what they do", maybe:-)

**Comment by andreak** [comment]
But, even ```to_char``` and ```to_number``` both seem to completely ignore '−'(8722) as negative prefix for lc_numeric='nb_NO.UTF-8'

**Comment by andreak** [comment]
See Tom Lane's answer here: https://www.postgresql.org/message-id/29374.1569452008%40sss.pgh.pa.us

**Comment by kdubb** [comment]
Good to have a (somewhat) definitive answer.

Unfortunately, postgres has text and binary formats for wire transmission and JDBC has text conversions rules.  This isn't an issue when using binary but when using text it's seeming that it must all be done in 'C'.  So when somebody calls 'PreparedStatement.setString()' for a 'float4' column (a required JDBC conversion) the mismatched locales come into play.

This driver generally uses binary for everything it can but there are instances where it is required to fallback to text.  I just need to figure out how to handle the mismatched locales (on the driver side) and then I'll now how to proceed with a correct fix for all of this.

I guess the solution could be as simple as _locking_ the locales to 'C' and then requiring all input to the driver (through JDBC) to be in the 'C' locale as well. I'm not yet completely sure the solution is that easy.

**Comment by kdubb** [comment]
Unhelpfully it seems to follow some locales...
```sql
test=# set lc_monetary='fr_FR';
test=# select 13.4::money;
  money   
----------
 13,40 Eu
(1 row)
```

**Comment by andreak** [comment]
Yea... Tom specifically confirmed only for LC_NUMERIC.

**Comment by davecramer** [comment]
Money is probably the worst example as it should have remained deprecated
and tossed in the bin a long time ago.

If you store 100 USD in there and then change the locale to somewhere in
Europe the output will be formatted as Euros, but the value remains the
same.

My .02 CAD :)

Dave

**Comment by andreak** [comment]
Ha ha! That's a great "feature":-)

**Comment by kdubb** [comment]
@davecramer Yeah it seemed really odd that it's not only adjust numeric formatting but adding the currency specifier.

Does mainline driver concern itself with 'JVM' -> 'C' locale translation when handling JDBC coercion from `setString` to numeric values for text protocol? Or does it just require all JDBC API input to be in 'C' locale as well?

**Comment by davecramer** [comment]
On Thu, 26 Sep 2019 at 11:17, Kevin Wooten <notifications@github.com> wrote:

> @davecramer <https://github.com/davecramer> Yeah it seemed really odd
> that it's not only adjust numeric formatting but adding the currency
> specifier.
>

Ya Money is FUBAR

> Does mainline driver concern itself with 'JVM' -> 'C' locale translation
> when handling JDBC coercion from setString to numeric values for text
> protocol? Or does it just require all JDBC API input to be in 'C' locale as
> well?
>
No we don't take locale into account, but should, Need more tuits

 Dave Cramer

>

**Comment by kdubb** [comment]
@andreak I'll be posting a PR soon. I think we're ahead of the game because all of the text encoders/decoders are respecting a locale... it's just the wrong locale in a lot of instances when parsing server output. We need client formatters, representing the JVM locale, and server formatters locked to the 'C' locale and that should be all that's needed. Also, travis configurations running in a few locales is clearly needed.

**Comment by andreak** [comment]
Keep on rocking!

**Comment by kdubb** [comment]
@andreak #431 Should do the trick.  It respects Java's locale when parsing input from JDBC but uses C/POSIX compatible parsing for all data going to or coming from PostgreSQL. Give it a shot and let me know!

**Comment by andreak** [comment]
Seems to work, but I'm getting an unexpected Exception in code that worked with 0.7.1, related to UDT. I'll report that in another issue.

**Comment by andreak** [comment]
Reported new issue here #432
