### ISSUE TITLE
Incorrect reporting of un-leaked result-set

### ISSUE THREAD

**Issue by brettwooldridge** [impossibl/pgjdbc-ng#44]
During testing of the XA DataSource, after an unclean shutdown, upon startup I encounter this error.  I don't think it is related to the XA DataSource in general.  This error was no encountered with the old "official" pgjdbc driver.

Dec 02, 2013 1:56:10 AM com.impossibl.postgres.jdbc.ThreadedHousekeeper$HousekeeperReference cleanup
WARNING: cleaning up leaked result-set
java.lang.Exception
    at com.impossibl.postgres.jdbc.PGResultSet$Cleanup.<init>(PGResultSet.java:127)
    at com.impossibl.postgres.jdbc.PGResultSet.<init>(PGResultSet.java:200)
    at com.impossibl.postgres.jdbc.PGResultSet.<init>(PGResultSet.java:183)
    at com.impossibl.postgres.jdbc.PGStatement.createResultSet(PGStatement.java:380)
    at com.impossibl.postgres.jdbc.PGStatement.createResultSet(PGStatement.java:375)
    at com.impossibl.postgres.jdbc.PGStatement.getGeneratedKeys(PGStatement.java:611)
    at com.impossibl.postgres.jdbc.PGStatementDelegator.getGeneratedKeys(PGStatementDelegator.java:191)
    at com.impossibl.postgres.jdbc.PGStatementDelegator.getGeneratedKeys(PGStatementDelegator.java:191)
    at bitronix.tm.resource.jdbc.proxy.PreparedStatementJavaProxy.getGeneratedKeys(PreparedStatementJavaProxy.java:110)
    at org.sansorm.internal.OrmWriter.setParamsExecuteClose(OrmWriter.java:353)
    at org.sansorm.internal.OrmWriter.updateObject(OrmWriter.java:203)
    at org.sansorm.OrmElf.updateObject(OrmElf.java:279)
    at org.ziptie.provider.compliance.ComplianceProvider$6.execute(ComplianceProvider.java:413)
    at org.ziptie.provider.compliance.ComplianceProvider$6.execute(ComplianceProvider.java:400)
    at org.sansorm.SqlClosure.execute(SqlClosure.java:130)
    at org.ziptie.provider.compliance.ComplianceProvider.updateRuleSet(ComplianceProvider.java:399)
    at org.ziptie.provider.compliance.ComplianceProvider.saveRuleSet(ComplianceProvider.java:56)
    at org.ziptie.provider.compliance.internal.ComplianceActivator.scanPolicies(ComplianceActivator.java:101)
    at org.ziptie.provider.compliance.internal.ComplianceActivator.start(ComplianceActivator.java:50)
    at org.eclipse.osgi.framework.internal.core.BundleContextImpl$1.run(BundleContextImpl.java:711)
    at java.security.AccessController.doPrivileged(Native Method)
    at org.eclipse.osgi.framework.internal.core.BundleContextImpl.startActivator(BundleContextImpl.java:702)
    at org.eclipse.osgi.framework.internal.core.BundleContextImpl.start(BundleContextImpl.java:683)
    at org.eclipse.osgi.framework.internal.core.BundleHost.startWorker(BundleHost.java:381)
    at org.eclipse.osgi.framework.internal.core.AbstractBundle.start(AbstractBundle.java:300)
    at org.eclipse.osgi.framework.internal.core.AbstractBundle.start(AbstractBundle.java:292)
    at org.ziptie.crates.CrateStarterElf.start(CrateStarterElf.java:282)
    at org.ziptie.crates.CrateStarterElf.activateBundles(CrateStarterElf.java:193)
    at org.ziptie.crates.CrateStarterElf.activateBundles(CrateStarterElf.java:219)
    at org.ziptie.zap.bootstrap.ZApplication.start(ZApplication.java:193)
    at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:110)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:79)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:353)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:180)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.main(EclipseStarter.java:151)

**Comment by kdubb** [comment]
FYI, this is not an exception per-se but a warning about the leaked ResultSet.  This just means the result set wasn't closed properly.  The exception part is just an easy way to provide the stack trace for the allocation of the ResultSet that was leaked.

**Comment by brettwooldridge** [comment]
OK, I did find the code in question:

```
ResultSet generatedKeys = stmt.getGeneratedKeys();
if (generatedKeys != null && generatedKeys.next()) {
    introspected.set(target, idColumn, generatedKeys.getObject(1));
    generatedKeys.close();
}

stmt.close();
```

Clearly, there is a path where `generatedKeys` might not be closed ... if `generatedKeys` is not `null` but does not have `next()`.  However, I think the leak warning is a little bit "aggressive" in that the JavaDoc for `ResultSet` states:

_A ResultSet object is automatically closed when the Statement object that generated it is closed, re-executed, or used to retrieve the next result from a sequence of multiple results._

And similarly the JavaDoc for `Statement.close()` says:

_When a Statement object is closed, its current ResultSet object, if one exists, is also closed._

The latter is particularly meaningful in Java 7, because Statement implements `AutoClosable`.  This is an example [directly from Oracle](http://docs.oracle.com/javase/tutorial/essential/exceptions/tryResourceClose.html)

```
try (Statement stmt = con.createStatement()) {
    ResultSet rs = stmt.executeQuery(query);

    while (rs.next()) {
        String coffeeName = rs.getString("COF_NAME");
        int supplierID = rs.getInt("SUP_ID");
        float price = rs.getFloat("PRICE");
        int sales = rs.getInt("SALES");
        int total = rs.getInt("TOTAL");

        System.out.println(coffeeName + ", " + supplierID + ", " + 
                           price + ", " + sales + ", " + total);
    }
} catch (SQLException e) {
    JDBCTutorialUtilities.printSQLException(e);
}
```

The `ResultSet` in this case is closed automatically when the _try with resources_ statement closes the `Statement`.  In my case, the code in question is a 3rd party library relative to my application.

**Comment by kdubb** [comment]
In 7c6180dceb0c1a1e638ef22d4222eebdf64a4227 I cleaned up the stack traces and now report them without mentioning an exception.  This should clarify that these are just warnings.

Still investigating how a closed statement can report a leaked result set.  In my testing your excerpt from the bitronix code is cleaned up correctly.

**Comment by kdubb** [comment]
I believe in f0a18301b687824465fd99210684b63d3df4c8bf @jesperpedersen fixed the leak related to generated keys
