### ISSUE TITLE
Unhandled message: Z @ com.impossibl.postgres.protocol.v30.PrepareRequest$Handler

### ISSUE THREAD

**Issue by andreak** [impossibl/pgjdbc-ng#457]
I got this in the logs today, no idea why...

```
Caused by: java.lang.IllegalStateException: Unhandled message: Z @ com.impossibl.postgres.protocol.v30.PrepareRequest$Handler
        at com.impossibl.postgres.protocol.v30.MessageDispatchHandler.dispatch(MessageDispatchHandler.java:214)
        at com.impossibl.postgres.protocol.v30.MessageDispatchHandler.channelRead(MessageDispatchHandler.java:149)
        at com.impossibl.shadow.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
        at com.impossibl.shadow.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
        at com.impossibl.shadow.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
        at com.impossibl.shadow.io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:328)
        at com.impossibl.shadow.io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:302)
        at com.impossibl.shadow.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
        at com.impossibl.shadow.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
        at com.impossibl.shadow.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
        at com.impossibl.shadow.io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1422)
        at com.impossibl.shadow.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
        at com.impossibl.shadow.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
        at com.impossibl.shadow.io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:931)
        at com.impossibl.shadow.io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
        at com.impossibl.shadow.io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:700)
        at com.impossibl.shadow.io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:635)
        at com.impossibl.shadow.io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:552)
        at com.impossibl.shadow.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:514)
        at com.impossibl.shadow.io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1044)
        at com.impossibl.shadow.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at java.lang.Thread.run(Thread.java:830)
```

**Comment by kdubb** [comment]
This implies the message dispatching engine is "out of sync" with the stream of messages (PostgreSQL is essentially an asynchronous FIFO queue).

More information is needed before I can help.  What versions (driver, server, etc) and platform? Any idea on the workload (query types, statement types [prepared or not], batch, etc)?

**Comment by andreak** [comment]
PG: 12.0
OS: Ubuntu Linux eoan
JDK: 13.0.1
Driver: 0.8.3
I see (in debugger) that `parseAndDispatch` returns null (action == null) on line 210 in `MessageDispatchHandler`

The thread running is "PG-JDBC I/O" which seems to be in a separate thread from the thread issuing the query.

If I stop at breakpoint at MessageDispatchHandler:214, the last queries in the PG-logs are:
```
2019-11-06 15:49:52.490 CET [13160-107] andreak@rev DETAIL:  parameters: $1 = '449', $2 = '890903'
2019-11-06 15:49:52.491 CET [13160-108] andreak@rev LOG:  execute cached-8de6a6be: select nextval('origo_email_message_property_entity_id_seq')
2019-11-06 15:49:52.493 CET [13160-109] andreak@rev LOG:  execute cached-9cfbbf3e: SELECT DISTINCT t1.entity_id, t1.part_type, t1.filename, t1.part_index, t1.mimetype, t1.raw_content_filename, t1.size, t1.uid, t1.version, t1.message_id, t1.parent_id, t1.charset, t1.string_content, t1.multipart_type, t0.entity_id, t0.header_index, t0.header_name, t0.version, t0.part_id FROM origo_email_part t1 LEFT OUTER JOIN origo_email_part_header t0 ON (t0.part_id = t1.entity_id) WHERE (t1.message_id = $1) ORDER BY t1.part_index ASC
2019-11-06 15:49:52.493 CET [13160-110] andreak@rev DETAIL:  parameters: $1 = '890903'
2019-11-06 15:49:52.494 CET [13160-111] andreak@rev LOG:  execute cached-65948c5b: SELECT DISTINCT t1.entity_id, t1.part_type, t1.filename, t1.part_index, t1.mimetype, t1.raw_content_filename, t1.size, t1.uid, t1.version, t1.message_id, t1.parent_id, t1.charset, t1.string_content, t1.multipart_type, t0.entity_id, t0.header_index, t0.header_name, t0.version, t0.part_id FROM origo_email_part t1 LEFT OUTER JOIN origo_email_part_header t0 ON (t0.part_id = t1.entity_id) WHERE (t1.parent_id = $1) ORDER BY t1.part_index ASC
2019-11-06 15:49:52.494 CET [13160-112] andreak@rev DETAIL:  parameters: $1 = '873369'
2019-11-06 15:49:52.963 CET [13160-113] andreak@rev ERROR:  prepared statement "cached-3fcfe755" already exists
2019-11-06 15:49:52.963 CET [13160-115] andreak@rev ERROR:  current transaction is aborted, commands ignored until end of transaction block
2019-11-06 15:49:52.963 CET [13160-116] andreak@rev STATEMENT:  select lo_close($1)
2019-11-06 15:49:52.963 CET [13160-117] andreak@rev LOG:  execute TR: ROLLBACK
2019-11-06 15:49:52.963 CET [13160-118] andreak@rev ERROR:  prepared statement "cached-3fcfe755" already exists
```

But grepping doesn't reveal any previous such cached statements, only the errors:
```
$ grep "cached-3fcfe755" /var/log/postgresql/postgresql-12-main.log
2019-11-06 15:41:53.144 CET [13160-52] andreak@rev ERROR:  prepared statement "cached-3fcfe755" already exists
2019-11-06 15:49:52.963 CET [13160-113] andreak@rev ERROR:  prepared statement "cached-3fcfe755" already exists
2019-11-06 15:49:52.963 CET [13160-118] andreak@rev ERROR:  prepared statement "cached-3fcfe755" already exists
```

**Comment by andreak** [comment]
FWIW; I dumped the database from production to my laptop to reproduce and the same happens locally on my laptop, so it's 100% reproducable.

**Comment by andreak** [comment]
From the application-log:
```
[EL Warning]: 2019-11-06 15:49:52.817--UnitOfWork(1182293696)--com.impossibl.shadow.io.netty.handler.codec.TooLongFrameException: Adjusted frame length exceeds 20971520: 29028470 - discarded
nov. 06, 2019 3:56:24 P.M. com.impossibl.postgres.protocol.v30.ServerConnectionFactory$DefaultHandler error
WARNING: prepared statement "cached-3fcfe755" already exists
nov. 06, 2019 3:56:24 P.M. com.impossibl.postgres.protocol.v30.ServerConnectionFactory$DefaultHandler error
WARNING: current transaction is aborted, commands ignored until end of transaction block
[EL Warning]: 2019-11-06 15:56:24.285--ClientSession(1984511191)--java.lang.IllegalStateException: Unhandled message: C @ com.impossibl.postgres.protocol.v30.PrepareRequest$Handler
```

**Comment by kdubb** [comment]
I think we have two different issues...

First is the root cause which appears to be a cache collision; it's trying to prepare a statement that the server believes is already prepared which automatically terminates the current transaction.

Second, the driver is _not prepared for this scenario_.  The scenario I refer to is actually that the transaction has terminated at the point at which it does.  `MessageDispatchHandler` is effectively saying a `ready for query` message ('Z') couldn't possibly happen here and I don't know what to do.

I'm working on some reproduction cases. Feel free to attach anymore information you find.

**Comment by kdubb** [comment]
@andreak Seeing the the line beginning `execute cached-65948c5b`... Is the application attempting to open a blob after this?

Another thing that would be good is an SQL trace from the driver leading up to and following the error. http://impossibl.github.io/pgjdbc-ng/docs/0.8.3/user-guide/#tracing-sql

**Comment by andreak** [comment]
The application-thread starts with reading a SQL-Blob (using PG's OID, ie. LargeObject), from a custom queue-impl, and parses it to an rfc-822 email-object and stores it using JPA.

**Comment by andreak** [comment]
...the strange thing is that the application does this all the time, without error. This email-blob it's trying to parse in this case is larger than normal, 38MB, maybe that affects stuff....

**Comment by andreak** [comment]
I'll turn on some tracing and provide the logs

**Comment by andreak** [comment]
...I'm swamped with "customer-work" and won't have time for this until this weekend...

**Comment by andreak** [comment]
Here are pg's log and sql.trace
[postgresql.log](https://github.com/impossibl/pgjdbc-ng/files/3819845/postgresql.log)
[sql-trace.log](https://github.com/impossibl/pgjdbc-ng/files/3819846/sql-trace.log)

**Comment by andreak** [comment]
It seems EclipseLink is sending a `SELECT 1` as "pingSQL" when trying to cope with the original exception. Then the `ERROR:  prepared statement "cached-3fcfe755" already exists` is thrown, maskin the original-exception, which is:

```
Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.7.5.v20191016-ea124dd158): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: java.sql.SQLException: com.impossibl.shadow.io.netty.handler.codec.TooLongFrameException: Adjusted frame length exceeds 20971520: 29028403 - discarded
Error Code: 0
Call: SELECT entity_id, part_type, filename, part_index, mimetype, raw_content_filename, size, uid, version, message_id, parent_id, multipart_type, charset, string_content FROM origo_email_part WHERE (parent_id = ?) ORDER BY part_index ASC
        bind => [1 parameter bound]
Query: ReadAllQuery(name="children" referenceClass=EmailPart sql="SELECT entity_id, part_type, filename, part_index, mimetype, raw_content_filename, size, uid, version, message_id, parent_id, multipart_type, charset, string_content FROM origo_email_part WHERE (parent_id = ?) ORDER BY part_index ASC")
        at org.eclipse.persistence.exceptions.DatabaseException.sqlException(DatabaseException.java:342)
        at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.processExceptionForCommError(DatabaseAccessor.java:1650)
        at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.basicExecuteCall(DatabaseAccessor.java:683)
        at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.executeCall(DatabaseAccessor.java:567)
        at org.eclipse.persistence.internal.sessions.AbstractSession.basicExecuteCall(AbstractSession.java:2099)
        at org.eclipse.persistence.sessions.server.ClientSession.executeCall(ClientSession.java:313)
        at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.executeCall(DatasourceCallQueryMechanism.java:275)
        at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.executeCall(DatasourceCallQueryMechanism.java:261)
        at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.executeSelectCall(DatasourceCallQueryMechanism.java:332)
        at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.selectAllRows(DatasourceCallQueryMechanism.java:744)
        at org.eclipse.persistence.internal.queries.ExpressionQueryMechanism.selectAllRowsFromTable(ExpressionQueryMechanism.java:2759)
        at org.eclipse.persistence.internal.queries.ExpressionQueryMechanism.selectAllRows(ExpressionQueryMechanism.java:2712)
        at org.eclipse.persistence.queries.ReadAllQuery.executeObjectLevelReadQuery(ReadAllQuery.java:584)
        at org.eclipse.persistence.queries.ObjectLevelReadQuery.executeDatabaseQuery(ObjectLevelReadQuery.java:1232)
        at org.eclipse.persistence.queries.DatabaseQuery.execute(DatabaseQuery.java:911)
        at org.eclipse.persistence.queries.ObjectLevelReadQuery.execute(ObjectLevelReadQuery.java:1191)
        at org.eclipse.persistence.queries.ReadAllQuery.execute(ReadAllQuery.java:485)
        at org.eclipse.persistence.queries.ObjectLevelReadQuery.executeInUnitOfWork(ObjectLevelReadQuery.java:1279)
        at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.internalExecuteQuery(UnitOfWorkImpl.java:2983)
        at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1898)
        at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1880)
        at org.eclipse.persistence.internal.indirection.QueryBasedValueHolder.instantiate(QueryBasedValueHolder.java:135)
        at org.eclipse.persistence.internal.indirection.QueryBasedValueHolder.instantiateForUnitOfWorkValueHolder(QueryBasedValueHolder.java:153)
        at org.eclipse.persistence.internal.indirection.UnitOfWorkValueHolder.instantiateImpl(UnitOfWorkValueHolder.java:162)
        at org.eclipse.persistence.internal.indirection.UnitOfWorkValueHolder.instantiate(UnitOfWorkValueHolder.java:236)
        at org.eclipse.persistence.internal.indirection.DatabaseValueHolder.getValue(DatabaseValueHolder.java:97)
        at org.eclipse.persistence.indirection.IndirectList.buildDelegate(IndirectList.java:275)
        at org.eclipse.persistence.indirection.IndirectList.getDelegate(IndirectList.java:458)
        at org.eclipse.persistence.indirection.IndirectList$1.<init>(IndirectList.java:602)
        at org.eclipse.persistence.indirection.IndirectList.listIterator(IndirectList.java:601)
        at org.eclipse.persistence.indirection.IndirectList.iterator(IndirectList.java:560)
        at scala.collection.convert.Wrappers$JIterableWrapper.iterator(Wrappers.scala:55)
        at scala.collection.IterableLike.foreach(IterableLike.scala:74)
        at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
        at scala.collection.generic.Growable.$plus$plus$eq(Growable.scala:62)
        at scala.collection.generic.Growable.$plus$plus$eq$(Growable.scala:53)
        at scala.collection.mutable.ListBuffer.$plus$plus$eq(ListBuffer.scala:184)
        at scala.collection.mutable.ListBuffer.$plus$plus$eq(ListBuffer.scala:47)
        at scala.collection.TraversableLike.to(TraversableLike.scala:678)
        at scala.collection.TraversableLike.to$(TraversableLike.scala:675)
        at scala.collection.AbstractTraversable.to(Traversable.scala:108)
        at scala.collection.TraversableOnce.toList(TraversableOnce.scala:299)
        at scala.collection.TraversableOnce.toList$(TraversableOnce.scala:299)
        at scala.collection.AbstractTraversable.toList(Traversable.scala:108)
        at no.officenet.origo.email.application.util.EmailMessageBuilder$$anonfun$no$officenet$origo$email$application$util$EmailMessageBuilder$$findIcalPart$1.applyOrElse(EmailMessageBuilder.scala:643)
        at no.officenet.origo.email.application.util.EmailMessageBuilder$$anonfun$no$officenet$origo$email$application$util$EmailMessageBuilder$$findIcalPart$1.applyOrElse(EmailMessageBuilder.scala:634)
        at scala.collection.TraversableOnce.collectFirst(TraversableOnce.scala:148)
        at scala.collection.TraversableOnce.collectFirst$(TraversableOnce.scala:135)
        at scala.collection.AbstractTraversable.collectFirst(Traversable.scala:108)
        at no.officenet.origo.email.application.util.EmailMessageBuilder$.no$officenet$origo$email$application$util$EmailMessageBuilder$$findIcalPart(EmailMessageBuilder.scala:634)
        at no.officenet.origo.email.application.util.EmailMessageBuilder$.$anonfun$findIcalPart$19(EmailMessageBuilder.scala:670)
        at scala.Option.orElse(Option.scala:447)
        at no.officenet.origo.email.application.util.EmailMessageBuilder$.findIcalPart(EmailMessageBuilder.scala:670)
        at no.officenet.origo.email.application.service.EmailAppService.$anonfun$enqueueIcalFromIncomingEmail$2(EmailAppService.scala:321)
        at no.officenet.origo.email.application.service.EmailAppService.$anonfun$enqueueIcalFromIncomingEmail$2$adapted(EmailAppService.scala:319)
        at net.liftweb.common.Full.foreach(Box.scala:852)
        at no.officenet.origo.email.application.service.EmailAppService.enqueueIcalFromIncomingEmail(EmailAppService.scala:319)
        at no.officenet.origo.email.application.service.EmailAppService.enqueueIcalFromIncomingEmail$(EmailAppService.scala:318)
        at no.officenet.origo.email.application.service.EmailAppServiceImpl.enqueueIcalFromIncomingEmail(EmailAppService.scala:1862)
        at no.officenet.origo.email.application.service.EmailAppService.processRecipient(EmailAppService.scala:436)
        at no.officenet.origo.email.application.service.EmailAppService.processRecipient$(EmailAppService.scala:411)
        at no.officenet.origo.email.application.service.EmailAppServiceImpl.processRecipient(EmailAppService.scala:1862)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at no.officenet.origo.core.infrastructure.logging.LoggingTimeInterceptor.invoke(LoggingTimeInterceptor.scala:24)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:353)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:99)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:93)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
        at com.sun.proxy.$Proxy211.processRecipient(Unknown Source)
        at no.officenet.origo.emailimport.application.consumer.EmailImportDeliveryConsumer.$anonfun$process$6(EmailImportDeliveryConsumer.scala:29)
        at no.officenet.origo.core.util.ControlUtils$.autoClose(ControlUtils.scala:87)
        at no.officenet.origo.emailimport.application.consumer.EmailImportDeliveryConsumer.$anonfun$process$4(EmailImportDeliveryConsumer.scala:29)
        at scala.Option.foreach(Option.scala:407)
        at no.officenet.origo.emailimport.application.consumer.EmailImportDeliveryConsumer.$anonfun$process$3(EmailImportDeliveryConsumer.scala:27)
        at no.officenet.origo.emailimport.application.consumer.EmailImportDeliveryConsumer.$anonfun$process$3$adapted(EmailImportDeliveryConsumer.scala:25)
        at scala.Option.foreach(Option.scala:407)
        at no.officenet.origo.emailimport.application.consumer.EmailImportDeliveryConsumer.process(EmailImportDeliveryConsumer.scala:25)
        at no.officenet.origo.emailimport.application.consumer.EmailImportDeliveryConsumer.process(EmailImportDeliveryConsumer.scala:16)
        at no.officenet.origo.core.domain.service.queue.QueueService.$anonfun$notifyConsumers$8(QueueService.scala:86)
        at no.officenet.origo.core.domain.service.queue.QueueService.$anonfun$notifyConsumers$8$adapted(QueueService.scala:84)
        at scala.collection.immutable.List.foreach(List.scala:392)
        at no.officenet.origo.core.domain.service.queue.QueueService.$anonfun$notifyConsumers$7(QueueService.scala:84)
        at no.officenet.origo.core.domain.service.queue.QueueService.$anonfun$notifyConsumers$7$adapted(QueueService.scala:83)
        at scala.Option.foreach(Option.scala:407)
        at no.officenet.origo.core.domain.service.queue.QueueService.$anonfun$notifyConsumers$4(QueueService.scala:83)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
        at no.officenet.origo.core.infrastructure.jpa.TransactionHelper$.$anonfun$doInTransactionWithoutResult$1(TransactionHelper.scala:22)
        at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:140)
        at no.officenet.origo.core.infrastructure.jpa.TransactionHelper$.doInTransactionWithoutResult(TransactionHelper.scala:21)
        at no.officenet.origo.core.domain.service.queue.QueueService.notifyConsumers(QueueService.scala:78)
        at no.officenet.origo.core.domain.service.queue.QueueService.notifyConsumers$(QueueService.scala:64)
        at no.officenet.origo.core.domain.service.queue.QueueServiceImpl.notifyConsumers(QueueService.scala:217)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at no.officenet.origo.core.infrastructure.logging.LoggingTimeInterceptor.invoke(LoggingTimeInterceptor.scala:24)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:353)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:99)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:93)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
        at com.sun.proxy.$Proxy210.notifyConsumers(Unknown Source)
        at no.officenet.origo.core.integration.QueueActor$$anonfun$messageHandler$1.applyOrElse(QueueMasterServer.scala:78)
        at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:38)
        at net.liftweb.actor.LiftActor.execTranslate(LiftActor.scala:503)
        at net.liftweb.actor.LiftActor.execTranslate$(LiftActor.scala:495)
        at no.officenet.origo.core.integration.QueueActor.execTranslate(QueueMasterServer.scala:59)
        at net.liftweb.actor.SpecializedLiftActor.proc2(LiftActor.scala:304)
        at net.liftweb.actor.SpecializedLiftActor.$anonfun$processMailbox$1(LiftActor.scala:226)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
        at net.liftweb.common.CommonLoanWrapper$.apply(LoanWrapper.scala:60)
        at net.liftweb.common.CommonLoanWrapper$.$anonfun$apply$1(LoanWrapper.scala:61)
        at no.officenet.origo.core.util.LoanWrapperHelper$$anon$2.apply(LoanWrapperHelper.scala:47)
        at net.liftweb.common.CommonLoanWrapper$.apply(LoanWrapper.scala:61)
        at net.liftweb.common.CommonLoanWrapper$.$anonfun$apply$1(LoanWrapper.scala:61)
        at no.officenet.origo.core.integration.OrigoActor$$anon$1.apply(OrigoActor.scala:28)
        at net.liftweb.common.CommonLoanWrapper$.apply(LoanWrapper.scala:61)
        at net.liftweb.actor.SpecializedLiftActor.around(LiftActor.scala:241)
        at net.liftweb.actor.SpecializedLiftActor.around$(LiftActor.scala:239)
        at no.officenet.origo.core.integration.QueueActor.around(QueueMasterServer.scala:59)
        at net.liftweb.actor.SpecializedLiftActor.processMailbox(LiftActor.scala:226)
        at net.liftweb.actor.SpecializedLiftActor.$anonfun$$bang$3(LiftActor.scala:189)
        at net.liftweb.actor.LAScheduler$$anon$2$$anon$3.run(LiftActor.scala:76)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:830)
Caused by: java.sql.SQLException: com.impossibl.shadow.io.netty.handler.codec.TooLongFrameException: Adjusted frame length exceeds 20971520: 29028403 - discarded
        at com.impossibl.postgres.jdbc.PGStatement.executeStatement(PGStatement.java:384)
        at com.impossibl.postgres.jdbc.PGPreparedStatement.execute(PGPreparedStatement.java:339)
        at com.impossibl.postgres.jdbc.PGPreparedStatement.executeQuery(PGPreparedStatement.java:357)
        at com.impossibl.postgres.jdbc.PGPreparedStatement.executeQuery(PGPreparedStatement.java:106)
        at jdk.internal.reflect.GeneratedMethodAccessor97.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
        at org.apache.tomcat.jdbc.pool.interceptor.AbstractQueryReport$StatementProxy.invoke(AbstractQueryReport.java:210)
        at com.sun.proxy.$Proxy475.executeQuery(Unknown Source)
        at jdk.internal.reflect.GeneratedMethodAccessor97.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
        at org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:114)
        at com.sun.proxy.$Proxy475.executeQuery(Unknown Source)
        at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.executeSelect(DatabaseAccessor.java:1015)
        at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.basicExecuteCall(DatabaseAccessor.java:651)
        ... 139 more
Caused by: com.impossibl.shadow.io.netty.handler.codec.TooLongFrameException: Adjusted frame length exceeds 20971520: 29028403 - discarded
        at com.impossibl.shadow.io.netty.handler.codec.LengthFieldBasedFrameDecoder.fail(LengthFieldBasedFrameDecoder.java:513)
        at com.impossibl.shadow.io.netty.handler.codec.LengthFieldBasedFrameDecoder.failIfNecessary(LengthFieldBasedFrameDecoder.java:491)
        at com.impossibl.shadow.io.netty.handler.codec.LengthFieldBasedFrameDecoder.exceededFrameLength(LengthFieldBasedFrameDecoder.java:378)
        at com.impossibl.shadow.io.netty.handler.codec.LengthFieldBasedFrameDecoder.decode(LengthFieldBasedFrameDecoder.java:421)
        at com.impossibl.shadow.io.netty.handler.codec.LengthFieldBasedFrameDecoder.decode(LengthFieldBasedFrameDecoder.java:334)
        at com.impossibl.shadow.io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:505)
        at com.impossibl.shadow.io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:444)
        at com.impossibl.shadow.io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:283)
        at com.impossibl.shadow.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
        at com.impossibl.shadow.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
        at com.impossibl.shadow.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
        at com.impossibl.shadow.io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1422)
        at com.impossibl.shadow.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
        at com.impossibl.shadow.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
        at com.impossibl.shadow.io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:931)
        at com.impossibl.shadow.io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
        at com.impossibl.shadow.io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:700)
        at com.impossibl.shadow.io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:635)
        at com.impossibl.shadow.io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:552)
        at com.impossibl.shadow.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:514)
        at com.impossibl.shadow.io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1044)
        at com.impossibl.shadow.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        ... 1 more
```
The `string_content` in this case is:
```
SELECT entity_id, size, length(string_content) FROM origo_email_part WHERE (parent_id = 1) ORDER BY part_index ASC;
┌───────────┬──────────┬──────────┐
│ entity_id │   size   │  length  │
├───────────┼──────────┼──────────┤
│         2 │        0 │   [NULL] │
│         5 │ 28964957 │ 28964957 │
└───────────┴──────────┴──────────┘
(2 rows)
```
28964957 bytes, which is to be mapped to a JAVA-String, I suspect this is the problem, causing `TooLongFrameException: Adjusted frame length exceeds 20971520: 29028403 - discarded`

**Comment by kdubb** [comment]
Yeah I missed that, it was in the original app log you posted as well... your loading blobs that are _large_. The default for maximum message size is 20mb so it's kicking back this frame.

Set the max message parameter to whatever you want in your connection properties.

See [protocol.message.size.max](http://impossibl.github.io/pgjdbc-ng/docs/0.8.3/user-guide/#_protocol_settings)

**Comment by andreak** [comment]
The thing is not the blob actually but I'm storing the contents of "text type mime-parts in email" in a varchar-field in the DB, and in this case it's an part with mime-type text/html which is that large. Yes - someone sent a large (28964957 bytes) report, saved as HTML from MS Word, in email.
I'll adjust the `protocol.message.size.max` and see if I'm able to handle such large parts better.

**Comment by andreak** [comment]
Would be cool if the Exception mentioned that raising `protocol.message.size.max` is an option.
