### ISSUE TITLE
Infinite wait during XA transaction manager recovery

### ISSUE THREAD

**Issue by brettwooldridge** [impossibl/pgjdbc-ng#46]
This may (or may not) be related to the XA DataSource work on jesperpederson's ds branch...

Following an unclean shutdown of my application (I had to kill it), my XA Transaction Manager (Bitronix) tries to rollback transactions that are uncommitted in its logs ... this is causing an infinite wait during startup.  I am pretty sure that Bitronix is "correct" in its behavior, both because I have worked on it, and because it is a very mature transaction manager over 8 years old supporting a wide array of databases.

Here is the stacktrace of the hang:

"main" prio=5 tid=0x00007f9b6100b000 nid=0x80b in Object.wait() [0x00000001088a4000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
    at java.lang.Object.wait(Native Method)
    - waiting on <0x000000012ae73150> (a com.impossibl.postgres.protocol.v30.BindExecCommandImpl$BindExecCommandListener)
    at com.impossibl.postgres.protocol.v30.CommandImpl.waitFor(CommandImpl.java:120)
    - locked <0x000000012ae73150> (a com.impossibl.postgres.protocol.v30.BindExecCommandImpl$BindExecCommandListener)
    at com.impossibl.postgres.protocol.v30.BindExecCommandImpl.execute(BindExecCommandImpl.java:337)
    at com.impossibl.postgres.protocol.v30.ProtocolImpl.execute(ProtocolImpl.java:365)
    - locked <0x00000001322f3d40> (a com.impossibl.postgres.protocol.v30.ProtocolImpl)
    at com.impossibl.postgres.jdbc.PGConnectionImpl.execute(PGConnectionImpl.java:364)
    at com.impossibl.postgres.jdbc.PGStatement.executeStatement(PGStatement.java:366)
    at com.impossibl.postgres.jdbc.PGSimpleStatement.execute(PGSimpleStatement.java:105)
    at com.impossibl.postgres.jdbc.PGSimpleStatement.execute(PGSimpleStatement.java:124)
    at com.impossibl.postgres.jdbc.PGSimpleStatement.executeUpdate(PGSimpleStatement.java:185)
    at com.impossibl.postgres.jdbc.xa.PGXAConnection.rollback(PGXAConnection.java:363)
    at bitronix.tm.recovery.RecoveryHelper.rollback(RecoveryHelper.java:215)
    at bitronix.tm.recovery.Recoverer.rollback(Recoverer.java:474)
    at bitronix.tm.recovery.Recoverer.rollbackAbortedBranchesOfResource(Recoverer.java:450)
    at bitronix.tm.recovery.Recoverer.rollbackAbortedTransactions(Recoverer.java:415)
    at bitronix.tm.recovery.Recoverer.run(Recoverer.java:150)
    at bitronix.tm.BitronixTransactionManager.<init>(BitronixTransactionManager.java:85)
    at bitronix.tm.TransactionManagerServices.getTransactionManager(TransactionManagerServices.java:70)
    at bitronix.tm.osgi.Activator.start(Activator.java:97)
    at org.eclipse.osgi.framework.internal.core.BundleContextImpl$1.run(BundleContextImpl.java:711)
    at java.security.AccessController.doPrivileged(Native Method)
    at org.eclipse.osgi.framework.internal.core.BundleContextImpl.startActivator(BundleContextImpl.java:702)
    at org.eclipse.osgi.framework.internal.core.BundleContextImpl.start(BundleContextImpl.java:683)
    at org.eclipse.osgi.framework.internal.core.BundleHost.startWorker(BundleHost.java:381)
    at org.eclipse.osgi.framework.internal.core.AbstractBundle.start(AbstractBundle.java:300)
    at org.eclipse.osgi.framework.internal.core.AbstractBundle.start(AbstractBundle.java:292)
    at org.ziptie.crates.CrateStarterElf.start(CrateStarterElf.java:282)
    at org.ziptie.crates.CrateStarterElf.activateBundles(CrateStarterElf.java:193)
    at org.ziptie.crates.CrateStarterElf.activateBundles(CrateStarterElf.java:219)
    at org.ziptie.zap.bootstrap.ZApplication.start(ZApplication.java:193)
    at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:110)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:79)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:353)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:180)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.main(EclipseStarter.java:151)

**Comment by kdubb** [comment]
After 65f29228aa52d34f9a4dbad4edce12fb396b9aa4 this should report an SQLException
