### ISSUE TITLE
Unhandled message: 2 @ com.impossibl.postgres.protocol.v30.PrepareRequest$Handler

### ISSUE THREAD

**Issue by pkolaric** [impossibl/pgjdbc-ng#495]
Any idea  what causes this exception?

`
java.lang.IllegalStateException: Unhandled message: 2 @ com.impossibl.postgres.protocol.v30.PrepareRequest$Handler 	at com.impossibl.postgres.protocol.v30.MessageDispatchHandler.dispatch(MessageDispatchHandler.java:214) 	at com.impossibl.postgres.protocol.v30.MessageDispatchHandler.channelRead(MessageDispatchHandler.java:149) 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352) 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:328) 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:315) 	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:429) 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:283) 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352) 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1422) 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:931) 	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:792) 	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:483) 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:383) 	at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1044) 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) 	at java.lang.Thread.run(Thread.java:748)
`

**Comment by allllan** [comment]
I'm facing this issue as well... very cryptic error message. Not sure where to start to troubleshoot it.

**Comment by kdubb** [comment]
@pkolaric @allllan In the past this has been because the `protocol.message.size.max` has been reached (e.g. #457). The default size is 20MB.  Would that apply to either of your scenarios?

And yes, this is a very cryptic message 😞

**Comment by allllan** [comment]
I’ve switched over to the official postgres driver.  It does not experience this issue.

**Comment by hoxu** [comment]
Any updates regarding this issue? We are seeing this randomly in integration tests running on Google Cloud Build.

**Comment by kdubb** [comment]
@hoxu Please add all the information you have. Driver & server versions, stack traces, query causing the issue. I am eager to fix this issue but finding a reproducible case has been a dead end.

**Comment by hoxu** [comment]
@kdubb it seems I have hard time finding time to debug this issue. I think the best way to proceed would be to enable some more logging on our GCB, and wait until we see the issue pop up once more.

If you have any suggestions what traces to enable (pgjdbc-ng side or PostgreSQL), let me know.

**Comment by kdubb** [comment]
@hoxu https://impossibl.github.io/pgjdbc-ng/docs/0.8.7/user-guide/#logging-tracing Covers all the tracing that can be enabled.
