### ISSUE TITLE
[Almost] All test failing?

### ISSUE THREAD

**Issue by brettwooldridge** [impossibl/pgjdbc-ng#52]
I have a fresh clone on two machines (both Macs) with Postgres 9.3.0.0 and both are failing a significant number of tests.  Previously all tests passed, hence the fresh clones.  I haven't updated in several weeks, but when I did (just now)...

When the build failed on the first machine, I cloned clean from git on a second machine, but the errors are the same.

This is representative of most of the errors:

testEmptyQuery(com.impossibl.postgres.jdbc.StatementTest)  Time elapsed: 0.079 sec  <<< ERROR!
java.sql.SQLException: Error parsing SQL at position 0
at com.impossibl.postgres.jdbc.PGConnectionImpl.parseSQL(PGConnectionImpl.java:343)
at com.impossibl.postgres.jdbc.PGSimpleStatement.execute(PGSimpleStatement.java:122)
at com.impossibl.postgres.jdbc.StatementTest.testEmptyQuery(StatementTest.java:126)

testParsingSemiColons(com.impossibl.postgres.jdbc.StatementTest)  Time elapsed: 0.08 sec  <<< ERROR!
java.sql.SQLException: Error parsing SQL at position 155
at com.impossibl.postgres.jdbc.PGConnectionImpl.parseSQL(PGConnectionImpl.java:343)
at com.impossibl.postgres.jdbc.PGSimpleStatement.execute(PGSimpleStatement.java:122)
at com.impossibl.postgres.jdbc.StatementTest.testParsingSemiColons(StatementTest.java:384)

Running com.impossibl.postgres.jdbc.StructTest
Tests run: 4, Failures: 0, Errors: 4, Skipped: 0, Time elapsed: 0.352 sec <<< FAILURE!
testResultSetTypeMap(com.impossibl.postgres.jdbc.StructTest)  Time elapsed: 0.089 sec  <<< ERROR!
java.sql.SQLException: Error parsing SQL at position 36
at com.impossibl.postgres.jdbc.PGConnectionImpl.parseSQL(PGConnectionImpl.java:343)
at com.impossibl.postgres.jdbc.PGSimpleStatement.execute(PGSimpleStatement.java:122)
at com.impossibl.postgres.jdbc.PGSimpleStatement.executeQuery(PGSimpleStatement.java:175)
at com.impossibl.postgres.jdbc.StructTest.testResultSetTypeMap(StructTest.java:149)

testSpecificType(com.impossibl.postgres.jdbc.StructTest)  Time elapsed: 0.088 sec  <<< ERROR!
java.sql.SQLException: Error parsing SQL at position 36
at com.impossibl.postgres.jdbc.PGConnectionImpl.parseSQL(PGConnectionImpl.java:343)
at com.impossibl.postgres.jdbc.PGSimpleStatement.execute(PGSimpleStatement.java:122)
at com.impossibl.postgres.jdbc.PGSimpleStatement.executeQuery(PGSimpleStatement.java:175)
at com.impossibl.postgres.jdbc.StructTest.testSpecificType(StructTest.java:122)

testConnectionTypeMap(com.impossibl.postgres.jdbc.StructTest)  Time elapsed: 0.083 sec  <<< ERROR!
java.sql.SQLException: Error parsing SQL at position 36
at com.impossibl.postgres.jdbc.PGConnectionImpl.parseSQL(PGConnectionImpl.java:343)
at com.impossibl.postgres.jdbc.PGSimpleStatement.execute(PGSimpleStatement.java:122)
at com.impossibl.postgres.jdbc.PGSimpleStatement.executeQuery(PGSimpleStatement.java:175)
at com.impossibl.postgres.jdbc.StructTest.testConnectionTypeMap(StructTest.java:179)

testConnectionTypeMapFail(com.impossibl.postgres.jdbc.StructTest)  Time elapsed: 0.092 sec  <<< ERROR!
java.sql.SQLException: Error parsing SQL at position 36
at com.impossibl.postgres.jdbc.PGConnectionImpl.parseSQL(PGConnectionImpl.java:343)
at com.impossibl.postgres.jdbc.PGSimpleStatement.execute(PGSimpleStatement.java:122)
at com.impossibl.postgres.jdbc.PGSimpleStatement.executeQuery(PGSimpleStatement.java:175)
at com.impossibl.postgres.jdbc.StructTest.testConnectionTypeMapFail(StructTest.java:205)

Any ideas?

**Comment by brettwooldridge** [comment]
Weird thing is, if I connect to the postgres database using SquirrelSQL (and the pgjdbc-ng) driver, and run some of the failing SQL manually, it succeeds.

**Comment by kdubb** [comment]
I was quite certain I had tested the PR that did this before merging... but I guess I did not.  Don't know how that happened.  Either way, it's fixed.
