### ISSUE TITLE
ArrayIndexOutOfBounds when setting enum with very high oid

### ISSUE THREAD

**Issue by davidwheeler123** [impossibl/pgjdbc-ng#527]
We've encountered an unusual error on one of our dev environments, where it seems the oid for "enum" is > 2^31 (and therefore negative for signed int), and this is causing pgjdbc-ng to throw an ArrayIndexOutOfBounds exception

```
2021-02-01T04:14:17.932204324Z Caused by: java.lang.ArrayIndexOutOfBoundsException: Index -1846158966 out of bounds for length 4096
2021-02-01T04:14:17.932213915Z 	at java.base/java.lang.invoke.VarHandle$1.apply(Unknown Source)
2021-02-01T04:14:17.932343417Z 	at java.base/java.lang.invoke.VarHandle$1.apply(Unknown Source)
2021-02-01T04:14:17.932367979Z 	at java.base/jdk.internal.util.Preconditions$1.apply(Unknown Source)
2021-02-01T04:14:17.932376899Z 	at java.base/jdk.internal.util.Preconditions$1.apply(Unknown Source)
2021-02-01T04:14:17.932382713Z 	at java.base/jdk.internal.util.Preconditions.outOfBounds(Unknown Source)
2021-02-01T04:14:17.932388616Z 	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Unknown Source)
2021-02-01T04:14:17.932405831Z 	at java.base/jdk.internal.util.Preconditions.checkIndex(Unknown Source)
2021-02-01T04:14:17.932413144Z 	at java.base/java.lang.invoke.VarHandleObjects$Array.compareAndSet(Unknown Source)
2021-02-01T04:14:17.932419435Z 	at java.base/java.lang.invoke.VarHandleGuards.guard_LILL_Z(Unknown Source)
2021-02-01T04:14:17.932544638Z 	at java.base/java.util.concurrent.atomic.AtomicReferenceArray.compareAndSet(Unknown Source)
2021-02-01T04:14:17.932553735Z 	at com.impossibl.postgres.protocol.TypeOid.valueOf(TypeOid.java:43)
2021-02-01T04:14:17.932557924Z 	at com.impossibl.postgres.protocol.v30.MessageDispatchHandler.receiveParameterDescriptions(MessageDispatchHandler.java:496)
2021-02-01T04:14:17.932561965Z 	at com.impossibl.postgres.protocol.v30.MessageDispatchHandler.parseAndDispatch(MessageDispatchHandler.java:311)
2021-02-01T04:14:17.932565935Z 	at com.impossibl.postgres.protocol.v30.MessageDispatchHandler.dispatch(MessageDispatchHandler.java:192)
2021-02-01T04:14:17.932569943Z 	at com.impossibl.postgres.protocol.v30.MessageDispatchHandler.channelRead(MessageDispatchHandler.java:147)
```

This is triggered by executing a query with an enum parameter.

If we take a look at the OID in question

```
select oid, * from pg_type where oid = -1846158966;
-[ RECORD 1 ]--+-----------
oid            | 2448808330
typname        | status_t
typnamespace   | 2448808018
typowner       | 2461479530
typlen         | 4
typbyval       | t
typtype        | e
typcategory    | E
typispreferred | f
typisdefined   | t
typdelim       | ,
typrelid       | 0
typelem        | 0
typarray       | 2448808329
typinput       | enum_in
typoutput      | enum_out
typreceive     | enum_recv
typsend        | enum_send
typmodin       | -
typmodout      | -
typanalyze     | -
typalign       | i
typstorage     | p
typnotnull     | f
typbasetype    | 0
typtypmod      | -1
typndims       | 0
typcollation   | 0
typdefaultbin  |
typdefault     |
typacl         |
```

can see that the oid is high enough to be treated as a negative number. 

It seems to me that this line: https://github.com/impossibl/pgjdbc-ng/blob/415afcf15c2435a6b3f3995b12c0463210151893/driver/src/main/java/com/impossibl/postgres/protocol/v30/MessageDispatchHandler.java#L558 should be using `readUnsignedInt()` rather than `readInt()` - or else `TypeOid` should do a little more checking to ensure that it's not going to exceed the bounds of the array (on the lower side)

I'm not sure how to reproduce this, you'd need to set up a db with enum type having a very high oid. if you can give some tips I'd be happy to do the legwork. 

I will submit a PR, I can test against our dev environment.

**Comment by davidwheeler123** [comment]
Fixed this issue and another in #528
