### ISSUE TITLE
Hang connecting to database after database restart

### ISSUE THREAD

**Issue by kwesterfeld2** [impossibl/pgjdbc-ng#539]
Our database is built with a postgresql frontend, and our query manager uses pjdbc-ng to talk to PG.  If PG goes down for any reason, we have encountered a rare occurrence where JDBC connections can no longer be made to the database once restarted.

We tracked down this issue to a thread that is spinning out of control in a recursive cleanup pattern.  The thread is one of the pgjdbc-ng netty I/O servicing threads, which explains why no new connections can be made to the database.  In this hang this thread is pegging the CPU at a constant 100% usage, and does not ever recover.

Excerpted below is the top of the stack.  

What is happening? 
 - some statement is stranded on a connection
 - connection needs to be closed
 - connection cleanup is pushed onto executor thread
 - cleanup begins, and starts cleaning up statements
 - statement checks transaction status, gets an exception and calls internalClose() on the PGDirectConnection
 - repeats

Fix is trivial, change:

```
  private void closeStatements() {
    closeStatements(activeStatements);
    activeStatements.clear();
  }
```
to:

```
  private void closeStatements() {
    List<WeakReference<PGStatement>> _activeStatements = new ArrayList<>(activeStatements);
    activeStatements.clear();
    closeStatements(_activeStatements);
  }

```

Offending stack (excerpt):

```

"PG-JDBC I/O (1)" #2425 daemon prio=5 os_prio=0 tid=0x00007ef3cc0f91a0 nid=0x87dc runnable [0x00007ef64db8a000]
   java.lang.Thread.State: RUNNABLE
	at java.lang.SecurityManager.getClassContext(Native Method)
	at java.lang.Exception$SecurityManagerEx.getThrowableContext(Exception.java:147)
	at java.lang.Exception.<init>(Exception.java:37)
	at java.io.IOException.<init>(IOException.java:47)
	at java.nio.channels.ClosedChannelException.<init>(ClosedChannelException.java:52)
	at com.impossibl.postgres.protocol.v30.ServerConnection.getTransactionStatus(ServerConnection.java:182)
	at com.impossibl.postgres.jdbc.PGDirectConnection.getTransactionStatus(PGDirectConnection.java:295)
	at com.impossibl.postgres.jdbc.PGDirectConnection.execute(PGDirectConnection.java:474)
	at com.impossibl.postgres.jdbc.PGDirectConnection.execute(PGDirectConnection.java:450)
	at com.impossibl.postgres.jdbc.PreparedQuery.dispose(PreparedQuery.java:200)
	at com.impossibl.postgres.jdbc.QueryScroller.close(PGResultSet.java:1991)
	at com.impossibl.postgres.jdbc.PGResultSet.internalClose(PGResultSet.java:592)
	at com.impossibl.postgres.jdbc.PGStatement.closeResultSets(PGStatement.java:209)
	at com.impossibl.postgres.jdbc.PGStatement.closeResultSets(PGStatement.java:227)
	at com.impossibl.postgres.jdbc.PGStatement.internalClose(PGStatement.java:273)
	at com.impossibl.postgres.jdbc.PGPreparedStatement.internalClose(PGPreparedStatement.java:211)
	at com.impossibl.postgres.jdbc.PGDirectConnection.closeStatements(PGDirectConnection.java:392)
	at com.impossibl.postgres.jdbc.PGDirectConnection.closeStatements(PGDirectConnection.java:408)
	at com.impossibl.postgres.jdbc.PGDirectConnection.internalClose(PGDirectConnection.java:676)
	at com.impossibl.postgres.jdbc.PGDirectConnection.getTransactionStatus(PGDirectConnection.java:298)
	at com.impossibl.postgres.jdbc.PGDirectConnection.execute(PGDirectConnection.java:474)
	at com.impossibl.postgres.jdbc.PGDirectConnection.execute(PGDirectConnection.java:450)
	at com.impossibl.postgres.jdbc.PreparedQuery.dispose(PreparedQuery.java:200)
	at com.impossibl.postgres.jdbc.QueryScroller.close(PGResultSet.java:1991)
	at com.impossibl.postgres.jdbc.PGResultSet.internalClose(PGResultSet.java:592)
	at com.impossibl.postgres.jdbc.PGStatement.closeResultSets(PGStatement.java:209)
	at com.impossibl.postgres.jdbc.PGStatement.closeResultSets(PGStatement.java:227)
	at com.impossibl.postgres.jdbc.PGStatement.internalClose(PGStatement.java:273)
	at com.impossibl.postgres.jdbc.PGPreparedStatement.internalClose(PGPreparedStatement.java:211)
	at com.impossibl.postgres.jdbc.PGDirectConnection.closeStatements(PGDirectConnection.java:392)
	at com.impossibl.postgres.jdbc.PGDirectConnection.closeStatements(PGDirectConnection.java:408)
	at com.impossibl.postgres.jdbc.PGDirectConnection.internalClose(PGDirectConnection.java:676)
	at com.impossibl.postgres.jdbc.PGDirectConnection.getTransactionStatus(PGDirectConnection.java:298)
	at com.impossibl.postgres.jdbc.PGDirectConnection.execute(PGDirectConnection.java:474)
	at com.impossibl.postgres.jdbc.PGDirectConnection.execute(PGDirectConnection.java:450)
	at com.impossibl.postgres.jdbc.PreparedQuery.dispose(PreparedQuery.java:200)
	at com.impossibl.postgres.jdbc.QueryScroller.close(PGResultSet.java:1991)
	at com.impossibl.postgres.jdbc.PGResultSet.internalClose(PGResultSet.java:592)
	at com.impossibl.postgres.jdbc.PGStatement.closeResultSets(PGStatement.java:209)
	at com.impossibl.postgres.jdbc.PGStatement.closeResultSets(PGStatement.java:227)
	at com.impossibl.postgres.jdbc.PGStatement.internalClose(PGStatement.java:273)
	at com.impossibl.postgres.jdbc.PGPreparedStatement.internalClose(PGPreparedStatement.java:211)
	at com.impossibl.postgres.jdbc.PGDirectConnection.closeStatements(PGDirectConnection.java:392)
	at com.impossibl.postgres.jdbc.PGDirectConnection.closeStatements(PGDirectConnection.java:408)
	at com.impossibl.postgres.jdbc.PGDirectConnection.internalClose(PGDirectConnection.java:676)
	at com.impossibl.postgres.jdbc.PGDirectConnection.getTransactionStatus(PGDirectConnection.java:298)
	at com.impossibl.postgres.jdbc.PGDirectConnection.execute(PGDirectConnection.java:474)
	at com.impossibl.postgres.jdbc.PGDirectConnection.execute(PGDirectConnection.java:450)
	at com.impossibl.postgres.jdbc.PreparedQuery.dispose(PreparedQuery.java:200)
	at com.impossibl.postgres.jdbc.QueryScroller.close(PGResultSet.java:1991)
	at com.impossibl.postgres.jdbc.PGResultSet.internalClose(PGResultSet.java:592)
	at com.impossibl.postgres.jdbc.PGStatement.closeResultSets(PGStatement.java:209)
	at com.impossibl.postgres.jdbc.PGStatement.closeResultSets(PGStatement.java:227)
	at com.impossibl.postgres.jdbc.PGStatement.internalClose(PGStatement.java:273)
	at com.impossibl.postgres.jdbc.PGPreparedStatement.internalClose(PGPreparedStatement.java:211)
	at com.impossibl.postgres.jdbc.PGDirectConnection.closeStatements(PGDirectConnection.java:392)
	at com.impossibl.postgres.jdbc.PGDirectConnection.closeStatements(PGDirectConnection.java:408)
	at com.impossibl.postgres.jdbc.PGDirectConnection.internalClose(PGDirectConnection.java:676)
	at com.impossibl.postgres.jdbc.PGDirectConnection.getTransactionStatus(PGDirectConnection.java:298)
```

**Comment by kwesterfeld2** [comment]
An attempt to "fix" this in our use-case ended up moving the problem a bit, but it is interesting all the same that I was also able to induce a similar stacktrace that ends with ConcurrentModificationException: 
```
2021-05-19T06:50:24.781-04:00 | WARN  | PG-JDBC I/O (2)                          | io.netty.channel.AbstractChannelHandlerContext                   | An exception was thrown by a user handler while handling an exceptionCaught event
java.util.ConcurrentModificationException
        at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)[:1.8.0_92]
        at java.util.ArrayList$Itr.next(ArrayList.java:851)[:1.8.0_92]
        at com.impossibl.postgres.jdbc.PGStatement.closeResultSets(PGStatement.java:204)
        at com.impossibl.postgres.jdbc.PGStatement.closeResultSets(PGStatement.java:227)
        at com.impossibl.postgres.jdbc.PGStatement.internalClose(PGStatement.java:273)
        at com.impossibl.postgres.jdbc.PGPreparedStatement.internalClose(PGPreparedStatement.java:211)
        at com.impossibl.postgres.jdbc.PGDirectConnection.closeStatements(PGDirectConnection.java:392)
        at com.impossibl.postgres.jdbc.PGDirectConnection.closeStatements(PGDirectConnection.java:408)
        at com.impossibl.postgres.jdbc.PGDirectConnection.internalClose(PGDirectConnection.java:676)
        at com.impossibl.postgres.jdbc.PGDirectConnection.getTransactionStatus(PGDirectConnection.java:298)
        at com.impossibl.postgres.jdbc.PGDirectConnection.execute(PGDirectConnection.java:474)
        at com.impossibl.postgres.jdbc.PGDirectConnection.execute(PGDirectConnection.java:450)
        at com.impossibl.postgres.jdbc.PreparedQuery.dispose(PreparedQuery.java:200)
        at com.impossibl.postgres.jdbc.QueryScroller.close(PGResultSet.java:1991)
        at com.impossibl.postgres.jdbc.PGResultSet.internalClose(PGResultSet.java:592)
        at com.impossibl.postgres.jdbc.PGStatement.closeResultSets(PGStatement.java:209)
        at com.impossibl.postgres.jdbc.PGStatement.closeResultSets(PGStatement.java:227)
        at com.impossibl.postgres.jdbc.PGStatement.internalClose(PGStatement.java:273)
        at com.impossibl.postgres.jdbc.PGPreparedStatement.internalClose(PGPreparedStatement.java:211)
        at com.impossibl.postgres.jdbc.PGDirectConnection.closeStatements(PGDirectConnection.java:392)
        at com.impossibl.postgres.jdbc.PGDirectConnection.closeStatements(PGDirectConnection.java:408)
        at com.impossibl.postgres.jdbc.PGDirectConnection.internalClose(PGDirectConnection.java:676)
        at com.impossibl.postgres.jdbc.PGDirectConnection.getTransactionStatus(PGDirectConnection.java:298)
        at com.impossibl.postgres.jdbc.PGDirectConnection.execute(PGDirectConnection.java:474)
        at com.impossibl.postgres.jdbc.PGDirectConnection.execute(PGDirectConnection.java:450)
        at com.impossibl.postgres.jdbc.PreparedQuery.dispose(PreparedQuery.java:200)
        at com.impossibl.postgres.jdbc.QueryScroller.close(PGResultSet.java:1991)
        at com.impossibl.postgres.jdbc.PGResultSet.internalClose(PGResultSet.java:592)
        at com.impossibl.postgres.jdbc.PGStatement.closeResultSets(PGStatement.java:209)
        at com.impossibl.postgres.jdbc.PGStatement.closeResultSets(PGStatement.java:227)
        at com.impossibl.postgres.jdbc.PGStatement.internalClose(PGStatement.java:273)
        at com.impossibl.postgres.jdbc.PGPreparedStatement.internalClose(PGPreparedStatement.java:211)
        at com.impossibl.postgres.jdbc.PGDirectConnection.closeStatements(PGDirectConnection.java:392)
        at com.impossibl.postgres.jdbc.PGDirectConnection.closeStatements(PGDirectConnection.java:408)
        at com.impossibl.postgres.jdbc.PGDirectConnection.internalClose(PGDirectConnection.java:676)
        at com.impossibl.postgres.jdbc.PGDirectConnection.getTransactionStatus(PGDirectConnection.java:298)
        at com.impossibl.postgres.jdbc.PGDirectConnection.execute(PGDirectConnection.java:474)
        at com.impossibl.postgres.jdbc.PGDirectConnection.execute(PGDirectConnection.java:450)
        at com.impossibl.postgres.jdbc.PreparedQuery.dispose(PreparedQuery.java:200)
```

**Comment by kdubb** [comment]
@kwesterfeld2 Awesome find.

I'm thinking there should be a check against "double close". For example maybe we have a `closing` flag or status enum that is set and `PGDirectConnection.internalClose` can check and set it. This would prevent other similar issues from occurring.

I'll be looking at this today and cutting a release with this important fix.

**Comment by kwesterfeld2** [comment]
@kdubb  there is a cleanup similar pattern in PGStatement.java, and I thought maybe I should tidy that up, but then the semantics seemed different.  In that use case, the cleanup happens but the list is not cleared.  I decided that making the change there would be over-reaching because I did not encounter a problem with it, but you may want to look there as well.

**Comment by kwesterfeld2** [comment]
@kdubb ...ping.   Will there be a 0.8.8 release imminent with this fix?

**Comment by kdubb** [comment]
Yessir, actively being worked on 👍

**Comment by kwesterfeld2** [comment]
Thank YOU, much appreciated

**Comment by kdubb** [comment]
@kwesterfeld2 What version of the driver are you using? I'm having trouble reproducing this with the current HEAD of develop.

**Comment by kdubb** [comment]
Also, debugging in the current code has large differences for the line #'s and the stack trace line #'s.

**Comment by kdubb** [comment]
@kwesterfeld2 I've made a reproducer test and managed to opened #541 to address all the double close issues I can currently see.

**Comment by kdubb** [comment]
@kwesterfeld2  Please confirm using latest `0.9-SNAPSHOT` and report back. I will release a `0.8.8` once we are agreed this is a stable fix in a live environment.

**Comment by kwesterfeld2** [comment]
I'm not sure how to test with 0.9-SNAPSHOT; our builds require pulling from maven central at this time, or at least a known repository.  

Also, the issue we found once weeks ago and then had an engineer build tests to reproduce it, ran those tests in repetition and it didn't repro for 7 days or so.  We were able to then capture the stacktraces and diagnostics to figure out what was going on.

Confirming also we reproduced this on version 0.8.2.   

My theory is that we were using auto commit false, setFetchSize to 1000 and were in the middle of querying a large-ish result set when the database crashed.  The recovery of the crash was actually the issue; the close connection logic then kicked in.

**Comment by kdubb** [comment]
Ok. I think this is the fix.  I was able to produce a nearly identical call chain and without these changes it indeed recurses.

FYI, all merged PR's automatically update the next snapshot. And the snapshots are pulled from Maven Central Snapshot repo. See here `https://central.sonatype.org/publish/publish-guide/#ossrh-usage-notes`.
