### ISSUE TITLE
Unable to convert from java.time.LocalDate to timestamp

### ISSUE THREAD

**Issue by Arthurm1** [impossibl/pgjdbc-ng#544]
Passing a `LocalDate` as a param into a `PreparedStatement` that expects a Postgres `Timestamp` param results in an Exception:
```
Caused by: com.impossibl.postgres.jdbc.PGSQLSimpleException: Unable to convert from java.time.LocalDate to timestamp
	at com.impossibl.postgres.jdbc.ErrorUtils.makeSQLException(ErrorUtils.java:164)
	at com.impossibl.postgres.jdbc.PGPreparedStatement.set(PGPreparedStatement.java:200)
	at com.impossibl.postgres.jdbc.PGPreparedStatement.set(PGPreparedStatement.java:163)
	at com.impossibl.postgres.jdbc.PGPreparedStatement.setObject(PGPreparedStatement.java:796)
	... 151 more
Caused by: com.impossibl.postgres.system.ConversionException: Unable to convert from java.time.LocalDate to timestamp
	at com.impossibl.postgres.system.procs.TimestampsWithoutTZ.convertInput(TimestampsWithoutTZ.java:111)
	at com.impossibl.postgres.system.procs.TimestampsWithoutTZ.access$400(TimestampsWithoutTZ.java:63)
	at com.impossibl.postgres.system.procs.TimestampsWithoutTZ$BinEncoder.encodeValue(TimestampsWithoutTZ.java:224)
	at com.impossibl.postgres.system.procs.BaseBinaryEncoder.encode(BaseEncoders.java:59)
	at com.impossibl.postgres.system.procs.BaseBinaryEncoder.encode(BaseEncoders.java:41)
	at com.impossibl.postgres.jdbc.PGPreparedStatement.set(PGPreparedStatement.java:193)
	... 157 more
```

Passing a `LocalDateTime` works fine.

The exception is raised in `com.impossibl.postgres.system.procs.TimestampsWithoutTZ#convertInput`

Its opposite method  `com.impossibl.postgres.system.procs.TimestampsWithoutTZ#convertOutput` seems to handle this situation.  Other JDBC drivers I've used can also handle it.

Could the following be added to `convertInput` or something similar...
```
if (value instanceof LocalDate) {
  return ((LocalDate) value).atStartOfDay();
}
```

**Comment by kdubb** [comment]
Probably not.  These type of conversions are explicitly _not_ specified in JDBC 4.2. As previous JDBC versions can attest to, "convenience conversions" for date time types cause nothing but problems. It's why `java.sql.Date`, `java.sql.Time` and `java.sql.Timestamp` have been deprecated; all the conversions without a timezone/calendar specified are ambiguous.

For example, a `LocalDate` explicitly has _no_ timezone but a `Timestamp` implicitly has one.  What timezone _should_ the new timestamp be in? I say "should" because we have to pick _something_. Should it be the current machine's time zone? UTC? or should we use the database's?

The JDBC spec say's `LocalDate` can only convert to `CHAR`, `VARCHAR`, `LONGVARCHAR`, `DATE` and that's what we support.

As far as `covertOutput` is concerned _if_ an unambiguous conversion can be made the driver will do it as an extension; I nearly removed all of these when the date/time handling was rewritten for 4.2 compliance (and I kind of wish I did).

**Comment by kdubb** [comment]
Btw, what's wrong with calling `myLocalDate.atStartOfDay().atZone(myTZ)` in your calls to `PreparedStatement`? It ensures you get it converted consistently because you're doing the conversion.

**Comment by Arthurm1** [comment]
I was migrating from the other Postgres driver and noticed this difference.  I can understand the need to stick to the spec though every driver seems to implement the JDBC 'standard' in a slightly different way :-)

I can change my code - I just thought this was an oversight after seeing the `convertOutput` implementation

When I was referring to `timestamp` above I meant the Postgres data type, not `java.sql.Timestamp`.  None of Java's `java.time.LocalTime`, `java.time.LocalDate`, `java.time.LocalDateTime` or PostgreSQL's `Timestamp` type have a timezone as far as I'm aware so there should be no ambiguity converting between them and I shouldn't need `.atZone(xx)`.

**Comment by kdubb** [comment]
You are correct. When you are not using a PostgreSQL "tz" type, you should should "local" types in Java. When you _are_ using a "tz" type in PostgreSQL you should be using an "Offset" type.

I should never have suggested `atZone`.. JDBC 4.2 also doesn't supported any of the "Zone" types from `java.time`. I should have said `atOffset`.
