### ISSUE TITLE
Wildfly 10 

### ISSUE THREAD

**Issue by sandyrhg** [impossibl/pgjdbc-ng#548]
I'm trying to set up a datasource on a Wildfly 10 (on jdk-8) by following the User guide but the connection test returns the error below :

`Caused by: java.lang.IllegalArgumentException: Unsupported event loop group type: NioEventLoopGroup
        at com.impossibl.postgres.protocol.v30.ServerConnectionShared.getEventLoopGroup(ServerConnectionShared.java:89)
        at com.impossibl.postgres.protocol.v30.ServerConnectionFactory.createInetSocketChannel(ServerConnectionFactory.java:340)
        at com.impossibl.postgres.protocol.v30.ServerConnectionFactory.createChannel(ServerConnectionFactory.java:278)
        at com.impossibl.postgres.protocol.v30.ServerConnectionFactory.connect(ServerConnectionFactory.java:165)
        ... 39 more`

I've tried the older versions (down to 0.8.4) also but with no success.
I know the version was tested against Wildfly 15 so I was wondering is there might  be some library conflicts causing this.
The only dependencies declared in the module.xml file are : 

- javax.api
- javax.transaction.api

**Comment by kdubb** [comment]
@sandyrhg Did you solve this or discover why it wasn't working?

**Comment by sandyrhg** [comment]
The problem was caused by a stackoverflow buried under a few exceptions (starting with a TargetInvocationException) so increasing my app server's stack solved the problem.
