### ISSUE TITLE
Correct way to insert into TEXT?

### ISSUE THREAD

**Issue by tlf30** [impossibl/pgjdbc-ng#551]
Hello,
I am feeling a little stumped (and I feel like I have done this before). I am attempting to use a prepared statement to insert into a table that has two TEXT datatype fields, and am running into issues. 

```
try (Connection db = getDb()) {
            db.setAutoCommit(true);
            try (PreparedStatement pstmt = db.prepareStatement("INSERT INTO users (username, password, data) VALUES (?, crypt(?, gen_salt('bf', 8)), ?)", Statement.RETURN_GENERATED_KEYS)) {
                pstmt.setObject(1, username, PGType.TEXT);
                pstmt.setObject(2, password, PGType.TEXT);
                pstmt.setObject(3, CharaHelper.convert(player));

                int affectedRows = pstmt.executeUpdate();
                if (affectedRows > 0) {
                    ResultSet keys = pstmt.getGeneratedKeys();
                    if (keys.next()) {
                        player.setId(keys.getLong(1)); //Get player ID for new player
                    } else {
                        return false; //No generated key means something went wrong...
                    }
                    keys.close();
                } else {
                    return false;
                }
            }
        } catch (SQLException ex) {
            LOGGER.log(Level.SEVERE, "Failed to create new player in database!", ex);
            return false;
        }
```

I get:
```
[2021-06-09 19:39:27] [SEVERE ] Failed to create new player in database! 
com.impossibl.postgres.jdbc.PGSQLSimpleException: wrong data type: 1015, expected 1009
	at com.impossibl.postgres.jdbc.ErrorUtils.makeSQLException(ErrorUtils.java:197)
	at com.impossibl.postgres.jdbc.ErrorUtils.makeSQLException(ErrorUtils.java:174)
	at com.impossibl.postgres.jdbc.ErrorUtils.makeSQLException(ErrorUtils.java:161)
	at com.impossibl.postgres.jdbc.PGDirectConnection.execute(PGDirectConnection.java:514)
	at com.impossibl.postgres.jdbc.PGDirectConnection.executeTimed(PGDirectConnection.java:522)
	at com.impossibl.postgres.jdbc.PreparedQuery.executeStatement(PreparedQuery.java:121)
	at com.impossibl.postgres.jdbc.PreparedQuery.execute(PreparedQuery.java:194)
	at com.impossibl.postgres.jdbc.PGStatement.executeStatement(PGStatement.java:378)
	at com.impossibl.postgres.jdbc.PGPreparedStatement.execute(PGPreparedStatement.java:339)
	at com.impossibl.postgres.jdbc.PGPreparedStatement.executeLargeUpdate(PGPreparedStatement.java:373)
	at com.impossibl.postgres.jdbc.PGPreparedStatement.executeUpdate(PGPreparedStatement.java:367)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
	at io.tlf.outside.server.persistence.SqlSerializer.newPlayer(SqlSerializer.java:680)
```
I originally tried to do just a normal `setString` and it has the same error. Is it possible to insert into a TEXT datatype? 

Using pgjdbc-ng version `0.8.8` with postgresql 12. 

Any help is greatly appreciated.

Thank you,
Trevor

**Comment by kdubb** [comment]
`text` is old `25` and `varchar` is `1043`...  `1015` and `1009` are arrays of them (e.g. `text[]` and `varchar[]`).

**Comment by tlf30** [comment]
Ah, I had made the assumption that it was my `TEXT` fields because I just changed those, but the other field I changed was a VARCHAR array to a text array as well. It just so happens the third object in that insert, several layers down is in fact that array.
This is looking like the UDT generation issue. 

```
CREATE TYPE CHARA AS
(
    component    TEXT,
    inv          INV_ITEM[],
    quests       QUEST[],
    stats        STAT_REF[],
    loc          LOCATION,
    achievements ACHIEVEMENT[],
    actions      TEXT[],
    object       TEXT
);
```

Gets generated as:
```
package io.tlf.outside.server.persistence.generated;

import com.impossibl.postgres.api.jdbc.PGAnyType;
import com.impossibl.postgres.api.jdbc.PGType;
import java.sql.JDBCType;
import java.sql.SQLData;
import java.sql.SQLException;
import java.sql.SQLInput;
import java.sql.SQLOutput;

public class Chara implements SQLData {
  private static final String TYPE_NAME = "public.chara";

  public static final PGAnyType TYPE = new PGAnyType() {
    @Override
    public String getName() {
      return Chara.TYPE_NAME;
    }

    @Override
    public String getVendor() {
      return "UDT Generated";
    }

    @Override
    public Integer getVendorTypeNumber() {
      return null;
    }

    @Override
    public Class getJavaType() {
      return Chara.class;
    }
  };

  private String component;

  private InvItem[] inv;

  private Quest[] quests;

  private StatRef[] stats;

  private Location loc;

  private Achievement[] achievements;

  private String[] actions;

  private String object;

  @Override
  public String getSQLTypeName() throws SQLException {
    return TYPE_NAME;
  }

  public String getComponent() {
    return component;
  }

  public void setComponent(String component) {
    this.component = component;
  }

  public InvItem[] getInv() {
    return inv;
  }

  public void setInv(InvItem[] inv) {
    this.inv = inv;
  }

  public Quest[] getQuests() {
    return quests;
  }

  public void setQuests(Quest[] quests) {
    this.quests = quests;
  }

  public StatRef[] getStats() {
    return stats;
  }

  public void setStats(StatRef[] stats) {
    this.stats = stats;
  }

  public Location getLoc() {
    return loc;
  }

  public void setLoc(Location loc) {
    this.loc = loc;
  }

  public Achievement[] getAchievements() {
    return achievements;
  }

  public void setAchievements(Achievement[] achievements) {
    this.achievements = achievements;
  }

  public String[] getActions() {
    return actions;
  }

  public void setActions(String[] actions) {
    this.actions = actions;
  }

  public String getObject() {
    return object;
  }

  public void setObject(String object) {
    this.object = object;
  }

  @Override
  public void readSQL(SQLInput in, String typeName) throws SQLException {
    this.component = in.readString();
    this.inv = in.readObject(InvItem[].class);
    this.quests = in.readObject(Quest[].class);
    this.stats = in.readObject(StatRef[].class);
    this.loc = in.readObject(Location.class);
    this.achievements = in.readObject(Achievement[].class);
    this.actions = in.readObject(String[].class);
    this.object = in.readString();
  }

  @Override
  public void writeSQL(SQLOutput out) throws SQLException {
    out.writeObject(this.component, PGType.TEXT);
    out.writeObject(this.inv, JDBCType.ARRAY);
    out.writeObject(this.quests, JDBCType.ARRAY);
    out.writeObject(this.stats, JDBCType.ARRAY);
    out.writeObject(this.loc, Location.TYPE);
    out.writeObject(this.achievements, JDBCType.ARRAY);
    out.writeObject(this.actions, JDBCType.ARRAY);
    out.writeObject(this.object, PGType.TEXT);
  }
}
```

Take note the `actions` field. I just removed it from the table and regenerated and it works as expected. I re-introduced the `actions` field and regenerate the error is present. It looks like the UDT generator generates a `TEXT[]` as if it is a `VARCHAR(#)[]`.
I recall seeing an issue like this on the issue tracker here, but I am not able to find it...

**Comment by tlf30** [comment]
@kdubb I built a simple test case for this one: https://github.com/tlf30/pgjdbc-ng-test5
I noticed 3 things:
1. Cannot insert with null value into TEXT[] with UDT gen mapping
2. Cannot insert string[] value into TEXT[] with UDT gen mapping
3. The kotlin std for the UDT gen is not coming across as a dependency and must be specified manually in the pom in order to run the UDT generator. 

Let me know if you need anything else.

Thank you,
Trevor

**Comment by tlf30** [comment]
A fix is to modify the UDT generator to create a `TEXT` array type.
```
new PGAnyType() {
      @Override
      public Class<?> getJavaType() {
        return String[].class;
      }

      @Override
      public String getName() {
        return "TEXT";
      }

      @Override
      public String getVendor() {
        return VENDOR_NAME;
      }

      @Override
      public Integer getVendorTypeNumber() {
        return 1009;
      }
    }
```

Then it will correctly write the string array into a text array in the UDT. 

Perhaps this type needs to be added to PGType as `TEXT_ARRAY`, as that would make it even simpler for others to use.
