### ISSUE TITLE
Driver throws java.time.format.DateTimeParseException

### ISSUE THREAD

**Issue by kwesterfeld2** [impossibl/pgjdbc-ng#552]
Our application is doing a "setString()" on a PreparedStatement, whose parameter is a SQL interval.  In prior versions of the driver, this string would be passed on to PG, but recent versions now try to convert the value to a java.time entity.  The problem is, we are passing a legal interval value into setString(), which PG can parse, but the java.time.Period cannot.  The simplest of these is simply passing "1 day".

Sample SQL:

```
  select * 
  from foo
  where (current_timestamp - start_time) < '1 day'
```

In this case "1 day"  is a parameter ?

```
java.time.format.DateTimeParseException: Text cannot be parsed to a Period
        at java.time.Period.parse(Period.java:350)[:1.8.0_252]
        at com.impossibl.postgres.api.data.Interval.parse(Interval.java:336)
        at com.impossibl.postgres.system.procs.AutoConvertingEncoder$FromStringConverter.convert(BaseEncoders.java:93)
        at com.impossibl.postgres.system.procs.AutoConvertingBinaryEncoder.convertInput(BaseEncoders.java:126)
        at com.impossibl.postgres.system.procs.AutoConvertingBinaryEncoder.encodeValue(BaseEncoders.java:141)
        at com.impossibl.postgres.system.procs.BaseBinaryEncoder.encode(BaseEncoders.java:59)
        at com.impossibl.postgres.system.procs.BaseBinaryEncoder.encode(BaseEncoders.java:41)
        at com.impossibl.postgres.jdbc.PGPreparedStatement.set(PGPreparedStatement.java:193)
        at com.impossibl.postgres.jdbc.PGPreparedStatement.set(PGPreparedStatement.java:163)
        at com.impossibl.postgres.jdbc.PGPreparedStatement.setString(PGPreparedStatement.java:669)
```

**Comment by kdubb** [comment]
@kwesterfeld2 The decision was made to use "Java" time classes (which are usable in Java) in the driver and that is what you are seeing here.  This change happened at the beginning of the 0.8.x series.

I think the only real solution (without rewriting driver internals) is to cast the value in the SQL query; using something like `the_interval::interval::varchar`.  This would ensure the driver treats the value as text while the server will convert it to an interval as wanted.

In the long term I'm open to rethinking this idea or figuring out a better solution for passing intervals directly to the server.

**Comment by kwesterfeld2** [comment]
We aren't having a problem selecting intervals, we are having a problem sending a parameter to a query as an interval.  I am not sure how your workaround helps.  

I think what is suitable here is to send the value as a string to pg (as the driver did befor) since the setString() api is used.  Converting the value to an interval when PG can do this better simply makes the driver less compatible.

**Comment by kdubb** [comment]
Sorry, for parameters cast the parameter placeholder. `?::interval::varchar` (actually with PostgreSQL the server might just accept `?::varchar`).  It will send it to the server as text.

**Comment by kwesterfeld2** [comment]
good idea—worth a shot!

KURT WESTERFELD // Yellowbrick Data
________________________________
