### ISSUE TITLE
Caused by: com.impossibl.postgres.jdbc.PGSQLSimpleException: Connection Error  - after postgres upgrade to 14

### ISSUE THREAD

**Issue by Ondreychikishev** [impossibl/pgjdbc-ng#607]
Hi,
got this error after postgres upgrade to 14 version:

Caused by: com.impossibl.postgres.jdbc.PGSQLSimpleException: Connection Error: Timeout starting connection
    at com.impossibl.postgres.jdbc.ErrorUtils.makeSQLException(ErrorUtils.java:138)
    at com.impossibl.postgres.jdbc.ConnectionUtil.createConnection(ConnectionUtil.java:326)
    at com.impossibl.postgres.jdbc.AbstractDataSource.createConnection(AbstractDataSource.java:125)
    at com.impossibl.postgres.jdbc.PGDataSource.getConnection(PGDataSource.java:71)
    at com.impossibl.postgres.jdbc.PGDataSource.getConnection(PGDataSource.java:63)
    at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
    at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
    at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Unknown Source)
    at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source)
    at kotlin.reflect.jvm.internal.calls.CallerImpl$Constructor.call(CallerImpl.kt:41)
    at kotlin.reflect.jvm.internal.KCallableImpl.call(KCallableImpl.kt:108)
    at kotlin.reflect.jvm.internal.KCallableImpl.callDefaultMethod$kotlin_reflection(KCallableImpl.kt:159)
    at kotlin.reflect.jvm.internal.KCallableImpl.callBy(KCallableImpl.kt:112)
    at org.springframework.beans.BeanUtils$KotlinDelegate.instantiateClass(BeanUtils.java:903)
    at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:198)
    ... 68 common frames omitted
Caused by: java.io.IOException: Timeout starting connection
    at com.impossibl.postgres.protocol.v30.ServerConnectionFactory.startup(ServerConnectionFactory.java:459)
    at com.impossibl.postgres.protocol.v30.ServerConnectionFactory.connect(ServerConnectionFactory.java:200)
    at com.impossibl.postgres.protocol.v30.ServerConnectionFactory.connect(ServerConnectionFactory.java:143)
    at com.impossibl.postgres.protocol.v30.ServerConnectionFactory.connect(ServerConnectionFactory.java:124)
    at com.impossibl.postgres.system.BasicContext.<init>(BasicContext.java:213)
    at com.impossibl.postgres.jdbc.PGDirectConnection.<init>(PGDirectConnection.java:236)
    at com.impossibl.postgres.jdbc.ConnectionUtil.createConnection(ConnectionUtil.java:317)
    ... 83 common frames omitted

**Comment by davidwheeler123** [comment]
Hi @Ondreychikishev thanks for the report. What makes you think pgjdbc-ng is the cause of this issue?

**Comment by hermanekt** [comment]
We have exact same issue after upgrade from 12>15. Classic connection for fine, but with PGEvent lock DB completely. We have workaround with restart DB. But every time when we are deploying new version we have this issue back and we need to restart DB.

**Comment by FrostbittenKing** [comment]
Hi @Ondreychikishev This looks deceptively similar to an issue I reported almost three years ago. https://github.com/impossibl/pgjdbc-ng/issues/567. Nobody reacted. Debugging this for days, we patched the code ourselves, since the issue was only in kubernetes environments, because it uses /dev/random hardcoded, and that was too slow in newer openshift environments.... Previously the openshift environments / service images we used symlinked /dev/random to /dev/urandom. That was changed in openshfit 4, and suddently I had to debug an unexplainable connection timeout for days.
