### ISSUE TITLE
Fails to encode BigDecimal(0) with java.lang.ArrayIndexOutOfBoundsException:

### ISSUE THREAD

**Issue by andreak** [impossibl/pgjdbc-ng#68]
If one has a BigDecimal(0) this loop in Numerics.encodeFromString():210 will never end:

```
//Swallow leading zeros
while (numChars[ch] == '0')
  ch++;
```

resulting in ArrayIndexOutOfBoundsException: 1 on next iteration

This test shows the problem:

```
@RunWith(JUnit4.class)
public class NumericsTest {

  private Connection conn;

  @Before
  public void before() throws Exception {
    conn = TestUtil.openDB();
    TestUtil.createTable(conn, "numerictest", "id NUMERIC");
    conn.setAutoCommit(false);
  }

  @After
  public void after() throws SQLException {
    conn.setAutoCommit(true);
    TestUtil.dropTable(conn, "numerictest");
    TestUtil.closeDB(conn);
  }

  @Test
  public void testSetZero() throws Exception {

    PreparedStatement pstmt = conn.prepareStatement("INSERT INTO numerictest(id) VALUES (?)");

    pstmt.setBigDecimal(1, new BigDecimal("0"));
    pstmt.executeUpdate();

    pstmt.close();
  }

}
```

```
java.lang.ArrayIndexOutOfBoundsException: 1
    at com.impossibl.postgres.system.procs.Numerics.encodeFromString(Numerics.java:210)
    at com.impossibl.postgres.system.procs.Numerics.access$100(Numerics.java:42)
    at com.impossibl.postgres.system.procs.Numerics$BinEncoder.encode(Numerics.java:133)
    at com.impossibl.postgres.system.procs.BinaryEncoder.length(BinaryEncoder.java:51)
    at com.impossibl.postgres.protocol.v30.ProtocolImpl.lengthOfParams(ProtocolImpl.java:723)
    at com.impossibl.postgres.protocol.v30.ProtocolImpl.writeBind(ProtocolImpl.java:507)
    at com.impossibl.postgres.protocol.v30.BindExecCommandImpl.execute(BindExecCommandImpl.java:319)
    at com.impossibl.postgres.protocol.v30.ProtocolImpl.execute(ProtocolImpl.java:369)
    at com.impossibl.postgres.jdbc.PGConnectionImpl.execute(PGConnectionImpl.java:396)
    at com.impossibl.postgres.jdbc.PGStatement.executeStatement(PGStatement.java:368)
    at com.impossibl.postgres.jdbc.PGPreparedStatement.execute(PGPreparedStatement.java:205)
    at com.impossibl.postgres.jdbc.PGPreparedStatement.executeUpdate(PGPreparedStatement.java:229)
    at com.impossibl.postgres.jdbc.NumericsTest.testSetZero(NumericsTest.java:91)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
    at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
    at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
    at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:74)
    at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:202)
    at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:65)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:120)

```

**Comment by kdubb** [comment]
Thanks for the unit test.  Very helpful.  Fixed in 1195d36a0b8b40c0326205e103194e64eda72b58
