### ISSUE TITLE
Exception trying to map array of ROW-type

### ISSUE THREAD

**Issue by andreak** [impossibl/pgjdbc-ng#76]
Using version 0.3

This query:

```
select ARRAY(select ROW(1::bigint, 'nisse'::varchar));
```

gives the following output in pgsql-console:

```
andreak=# select ARRAY(select ROW(1::bigint, 'nisse'::varchar));
     array
---------------
 {"(1,nisse)"}
(1 row)
```

But trying to retrieve the value from JDBC results in this exception:

```
java.lang.ClassCastException: com.impossibl.postgres.types.PsuedoType cannot be cast to com.impossibl.postgres.types.ArrayType
    at com.impossibl.postgres.system.procs.Arrays$BinDecoder.decode(Arrays.java:81)
    at com.impossibl.postgres.system.procs.BinaryDecoder.decode(BinaryDecoder.java:44)
    at com.impossibl.postgres.protocol.v30.BindExecCommandImpl$BindExecCommandListener.rowData(BindExecCommandImpl.java:113)
    at com.impossibl.postgres.protocol.v30.ProtocolImpl.receiveRowData(ProtocolImpl.java:999)
    at com.impossibl.postgres.protocol.v30.ProtocolImpl.dispatch(ProtocolImpl.java:789)
    at com.impossibl.postgres.protocol.v30.MessageHandler.channelRead(MessageHandler.java:46)
    at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:338)
    at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:324)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:153)
    at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:338)
    at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:324)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785)
    at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:132)
    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:485)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:452)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:346)
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:101)
    at java.lang.Thread.run(Thread.java:724)
    at sun.rmi.transport.StreamRemoteCall.exceptionReceivedFromServer(StreamRemoteCall.java:275)
    at sun.rmi.transport.StreamRemoteCall.executeCall(StreamRemoteCall.java:252)
    at sun.rmi.server.UnicastRef.invoke(UnicastRef.java:161)
    at java.rmi.server.RemoteObjectInvocationHandler.invokeRemoteMethod(RemoteObjectInvocationHandler.java:194)
    at java.rmi.server.RemoteObjectInvocationHandler.invoke(RemoteObjectInvocationHandler.java:148)
    at com.sun.proxy.$Proxy147.execute(Unknown Source)
    at sun.reflect.GeneratedMethodAccessor880.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at com.intellij.execution.rmi.RemoteUtil$RemoteInvocationHandler.invoke(RemoteUtil.java:214)
    at com.sun.proxy.$Proxy148.execute(Unknown Source)
    at com.intellij.persistence.database.console.JdbcEngine.executeQueryInner(JdbcEngine.java:379)
```

Any hints on how to retrieve the value from such a result (array of bigint,varchar pairs)? Can I use a custom type for this, in that case are there any examples mapping custom-types I can look at?

Thanks.

**Comment by kdubb** [comment]
So the console is returning it as an array of strings; which doesn't help you much unless you want to parse them (this is the problem with the mainstream driver).

The way to do this would be to make a struct in your Postgres schema (e.g. BigIntVarChar) and then cast the row to that type:

```
select ARRAY(select ROW(1::bigint, 'nisse'::varchar)::BigIntVarChar);
```

Now you have Postgres returning an array of BigIntVarChars.  Now you can map a custom type to it using standard JDBC 4 methods.  You need to lookup SQLData, SQLInput, SQLOuput and the typeMap versions of the "getObject" methods on ResultSet

**Comment by andreak** [comment]
Thanks, I'll try. Do you have an example showing how to use/create such a custom-type in JAVA (the PG-part I'm ok with).

**Comment by andreak** [comment]
For completeness I'll write the class I use and the JDBC-mapping (it's Scala, but should be readable):

```
class BigIntVarcharJdbcData extends SQLData {

    var id: Long = 0
    var name: String = null
    var sqlType: String = null

    override def getSQLTypeName: String = {
        sqlType
    }

    override def writeSQL(stream: SQLOutput): Unit = {
        stream.writeLong(id)
        stream.writeNString(name)
    }

    override def readSQL(stream: SQLInput, typeName: String): Unit = {
        sqlType = typeName
        id = stream.readLong()
        name = stream.readString()
    }
}
```

Mapping:

```
val typeMap = {
    val h = new HashMap[String, Class[_]]()
    h.put("bigintvarchar", classOf[BigIntVarcharJdbcData])
    h
}

val parents = rs.getObject("project_parent_array", typeMap)
```

Closing the issue as it's not a flaw or bug in this driver.

Thanks for the help!

**Comment by kdubb** [comment]
Just an FYI for completeness...

the pgjdbc-ng-udt tool will generate these classes for you.  This is a small class and probably not worth the trouble but for larger projects with numerous, and probably changing, UDTs the tool should help a bit.

Of course... it only generates in java ;)

**Comment by andreak** [comment]
Jep:-)

Is there a way to register custom types in connection-pools, if you know what I mean? So I can register the type-mapping _one_ place and make use of it in the whole application, without having to pass the typeMap to rs.getObject every time?
