### ISSUE TITLE
Test failures in develop branch

### ISSUE THREAD

**Issue by brettwooldridge** [impossibl/pgjdbc-ng#81]
Anybody else seeing these?  

```
testTextCodecs[test-time](com.impossibl.postgres.jdbc.CodecTest)  Time elapsed: 0.039 sec  <<< FAILURE!
java.lang.AssertionError: expected:<09:30:30> but was:<01:30:30>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:144)
    at com.impossibl.postgres.jdbc.CodecTest.test(CodecTest.java:320)
    at com.impossibl.postgres.jdbc.CodecTest.testTextCodecs(CodecTest.java:157)

testTextCodecs[test-time[]](com.impossibl.postgres.jdbc.CodecTest)  Time elapsed: 0.034 sec  <<< FAILURE!
java.lang.AssertionError: expected:<09:30:30> but was:<01:30:30>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:144)
    at com.impossibl.postgres.jdbc.CodecTest.test(CodecTest.java:320)
    at com.impossibl.postgres.jdbc.CodecTest.test(CodecTest.java:290)
    at com.impossibl.postgres.jdbc.CodecTest.testTextCodecs(CodecTest.java:157)

testTextCodecs[test-timestruct](com.impossibl.postgres.jdbc.CodecTest)  Time elapsed: 0.039 sec  <<< FAILURE!
java.lang.AssertionError: expected:<09:30:30> but was:<01:30:30>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:144)
    at com.impossibl.postgres.jdbc.CodecTest.test(CodecTest.java:320)
    at com.impossibl.postgres.jdbc.CodecTest.test(CodecTest.java:303)
    at com.impossibl.postgres.jdbc.CodecTest.testTextCodecs(CodecTest.java:157)
```

**Comment by kdubb** [comment]
Recently change timezones?

**Comment by gsmet** [comment]
I have the same problem and another one but it's probably because I'm running the tests against a 9.1 server:

```
com.impossibl.postgres.jdbc.DatabaseMetaDataTest
testEscaping(com.impossibl.postgres.jdbc.DatabaseMetaDataTest)
com.impossibl.postgres.jdbc.PGSQLSimpleException: LIKE pattern must not end with escape character
    at com.impossibl.postgres.jdbc.ErrorUtils.makeSQLException(ErrorUtils.java:159)
    at com.impossibl.postgres.jdbc.ErrorUtils.makeSQLException(ErrorUtils.java:136)
    at com.impossibl.postgres.jdbc.PGConnectionImpl.execute(PGConnectionImpl.java:432)
    at com.impossibl.postgres.jdbc.PGStatement.executeStatement(PGStatement.java:372)
    at com.impossibl.postgres.jdbc.PGPreparedStatement.execute(PGPreparedStatement.java:239)
    at com.impossibl.postgres.jdbc.PGPreparedStatement.executeQuery(PGPreparedStatement.java:255)
```

This line is causing the issue:

``` java
rs = dbmd.getTables(null, null, "a\\", new String[] {"TABLE"});
```

**Comment by kdubb** [comment]
Yes those "LIKE pattern" failures are because of the 9.1 server.  I committed the changes to allow it to work against 9.1 but dropped off at those last two interesting bugs.  Consequently if somebody can fix those two issues the driver will test 100% against 9.1.

**Comment by brettwooldridge** [comment]
Ok.  Just so you know, I'm running against a 9.3.1.0 (18) server.  Yes, I might have changed timezones.  What is the fix in that case?  Edit the PostgreSQL config?

**Comment by gsmet** [comment]
Brett: the failures you have are due to timezone issues. That said, I don't know if it's just something to fix in the tests or a real problem in timezone implementation of the driver.

Kevin: I'll see what I can do for the 9.1 failure. There's something weird going on as I can't reproduce the issue from the PostgreSQL command line. I'll dig further this week or next week.

**Comment by kdubb** [comment]
Our test cases for timezones are lifted from the original project.  I am not sure if they suffer some of the same fragility as this... but I think I remember something being mentioned about it.  That being said, if they don't, it is most likely due to our implementation

**Comment by davecramer** [comment]
Ya, there are some failures around DST which are common.

Dave Cramer

**Comment by brettwooldridge** [comment]
I am no longer seeing this issue, so I am going to close it.
