### ISSUE TITLE
NullPointerException with PreparedStatement.addBatch() and non strandard types.

### ISSUE THREAD

**Issue by croudet** [impossibl/pgjdbc-ng#89]
With non standard types (e.g hstore, inet, long array), I got a NullPointerException when using batched prepared statement.

``` java
public void testInet() throws SQLException {
    try (Connection conn = DriverManager.getConnection(dbURL, username, password);
        Statement s = conn.createStatement();
        PreparedStatement ps = conn.prepareStatement("insert into testinet values (?)");
        ResultSet rs = s.executeQuery("select ip from testinet")) {
      while (rs.next()) {
        System.out.println(rs.getObject(1) + " - " + rs.getObject(1).getClass());
      }
      ps.setObject(1, new InetAddr("192.168.2.1"));
      ps.addBatch();
      ps.executeBatch();
      // ps.executeUpdate();
      try (ResultSet rs1 = s.executeQuery("select ip from testinet")) {
        while (rs1.next()) {
          System.out.println(rs1.getObject(1) + " - " + rs1.getObject(1).getClass());
        }
      }
    }
  }
```

```
Exception in thread "main" java.lang.NullPointerException
    at com.impossibl.postgres.jdbc.SQLTypeUtils.mapSetType(SQLTypeUtils.java:84)
    at com.impossibl.postgres.jdbc.PGPreparedStatement.coerceParameters(PGPreparedStatement.java:213)
    at com.impossibl.postgres.jdbc.PGPreparedStatement.addBatch(PGPreparedStatement.java:277)
```

It works fine with PreparedStatement.executeUpdate().

Modifying com.impossibl.postgres.jdbc.PGPreparedStatement.coerceParameters() test seems to fix the issue, but I am not sure it is the proper fix.

```
private void coerceParameters() throws SQLException {

    for (int c = 0, sz = parameterTypes.size(); c < sz; ++c) {

      Type parameterType = parameterTypes.get(c);
      Object parameterValue = parameterValues.get(c);
      if (parameterValue != null && parameterType != null) { // <--- check on parameterType added
        Class<?> targetType = mapSetType(parameterType);

        try {
          parameterValue = coerce(parameterValue, parameterType, targetType, Collections.<String, Class<?>>emptyMap(), TimeZone.getDefault(), connection);
        }
        catch (SQLException coercionException) {
          throw new SQLException("Error converting parameter " + c, coercionException);
        }
      }

      parameterValues.set(c, parameterValue);
    }

  }
```

**Comment by brettwooldridge** [comment]
I will take a look at this after the pull request for issue #96 is integrated.  The above fix may be acceptable, but we may be able to do better in terms of type validation when `setObject()` has been used.

**Comment by kdubb** [comment]
This proved to be the correct fix.
