### ISSUE TITLE
Using setString to set a MAC address causes IOException: invalid length

### ISSUE THREAD

**Issue by hakkikt** [impossibl/pgjdbc-ng#96]
Using setString (`stmt.setString(3, "00:50:56:00:00:09");`) to set a MAC throws an IOException. From the stack trace it looks like it's been converted to bytes first. 
The setBytes method (`stmt.setBytes(3, new byte[] {0,0x50,0x56,0,0,0x09});`) works as expected.

```
java.sql.SQLException: java.io.IOException: invalid length
     at com.impossibl.postgres.jdbc.PGConnectionImpl.execute(PGConnectionImpl.java:452)
     at com.impossibl.postgres.jdbc.PGStatement.executeStatement(PGStatement.java:372)
     at com.impossibl.postgres.jdbc.PGPreparedStatement.execute(PGPreparedStatement.java:239)
     at com.impossibl.postgres.jdbc.PGPreparedStatement.executeQuery(PGPreparedStatement.java:255)
     at com.impossibl.postgres.jdbc.PGPreparedStatement.executeQuery(PGPreparedStatement.java:92)
     at com.impossibl.postgres.jdbc.PGPreparedStatementDelegator.executeQuery(PGPreparedStatementDelegator.java:134)
     at _private_
With Throwable cause: java.io.IOException: invalid length
     at com.impossibl.postgres.system.procs.MacAddrs$BinEncoder.encode(MacAddrs.java:99)
     at com.impossibl.postgres.system.procs.BinaryEncoder.length(BinaryEncoder.java:51)
     at com.impossibl.postgres.protocol.v30.ProtocolImpl.lengthOfParams(ProtocolImpl.java:723)
     at com.impossibl.postgres.protocol.v30.ProtocolImpl.writeBind(ProtocolImpl.java:507)
     at com.impossibl.postgres.protocol.v30.BindExecCommandImpl.execute(BindExecCommandImpl.java:319)
     at com.impossibl.postgres.protocol.v30.ProtocolImpl.execute(ProtocolImpl.java:369)
     at com.impossibl.postgres.jdbc.PGConnectionImpl.execute(PGConnectionImpl.java:428)
     at com.impossibl.postgres.jdbc.PGStatement.executeStatement(PGStatement.java:372)
     at com.impossibl.postgres.jdbc.PGPreparedStatement.execute(PGPreparedStatement.java:239)
     at com.impossibl.postgres.jdbc.PGPreparedStatement.executeQuery(PGPreparedStatement.java:255)
     at com.impossibl.postgres.jdbc.PGPreparedStatement.executeQuery(PGPreparedStatement.java:92)
     at com.impossibl.postgres.jdbc.PGPreparedStatementDelegator.executeQuery(PGPreparedStatementDelegator.java:134)
    at _private_
```

**Comment by brettwooldridge** [comment]
What is the column type?

**Comment by hakkikt** [comment]
The could is the Postgres macaddr type.
